package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Beefshelves generated by hbm2java
 */
public class Beefshelves implements java.io.Serializable {

	private BeefshelvesId id;

	public Beefshelves() {
	}

	public Beefshelves(BeefshelvesId id) {
		this.id = id;
	}

	public BeefshelvesId getId() {
		return this.id;
	}

	public void setId(BeefshelvesId id) {
		this.id = id;
	}

}
