package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Beefs1 generated by hbm2java
 */
public class Beefs1 implements java.io.Serializable {

	private Beefs1Id id;

	public Beefs1() {
	}

	public Beefs1(Beefs1Id id) {
		this.id = id;
	}

	public Beefs1Id getId() {
		return this.id;
	}

	public void setId(Beefs1Id id) {
		this.id = id;
	}

}
