package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Beefs2 generated by hbm2java
 */
public class Beefs2 implements java.io.Serializable {

	private Beefs2Id id;

	public Beefs2() {
	}

	public Beefs2(Beefs2Id id) {
		this.id = id;
	}

	public Beefs2Id getId() {
		return this.id;
	}

	public void setId(Beefs2Id id) {
		this.id = id;
	}

}
