package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Beefcarts generated by hbm2java
 */
public class Beefcarts implements java.io.Serializable {

	private BeefcartsId id;

	public Beefcarts() {
	}

	public Beefcarts(BeefcartsId id) {
		this.id = id;
	}

	public BeefcartsId getId() {
		return this.id;
	}

	public void setId(BeefcartsId id) {
		this.id = id;
	}

}
