package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Beefs generated by hbm2java
 */
public class Beefs implements java.io.Serializable {

	private BeefsId id;

	public Beefs() {
	}

	public Beefs(BeefsId id) {
		this.id = id;
	}

	public BeefsId getId() {
		return this.id;
	}

	public void setId(BeefsId id) {
		this.id = id;
	}

}
