package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Beefs1Id generated by hbm2java
 */
public class Beefs1Id implements java.io.Serializable {

	private String i1;
	private String i2;
	private String i3;
	private String i4;
	private String i5;
	private String i6;
	private String i7;
	private String i8;
	private String i9;
	private String i10;
	private String i11;
	private String i12;
	private String i13;
	private String i14;
	private String i15;
	private String i16;
	private String i17;
	private String i18;
	private String i19;
	private String i20;
	private String i21;
	private String i22;
	private String i23;
	private String i24;
	private String i25;
	private String i26;
	private String i27;
	private String i28;
	private String i29;
	private String i30;
	private String i31;
	private String i32;
	private String i33;
	private String i34;
	private String i35;
	private String i36;
	private String i37;
	private String i38;
	private String i39;
	private String i40;
	private String i41;
	private String i42;
	private String i43;
	private String i44;
	private String i45;
	private String i46;
	private String i47;
	private String i48;
	private String i49;
	private String i50;
	private String i51;
	private String i52;
	private String i53;
	private String i54;
	private String i55;
	private String i56;
	private String i57;
	private String i58;
	private String i59;
	private String i60;
	private String i61;
	private String i62;
	private String i63;
	private String i64;
	private String i65;
	private String i66;
	private String i67;
	private String i68;
	private String i69;
	private String i70;
	private String i71;
	private String i72;
	private String i73;
	private String i74;
	private String i75;
	private String i76;
	private String i77;
	private String i78;
	private String i79;
	private String i80;
	private String i81;
	private String i82;
	private String i83;
	private String i84;
	private String i85;
	private String i86;
	private String i87;
	private String i88;
	private String i89;
	private String i90;
	private String i91;
	private String i92;
	private String i93;
	private String i94;
	private String i95;
	private String i96;
	private String i97;
	private String i98;
	private String i99;
	private String i100;
	private String i101;
	private String i102;
	private String i103;
	private String i104;
	private String i105;
	private String i106;
	private String i107;
	private String i108;
	private String i109;
	private String i110;
	private String i111;
	private String i112;
	private String i113;
	private String i114;
	private String i115;
	private String i116;
	private String i117;
	private String i118;
	private String i119;
	private String i120;
	private String i121;
	private String i122;
	private String i123;
	private String i124;
	private String i125;
	private String i126;
	private String i127;
	private String i128;
	private String i129;
	private String i130;
	private String i131;
	private String i132;
	private String i133;
	private String i134;
	private String i135;
	private String i136;
	private String i137;
	private String i138;
	private String i139;
	private String i140;
	private String i141;
	private String i142;
	private String i143;
	private String i144;
	private String i145;
	private String i146;
	private String i147;
	private String i148;
	private String i149;
	private String i150;
	private String i151;
	private String i152;
	private String i153;
	private String i154;
	private String i155;
	private String i156;
	private String i157;
	private String i158;
	private String i159;
	private String i160;
	private String i161;
	private String i162;
	private String i163;
	private String i164;
	private String i165;
	private String i166;
	private String i167;
	private String i168;
	private String i169;
	private String i170;
	private String i171;
	private String i172;
	private String i173;
	private String i174;
	private String i175;
	private String i176;
	private String i177;
	private String i178;
	private String i179;
	private String i180;

	public Beefs1Id() {
	}

	public Beefs1Id(String i1, String i2, String i3, String i4, String i5, String i6, String i7, String i8, String i9,
			String i10, String i11, String i12, String i13, String i14, String i15, String i16, String i17, String i18,
			String i19, String i20, String i21, String i22, String i23, String i24, String i25, String i26, String i27,
			String i28, String i29, String i30, String i31, String i32, String i33, String i34, String i35, String i36,
			String i37, String i38, String i39, String i40, String i41, String i42, String i43, String i44, String i45,
			String i46, String i47, String i48, String i49, String i50, String i51, String i52, String i53, String i54,
			String i55, String i56, String i57, String i58, String i59, String i60, String i61, String i62, String i63,
			String i64, String i65, String i66, String i67, String i68, String i69, String i70, String i71, String i72,
			String i73, String i74, String i75, String i76, String i77, String i78, String i79, String i80, String i81,
			String i82, String i83, String i84, String i85, String i86, String i87, String i88, String i89, String i90,
			String i91, String i92, String i93, String i94, String i95, String i96, String i97, String i98, String i99,
			String i100, String i101, String i102, String i103, String i104, String i105, String i106, String i107,
			String i108, String i109, String i110, String i111, String i112, String i113, String i114, String i115,
			String i116, String i117, String i118, String i119, String i120, String i121, String i122, String i123,
			String i124, String i125, String i126, String i127, String i128, String i129, String i130, String i131,
			String i132, String i133, String i134, String i135, String i136, String i137, String i138, String i139,
			String i140, String i141, String i142, String i143, String i144, String i145, String i146, String i147,
			String i148, String i149, String i150, String i151, String i152, String i153, String i154, String i155,
			String i156, String i157, String i158, String i159, String i160, String i161, String i162, String i163,
			String i164, String i165, String i166, String i167, String i168, String i169, String i170, String i171,
			String i172, String i173, String i174, String i175, String i176, String i177, String i178, String i179,
			String i180) {
		this.i1 = i1;
		this.i2 = i2;
		this.i3 = i3;
		this.i4 = i4;
		this.i5 = i5;
		this.i6 = i6;
		this.i7 = i7;
		this.i8 = i8;
		this.i9 = i9;
		this.i10 = i10;
		this.i11 = i11;
		this.i12 = i12;
		this.i13 = i13;
		this.i14 = i14;
		this.i15 = i15;
		this.i16 = i16;
		this.i17 = i17;
		this.i18 = i18;
		this.i19 = i19;
		this.i20 = i20;
		this.i21 = i21;
		this.i22 = i22;
		this.i23 = i23;
		this.i24 = i24;
		this.i25 = i25;
		this.i26 = i26;
		this.i27 = i27;
		this.i28 = i28;
		this.i29 = i29;
		this.i30 = i30;
		this.i31 = i31;
		this.i32 = i32;
		this.i33 = i33;
		this.i34 = i34;
		this.i35 = i35;
		this.i36 = i36;
		this.i37 = i37;
		this.i38 = i38;
		this.i39 = i39;
		this.i40 = i40;
		this.i41 = i41;
		this.i42 = i42;
		this.i43 = i43;
		this.i44 = i44;
		this.i45 = i45;
		this.i46 = i46;
		this.i47 = i47;
		this.i48 = i48;
		this.i49 = i49;
		this.i50 = i50;
		this.i51 = i51;
		this.i52 = i52;
		this.i53 = i53;
		this.i54 = i54;
		this.i55 = i55;
		this.i56 = i56;
		this.i57 = i57;
		this.i58 = i58;
		this.i59 = i59;
		this.i60 = i60;
		this.i61 = i61;
		this.i62 = i62;
		this.i63 = i63;
		this.i64 = i64;
		this.i65 = i65;
		this.i66 = i66;
		this.i67 = i67;
		this.i68 = i68;
		this.i69 = i69;
		this.i70 = i70;
		this.i71 = i71;
		this.i72 = i72;
		this.i73 = i73;
		this.i74 = i74;
		this.i75 = i75;
		this.i76 = i76;
		this.i77 = i77;
		this.i78 = i78;
		this.i79 = i79;
		this.i80 = i80;
		this.i81 = i81;
		this.i82 = i82;
		this.i83 = i83;
		this.i84 = i84;
		this.i85 = i85;
		this.i86 = i86;
		this.i87 = i87;
		this.i88 = i88;
		this.i89 = i89;
		this.i90 = i90;
		this.i91 = i91;
		this.i92 = i92;
		this.i93 = i93;
		this.i94 = i94;
		this.i95 = i95;
		this.i96 = i96;
		this.i97 = i97;
		this.i98 = i98;
		this.i99 = i99;
		this.i100 = i100;
		this.i101 = i101;
		this.i102 = i102;
		this.i103 = i103;
		this.i104 = i104;
		this.i105 = i105;
		this.i106 = i106;
		this.i107 = i107;
		this.i108 = i108;
		this.i109 = i109;
		this.i110 = i110;
		this.i111 = i111;
		this.i112 = i112;
		this.i113 = i113;
		this.i114 = i114;
		this.i115 = i115;
		this.i116 = i116;
		this.i117 = i117;
		this.i118 = i118;
		this.i119 = i119;
		this.i120 = i120;
		this.i121 = i121;
		this.i122 = i122;
		this.i123 = i123;
		this.i124 = i124;
		this.i125 = i125;
		this.i126 = i126;
		this.i127 = i127;
		this.i128 = i128;
		this.i129 = i129;
		this.i130 = i130;
		this.i131 = i131;
		this.i132 = i132;
		this.i133 = i133;
		this.i134 = i134;
		this.i135 = i135;
		this.i136 = i136;
		this.i137 = i137;
		this.i138 = i138;
		this.i139 = i139;
		this.i140 = i140;
		this.i141 = i141;
		this.i142 = i142;
		this.i143 = i143;
		this.i144 = i144;
		this.i145 = i145;
		this.i146 = i146;
		this.i147 = i147;
		this.i148 = i148;
		this.i149 = i149;
		this.i150 = i150;
		this.i151 = i151;
		this.i152 = i152;
		this.i153 = i153;
		this.i154 = i154;
		this.i155 = i155;
		this.i156 = i156;
		this.i157 = i157;
		this.i158 = i158;
		this.i159 = i159;
		this.i160 = i160;
		this.i161 = i161;
		this.i162 = i162;
		this.i163 = i163;
		this.i164 = i164;
		this.i165 = i165;
		this.i166 = i166;
		this.i167 = i167;
		this.i168 = i168;
		this.i169 = i169;
		this.i170 = i170;
		this.i171 = i171;
		this.i172 = i172;
		this.i173 = i173;
		this.i174 = i174;
		this.i175 = i175;
		this.i176 = i176;
		this.i177 = i177;
		this.i178 = i178;
		this.i179 = i179;
		this.i180 = i180;
	}

	public String getI1() {
		return this.i1;
	}

	public void setI1(String i1) {
		this.i1 = i1;
	}

	public String getI2() {
		return this.i2;
	}

	public void setI2(String i2) {
		this.i2 = i2;
	}

	public String getI3() {
		return this.i3;
	}

	public void setI3(String i3) {
		this.i3 = i3;
	}

	public String getI4() {
		return this.i4;
	}

	public void setI4(String i4) {
		this.i4 = i4;
	}

	public String getI5() {
		return this.i5;
	}

	public void setI5(String i5) {
		this.i5 = i5;
	}

	public String getI6() {
		return this.i6;
	}

	public void setI6(String i6) {
		this.i6 = i6;
	}

	public String getI7() {
		return this.i7;
	}

	public void setI7(String i7) {
		this.i7 = i7;
	}

	public String getI8() {
		return this.i8;
	}

	public void setI8(String i8) {
		this.i8 = i8;
	}

	public String getI9() {
		return this.i9;
	}

	public void setI9(String i9) {
		this.i9 = i9;
	}

	public String getI10() {
		return this.i10;
	}

	public void setI10(String i10) {
		this.i10 = i10;
	}

	public String getI11() {
		return this.i11;
	}

	public void setI11(String i11) {
		this.i11 = i11;
	}

	public String getI12() {
		return this.i12;
	}

	public void setI12(String i12) {
		this.i12 = i12;
	}

	public String getI13() {
		return this.i13;
	}

	public void setI13(String i13) {
		this.i13 = i13;
	}

	public String getI14() {
		return this.i14;
	}

	public void setI14(String i14) {
		this.i14 = i14;
	}

	public String getI15() {
		return this.i15;
	}

	public void setI15(String i15) {
		this.i15 = i15;
	}

	public String getI16() {
		return this.i16;
	}

	public void setI16(String i16) {
		this.i16 = i16;
	}

	public String getI17() {
		return this.i17;
	}

	public void setI17(String i17) {
		this.i17 = i17;
	}

	public String getI18() {
		return this.i18;
	}

	public void setI18(String i18) {
		this.i18 = i18;
	}

	public String getI19() {
		return this.i19;
	}

	public void setI19(String i19) {
		this.i19 = i19;
	}

	public String getI20() {
		return this.i20;
	}

	public void setI20(String i20) {
		this.i20 = i20;
	}

	public String getI21() {
		return this.i21;
	}

	public void setI21(String i21) {
		this.i21 = i21;
	}

	public String getI22() {
		return this.i22;
	}

	public void setI22(String i22) {
		this.i22 = i22;
	}

	public String getI23() {
		return this.i23;
	}

	public void setI23(String i23) {
		this.i23 = i23;
	}

	public String getI24() {
		return this.i24;
	}

	public void setI24(String i24) {
		this.i24 = i24;
	}

	public String getI25() {
		return this.i25;
	}

	public void setI25(String i25) {
		this.i25 = i25;
	}

	public String getI26() {
		return this.i26;
	}

	public void setI26(String i26) {
		this.i26 = i26;
	}

	public String getI27() {
		return this.i27;
	}

	public void setI27(String i27) {
		this.i27 = i27;
	}

	public String getI28() {
		return this.i28;
	}

	public void setI28(String i28) {
		this.i28 = i28;
	}

	public String getI29() {
		return this.i29;
	}

	public void setI29(String i29) {
		this.i29 = i29;
	}

	public String getI30() {
		return this.i30;
	}

	public void setI30(String i30) {
		this.i30 = i30;
	}

	public String getI31() {
		return this.i31;
	}

	public void setI31(String i31) {
		this.i31 = i31;
	}

	public String getI32() {
		return this.i32;
	}

	public void setI32(String i32) {
		this.i32 = i32;
	}

	public String getI33() {
		return this.i33;
	}

	public void setI33(String i33) {
		this.i33 = i33;
	}

	public String getI34() {
		return this.i34;
	}

	public void setI34(String i34) {
		this.i34 = i34;
	}

	public String getI35() {
		return this.i35;
	}

	public void setI35(String i35) {
		this.i35 = i35;
	}

	public String getI36() {
		return this.i36;
	}

	public void setI36(String i36) {
		this.i36 = i36;
	}

	public String getI37() {
		return this.i37;
	}

	public void setI37(String i37) {
		this.i37 = i37;
	}

	public String getI38() {
		return this.i38;
	}

	public void setI38(String i38) {
		this.i38 = i38;
	}

	public String getI39() {
		return this.i39;
	}

	public void setI39(String i39) {
		this.i39 = i39;
	}

	public String getI40() {
		return this.i40;
	}

	public void setI40(String i40) {
		this.i40 = i40;
	}

	public String getI41() {
		return this.i41;
	}

	public void setI41(String i41) {
		this.i41 = i41;
	}

	public String getI42() {
		return this.i42;
	}

	public void setI42(String i42) {
		this.i42 = i42;
	}

	public String getI43() {
		return this.i43;
	}

	public void setI43(String i43) {
		this.i43 = i43;
	}

	public String getI44() {
		return this.i44;
	}

	public void setI44(String i44) {
		this.i44 = i44;
	}

	public String getI45() {
		return this.i45;
	}

	public void setI45(String i45) {
		this.i45 = i45;
	}

	public String getI46() {
		return this.i46;
	}

	public void setI46(String i46) {
		this.i46 = i46;
	}

	public String getI47() {
		return this.i47;
	}

	public void setI47(String i47) {
		this.i47 = i47;
	}

	public String getI48() {
		return this.i48;
	}

	public void setI48(String i48) {
		this.i48 = i48;
	}

	public String getI49() {
		return this.i49;
	}

	public void setI49(String i49) {
		this.i49 = i49;
	}

	public String getI50() {
		return this.i50;
	}

	public void setI50(String i50) {
		this.i50 = i50;
	}

	public String getI51() {
		return this.i51;
	}

	public void setI51(String i51) {
		this.i51 = i51;
	}

	public String getI52() {
		return this.i52;
	}

	public void setI52(String i52) {
		this.i52 = i52;
	}

	public String getI53() {
		return this.i53;
	}

	public void setI53(String i53) {
		this.i53 = i53;
	}

	public String getI54() {
		return this.i54;
	}

	public void setI54(String i54) {
		this.i54 = i54;
	}

	public String getI55() {
		return this.i55;
	}

	public void setI55(String i55) {
		this.i55 = i55;
	}

	public String getI56() {
		return this.i56;
	}

	public void setI56(String i56) {
		this.i56 = i56;
	}

	public String getI57() {
		return this.i57;
	}

	public void setI57(String i57) {
		this.i57 = i57;
	}

	public String getI58() {
		return this.i58;
	}

	public void setI58(String i58) {
		this.i58 = i58;
	}

	public String getI59() {
		return this.i59;
	}

	public void setI59(String i59) {
		this.i59 = i59;
	}

	public String getI60() {
		return this.i60;
	}

	public void setI60(String i60) {
		this.i60 = i60;
	}

	public String getI61() {
		return this.i61;
	}

	public void setI61(String i61) {
		this.i61 = i61;
	}

	public String getI62() {
		return this.i62;
	}

	public void setI62(String i62) {
		this.i62 = i62;
	}

	public String getI63() {
		return this.i63;
	}

	public void setI63(String i63) {
		this.i63 = i63;
	}

	public String getI64() {
		return this.i64;
	}

	public void setI64(String i64) {
		this.i64 = i64;
	}

	public String getI65() {
		return this.i65;
	}

	public void setI65(String i65) {
		this.i65 = i65;
	}

	public String getI66() {
		return this.i66;
	}

	public void setI66(String i66) {
		this.i66 = i66;
	}

	public String getI67() {
		return this.i67;
	}

	public void setI67(String i67) {
		this.i67 = i67;
	}

	public String getI68() {
		return this.i68;
	}

	public void setI68(String i68) {
		this.i68 = i68;
	}

	public String getI69() {
		return this.i69;
	}

	public void setI69(String i69) {
		this.i69 = i69;
	}

	public String getI70() {
		return this.i70;
	}

	public void setI70(String i70) {
		this.i70 = i70;
	}

	public String getI71() {
		return this.i71;
	}

	public void setI71(String i71) {
		this.i71 = i71;
	}

	public String getI72() {
		return this.i72;
	}

	public void setI72(String i72) {
		this.i72 = i72;
	}

	public String getI73() {
		return this.i73;
	}

	public void setI73(String i73) {
		this.i73 = i73;
	}

	public String getI74() {
		return this.i74;
	}

	public void setI74(String i74) {
		this.i74 = i74;
	}

	public String getI75() {
		return this.i75;
	}

	public void setI75(String i75) {
		this.i75 = i75;
	}

	public String getI76() {
		return this.i76;
	}

	public void setI76(String i76) {
		this.i76 = i76;
	}

	public String getI77() {
		return this.i77;
	}

	public void setI77(String i77) {
		this.i77 = i77;
	}

	public String getI78() {
		return this.i78;
	}

	public void setI78(String i78) {
		this.i78 = i78;
	}

	public String getI79() {
		return this.i79;
	}

	public void setI79(String i79) {
		this.i79 = i79;
	}

	public String getI80() {
		return this.i80;
	}

	public void setI80(String i80) {
		this.i80 = i80;
	}

	public String getI81() {
		return this.i81;
	}

	public void setI81(String i81) {
		this.i81 = i81;
	}

	public String getI82() {
		return this.i82;
	}

	public void setI82(String i82) {
		this.i82 = i82;
	}

	public String getI83() {
		return this.i83;
	}

	public void setI83(String i83) {
		this.i83 = i83;
	}

	public String getI84() {
		return this.i84;
	}

	public void setI84(String i84) {
		this.i84 = i84;
	}

	public String getI85() {
		return this.i85;
	}

	public void setI85(String i85) {
		this.i85 = i85;
	}

	public String getI86() {
		return this.i86;
	}

	public void setI86(String i86) {
		this.i86 = i86;
	}

	public String getI87() {
		return this.i87;
	}

	public void setI87(String i87) {
		this.i87 = i87;
	}

	public String getI88() {
		return this.i88;
	}

	public void setI88(String i88) {
		this.i88 = i88;
	}

	public String getI89() {
		return this.i89;
	}

	public void setI89(String i89) {
		this.i89 = i89;
	}

	public String getI90() {
		return this.i90;
	}

	public void setI90(String i90) {
		this.i90 = i90;
	}

	public String getI91() {
		return this.i91;
	}

	public void setI91(String i91) {
		this.i91 = i91;
	}

	public String getI92() {
		return this.i92;
	}

	public void setI92(String i92) {
		this.i92 = i92;
	}

	public String getI93() {
		return this.i93;
	}

	public void setI93(String i93) {
		this.i93 = i93;
	}

	public String getI94() {
		return this.i94;
	}

	public void setI94(String i94) {
		this.i94 = i94;
	}

	public String getI95() {
		return this.i95;
	}

	public void setI95(String i95) {
		this.i95 = i95;
	}

	public String getI96() {
		return this.i96;
	}

	public void setI96(String i96) {
		this.i96 = i96;
	}

	public String getI97() {
		return this.i97;
	}

	public void setI97(String i97) {
		this.i97 = i97;
	}

	public String getI98() {
		return this.i98;
	}

	public void setI98(String i98) {
		this.i98 = i98;
	}

	public String getI99() {
		return this.i99;
	}

	public void setI99(String i99) {
		this.i99 = i99;
	}

	public String getI100() {
		return this.i100;
	}

	public void setI100(String i100) {
		this.i100 = i100;
	}

	public String getI101() {
		return this.i101;
	}

	public void setI101(String i101) {
		this.i101 = i101;
	}

	public String getI102() {
		return this.i102;
	}

	public void setI102(String i102) {
		this.i102 = i102;
	}

	public String getI103() {
		return this.i103;
	}

	public void setI103(String i103) {
		this.i103 = i103;
	}

	public String getI104() {
		return this.i104;
	}

	public void setI104(String i104) {
		this.i104 = i104;
	}

	public String getI105() {
		return this.i105;
	}

	public void setI105(String i105) {
		this.i105 = i105;
	}

	public String getI106() {
		return this.i106;
	}

	public void setI106(String i106) {
		this.i106 = i106;
	}

	public String getI107() {
		return this.i107;
	}

	public void setI107(String i107) {
		this.i107 = i107;
	}

	public String getI108() {
		return this.i108;
	}

	public void setI108(String i108) {
		this.i108 = i108;
	}

	public String getI109() {
		return this.i109;
	}

	public void setI109(String i109) {
		this.i109 = i109;
	}

	public String getI110() {
		return this.i110;
	}

	public void setI110(String i110) {
		this.i110 = i110;
	}

	public String getI111() {
		return this.i111;
	}

	public void setI111(String i111) {
		this.i111 = i111;
	}

	public String getI112() {
		return this.i112;
	}

	public void setI112(String i112) {
		this.i112 = i112;
	}

	public String getI113() {
		return this.i113;
	}

	public void setI113(String i113) {
		this.i113 = i113;
	}

	public String getI114() {
		return this.i114;
	}

	public void setI114(String i114) {
		this.i114 = i114;
	}

	public String getI115() {
		return this.i115;
	}

	public void setI115(String i115) {
		this.i115 = i115;
	}

	public String getI116() {
		return this.i116;
	}

	public void setI116(String i116) {
		this.i116 = i116;
	}

	public String getI117() {
		return this.i117;
	}

	public void setI117(String i117) {
		this.i117 = i117;
	}

	public String getI118() {
		return this.i118;
	}

	public void setI118(String i118) {
		this.i118 = i118;
	}

	public String getI119() {
		return this.i119;
	}

	public void setI119(String i119) {
		this.i119 = i119;
	}

	public String getI120() {
		return this.i120;
	}

	public void setI120(String i120) {
		this.i120 = i120;
	}

	public String getI121() {
		return this.i121;
	}

	public void setI121(String i121) {
		this.i121 = i121;
	}

	public String getI122() {
		return this.i122;
	}

	public void setI122(String i122) {
		this.i122 = i122;
	}

	public String getI123() {
		return this.i123;
	}

	public void setI123(String i123) {
		this.i123 = i123;
	}

	public String getI124() {
		return this.i124;
	}

	public void setI124(String i124) {
		this.i124 = i124;
	}

	public String getI125() {
		return this.i125;
	}

	public void setI125(String i125) {
		this.i125 = i125;
	}

	public String getI126() {
		return this.i126;
	}

	public void setI126(String i126) {
		this.i126 = i126;
	}

	public String getI127() {
		return this.i127;
	}

	public void setI127(String i127) {
		this.i127 = i127;
	}

	public String getI128() {
		return this.i128;
	}

	public void setI128(String i128) {
		this.i128 = i128;
	}

	public String getI129() {
		return this.i129;
	}

	public void setI129(String i129) {
		this.i129 = i129;
	}

	public String getI130() {
		return this.i130;
	}

	public void setI130(String i130) {
		this.i130 = i130;
	}

	public String getI131() {
		return this.i131;
	}

	public void setI131(String i131) {
		this.i131 = i131;
	}

	public String getI132() {
		return this.i132;
	}

	public void setI132(String i132) {
		this.i132 = i132;
	}

	public String getI133() {
		return this.i133;
	}

	public void setI133(String i133) {
		this.i133 = i133;
	}

	public String getI134() {
		return this.i134;
	}

	public void setI134(String i134) {
		this.i134 = i134;
	}

	public String getI135() {
		return this.i135;
	}

	public void setI135(String i135) {
		this.i135 = i135;
	}

	public String getI136() {
		return this.i136;
	}

	public void setI136(String i136) {
		this.i136 = i136;
	}

	public String getI137() {
		return this.i137;
	}

	public void setI137(String i137) {
		this.i137 = i137;
	}

	public String getI138() {
		return this.i138;
	}

	public void setI138(String i138) {
		this.i138 = i138;
	}

	public String getI139() {
		return this.i139;
	}

	public void setI139(String i139) {
		this.i139 = i139;
	}

	public String getI140() {
		return this.i140;
	}

	public void setI140(String i140) {
		this.i140 = i140;
	}

	public String getI141() {
		return this.i141;
	}

	public void setI141(String i141) {
		this.i141 = i141;
	}

	public String getI142() {
		return this.i142;
	}

	public void setI142(String i142) {
		this.i142 = i142;
	}

	public String getI143() {
		return this.i143;
	}

	public void setI143(String i143) {
		this.i143 = i143;
	}

	public String getI144() {
		return this.i144;
	}

	public void setI144(String i144) {
		this.i144 = i144;
	}

	public String getI145() {
		return this.i145;
	}

	public void setI145(String i145) {
		this.i145 = i145;
	}

	public String getI146() {
		return this.i146;
	}

	public void setI146(String i146) {
		this.i146 = i146;
	}

	public String getI147() {
		return this.i147;
	}

	public void setI147(String i147) {
		this.i147 = i147;
	}

	public String getI148() {
		return this.i148;
	}

	public void setI148(String i148) {
		this.i148 = i148;
	}

	public String getI149() {
		return this.i149;
	}

	public void setI149(String i149) {
		this.i149 = i149;
	}

	public String getI150() {
		return this.i150;
	}

	public void setI150(String i150) {
		this.i150 = i150;
	}

	public String getI151() {
		return this.i151;
	}

	public void setI151(String i151) {
		this.i151 = i151;
	}

	public String getI152() {
		return this.i152;
	}

	public void setI152(String i152) {
		this.i152 = i152;
	}

	public String getI153() {
		return this.i153;
	}

	public void setI153(String i153) {
		this.i153 = i153;
	}

	public String getI154() {
		return this.i154;
	}

	public void setI154(String i154) {
		this.i154 = i154;
	}

	public String getI155() {
		return this.i155;
	}

	public void setI155(String i155) {
		this.i155 = i155;
	}

	public String getI156() {
		return this.i156;
	}

	public void setI156(String i156) {
		this.i156 = i156;
	}

	public String getI157() {
		return this.i157;
	}

	public void setI157(String i157) {
		this.i157 = i157;
	}

	public String getI158() {
		return this.i158;
	}

	public void setI158(String i158) {
		this.i158 = i158;
	}

	public String getI159() {
		return this.i159;
	}

	public void setI159(String i159) {
		this.i159 = i159;
	}

	public String getI160() {
		return this.i160;
	}

	public void setI160(String i160) {
		this.i160 = i160;
	}

	public String getI161() {
		return this.i161;
	}

	public void setI161(String i161) {
		this.i161 = i161;
	}

	public String getI162() {
		return this.i162;
	}

	public void setI162(String i162) {
		this.i162 = i162;
	}

	public String getI163() {
		return this.i163;
	}

	public void setI163(String i163) {
		this.i163 = i163;
	}

	public String getI164() {
		return this.i164;
	}

	public void setI164(String i164) {
		this.i164 = i164;
	}

	public String getI165() {
		return this.i165;
	}

	public void setI165(String i165) {
		this.i165 = i165;
	}

	public String getI166() {
		return this.i166;
	}

	public void setI166(String i166) {
		this.i166 = i166;
	}

	public String getI167() {
		return this.i167;
	}

	public void setI167(String i167) {
		this.i167 = i167;
	}

	public String getI168() {
		return this.i168;
	}

	public void setI168(String i168) {
		this.i168 = i168;
	}

	public String getI169() {
		return this.i169;
	}

	public void setI169(String i169) {
		this.i169 = i169;
	}

	public String getI170() {
		return this.i170;
	}

	public void setI170(String i170) {
		this.i170 = i170;
	}

	public String getI171() {
		return this.i171;
	}

	public void setI171(String i171) {
		this.i171 = i171;
	}

	public String getI172() {
		return this.i172;
	}

	public void setI172(String i172) {
		this.i172 = i172;
	}

	public String getI173() {
		return this.i173;
	}

	public void setI173(String i173) {
		this.i173 = i173;
	}

	public String getI174() {
		return this.i174;
	}

	public void setI174(String i174) {
		this.i174 = i174;
	}

	public String getI175() {
		return this.i175;
	}

	public void setI175(String i175) {
		this.i175 = i175;
	}

	public String getI176() {
		return this.i176;
	}

	public void setI176(String i176) {
		this.i176 = i176;
	}

	public String getI177() {
		return this.i177;
	}

	public void setI177(String i177) {
		this.i177 = i177;
	}

	public String getI178() {
		return this.i178;
	}

	public void setI178(String i178) {
		this.i178 = i178;
	}

	public String getI179() {
		return this.i179;
	}

	public void setI179(String i179) {
		this.i179 = i179;
	}

	public String getI180() {
		return this.i180;
	}

	public void setI180(String i180) {
		this.i180 = i180;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Beefs1Id))
			return false;
		Beefs1Id castOther = (Beefs1Id) other;

		return ((this.getI1() == castOther.getI1())
				|| (this.getI1() != null && castOther.getI1() != null && this.getI1().equals(castOther.getI1())))
				&& ((this.getI2() == castOther.getI2()) || (this.getI2() != null && castOther.getI2() != null
						&& this.getI2().equals(castOther.getI2())))
				&& ((this.getI3() == castOther.getI3()) || (this.getI3() != null && castOther.getI3() != null
						&& this.getI3().equals(castOther.getI3())))
				&& ((this.getI4() == castOther.getI4()) || (this.getI4() != null && castOther.getI4() != null
						&& this.getI4().equals(castOther.getI4())))
				&& ((this.getI5() == castOther.getI5()) || (this.getI5() != null && castOther.getI5() != null
						&& this.getI5().equals(castOther.getI5())))
				&& ((this.getI6() == castOther.getI6()) || (this.getI6() != null && castOther.getI6() != null
						&& this.getI6().equals(castOther.getI6())))
				&& ((this.getI7() == castOther.getI7()) || (this.getI7() != null && castOther.getI7() != null
						&& this.getI7().equals(castOther.getI7())))
				&& ((this.getI8() == castOther.getI8()) || (this.getI8() != null && castOther.getI8() != null
						&& this.getI8().equals(castOther.getI8())))
				&& ((this.getI9() == castOther.getI9()) || (this.getI9() != null && castOther.getI9() != null
						&& this.getI9().equals(castOther.getI9())))
				&& ((this.getI10() == castOther.getI10()) || (this.getI10() != null && castOther.getI10() != null
						&& this.getI10().equals(castOther.getI10())))
				&& ((this.getI11() == castOther.getI11()) || (this.getI11() != null && castOther.getI11() != null
						&& this.getI11().equals(castOther.getI11())))
				&& ((this.getI12() == castOther.getI12()) || (this.getI12() != null && castOther.getI12() != null
						&& this.getI12().equals(castOther.getI12())))
				&& ((this.getI13() == castOther.getI13()) || (this.getI13() != null && castOther.getI13() != null
						&& this.getI13().equals(castOther.getI13())))
				&& ((this.getI14() == castOther.getI14()) || (this.getI14() != null && castOther.getI14() != null
						&& this.getI14().equals(castOther.getI14())))
				&& ((this.getI15() == castOther.getI15()) || (this.getI15() != null && castOther.getI15() != null
						&& this.getI15().equals(castOther.getI15())))
				&& ((this.getI16() == castOther.getI16()) || (this.getI16() != null && castOther.getI16() != null
						&& this.getI16().equals(castOther.getI16())))
				&& ((this.getI17() == castOther.getI17()) || (this.getI17() != null && castOther.getI17() != null
						&& this.getI17().equals(castOther.getI17())))
				&& ((this.getI18() == castOther.getI18()) || (this.getI18() != null && castOther.getI18() != null
						&& this.getI18().equals(castOther.getI18())))
				&& ((this.getI19() == castOther.getI19()) || (this.getI19() != null && castOther.getI19() != null
						&& this.getI19().equals(castOther.getI19())))
				&& ((this.getI20() == castOther.getI20()) || (this.getI20() != null && castOther.getI20() != null
						&& this.getI20().equals(castOther.getI20())))
				&& ((this.getI21() == castOther.getI21()) || (this.getI21() != null && castOther.getI21() != null
						&& this.getI21().equals(castOther.getI21())))
				&& ((this.getI22() == castOther.getI22()) || (this.getI22() != null && castOther.getI22() != null
						&& this.getI22().equals(castOther.getI22())))
				&& ((this.getI23() == castOther.getI23()) || (this.getI23() != null && castOther.getI23() != null
						&& this.getI23().equals(castOther.getI23())))
				&& ((this.getI24() == castOther.getI24()) || (this.getI24() != null && castOther.getI24() != null
						&& this.getI24().equals(castOther.getI24())))
				&& ((this.getI25() == castOther.getI25()) || (this.getI25() != null && castOther.getI25() != null
						&& this.getI25().equals(castOther.getI25())))
				&& ((this.getI26() == castOther.getI26()) || (this.getI26() != null && castOther.getI26() != null
						&& this.getI26().equals(castOther.getI26())))
				&& ((this.getI27() == castOther.getI27()) || (this.getI27() != null && castOther.getI27() != null
						&& this.getI27().equals(castOther.getI27())))
				&& ((this.getI28() == castOther.getI28()) || (this.getI28() != null && castOther.getI28() != null
						&& this.getI28().equals(castOther.getI28())))
				&& ((this.getI29() == castOther.getI29()) || (this.getI29() != null && castOther.getI29() != null
						&& this.getI29().equals(castOther.getI29())))
				&& ((this.getI30() == castOther.getI30()) || (this.getI30() != null && castOther.getI30() != null
						&& this.getI30().equals(castOther.getI30())))
				&& ((this.getI31() == castOther.getI31()) || (this.getI31() != null && castOther.getI31() != null
						&& this.getI31().equals(castOther.getI31())))
				&& ((this.getI32() == castOther.getI32()) || (this.getI32() != null && castOther.getI32() != null
						&& this.getI32().equals(castOther.getI32())))
				&& ((this.getI33() == castOther.getI33()) || (this.getI33() != null && castOther.getI33() != null
						&& this.getI33().equals(castOther.getI33())))
				&& ((this.getI34() == castOther.getI34()) || (this.getI34() != null && castOther.getI34() != null
						&& this.getI34().equals(castOther.getI34())))
				&& ((this.getI35() == castOther.getI35()) || (this.getI35() != null && castOther.getI35() != null
						&& this.getI35().equals(castOther.getI35())))
				&& ((this.getI36() == castOther.getI36()) || (this.getI36() != null && castOther.getI36() != null
						&& this.getI36().equals(castOther.getI36())))
				&& ((this.getI37() == castOther.getI37()) || (this.getI37() != null && castOther.getI37() != null
						&& this.getI37().equals(castOther.getI37())))
				&& ((this.getI38() == castOther.getI38()) || (this.getI38() != null && castOther.getI38() != null
						&& this.getI38().equals(castOther.getI38())))
				&& ((this.getI39() == castOther.getI39()) || (this.getI39() != null && castOther.getI39() != null
						&& this.getI39().equals(castOther.getI39())))
				&& ((this.getI40() == castOther.getI40()) || (this.getI40() != null && castOther.getI40() != null
						&& this.getI40().equals(castOther.getI40())))
				&& ((this.getI41() == castOther.getI41()) || (this.getI41() != null && castOther.getI41() != null
						&& this.getI41().equals(castOther.getI41())))
				&& ((this.getI42() == castOther.getI42()) || (this.getI42() != null && castOther.getI42() != null
						&& this.getI42().equals(castOther.getI42())))
				&& ((this.getI43() == castOther.getI43()) || (this.getI43() != null && castOther.getI43() != null
						&& this.getI43().equals(castOther.getI43())))
				&& ((this.getI44() == castOther.getI44()) || (this.getI44() != null && castOther.getI44() != null
						&& this.getI44().equals(castOther.getI44())))
				&& ((this.getI45() == castOther.getI45()) || (this.getI45() != null && castOther.getI45() != null
						&& this.getI45().equals(castOther.getI45())))
				&& ((this.getI46() == castOther.getI46()) || (this.getI46() != null && castOther.getI46() != null
						&& this.getI46().equals(castOther.getI46())))
				&& ((this.getI47() == castOther.getI47()) || (this.getI47() != null && castOther.getI47() != null
						&& this.getI47().equals(castOther.getI47())))
				&& ((this.getI48() == castOther.getI48()) || (this.getI48() != null && castOther.getI48() != null
						&& this.getI48().equals(castOther.getI48())))
				&& ((this.getI49() == castOther.getI49()) || (this.getI49() != null && castOther.getI49() != null
						&& this.getI49().equals(castOther.getI49())))
				&& ((this.getI50() == castOther.getI50()) || (this.getI50() != null && castOther.getI50() != null
						&& this.getI50().equals(castOther.getI50())))
				&& ((this.getI51() == castOther.getI51()) || (this.getI51() != null && castOther.getI51() != null
						&& this.getI51().equals(castOther.getI51())))
				&& ((this.getI52() == castOther.getI52()) || (this.getI52() != null && castOther.getI52() != null
						&& this.getI52().equals(castOther.getI52())))
				&& ((this.getI53() == castOther.getI53()) || (this.getI53() != null && castOther.getI53() != null
						&& this.getI53().equals(castOther.getI53())))
				&& ((this.getI54() == castOther.getI54()) || (this.getI54() != null && castOther.getI54() != null
						&& this.getI54().equals(castOther.getI54())))
				&& ((this.getI55() == castOther.getI55()) || (this.getI55() != null && castOther.getI55() != null
						&& this.getI55().equals(castOther.getI55())))
				&& ((this.getI56() == castOther.getI56()) || (this.getI56() != null && castOther.getI56() != null
						&& this.getI56().equals(castOther.getI56())))
				&& ((this.getI57() == castOther.getI57()) || (this.getI57() != null && castOther.getI57() != null
						&& this.getI57().equals(castOther.getI57())))
				&& ((this.getI58() == castOther.getI58()) || (this.getI58() != null && castOther.getI58() != null
						&& this.getI58().equals(castOther.getI58())))
				&& ((this.getI59() == castOther.getI59()) || (this.getI59() != null && castOther.getI59() != null
						&& this.getI59().equals(castOther.getI59())))
				&& ((this.getI60() == castOther.getI60()) || (this.getI60() != null && castOther.getI60() != null
						&& this.getI60().equals(castOther.getI60())))
				&& ((this.getI61() == castOther.getI61()) || (this.getI61() != null && castOther.getI61() != null
						&& this.getI61().equals(castOther.getI61())))
				&& ((this.getI62() == castOther.getI62()) || (this.getI62() != null && castOther.getI62() != null
						&& this.getI62().equals(castOther.getI62())))
				&& ((this.getI63() == castOther.getI63()) || (this.getI63() != null && castOther.getI63() != null
						&& this.getI63().equals(castOther.getI63())))
				&& ((this.getI64() == castOther.getI64()) || (this.getI64() != null && castOther.getI64() != null
						&& this.getI64().equals(castOther.getI64())))
				&& ((this.getI65() == castOther.getI65()) || (this.getI65() != null && castOther.getI65() != null
						&& this.getI65().equals(castOther.getI65())))
				&& ((this.getI66() == castOther.getI66()) || (this.getI66() != null && castOther.getI66() != null
						&& this.getI66().equals(castOther.getI66())))
				&& ((this.getI67() == castOther.getI67()) || (this.getI67() != null && castOther.getI67() != null
						&& this.getI67().equals(castOther.getI67())))
				&& ((this.getI68() == castOther.getI68()) || (this.getI68() != null && castOther.getI68() != null
						&& this.getI68().equals(castOther.getI68())))
				&& ((this.getI69() == castOther.getI69()) || (this.getI69() != null && castOther.getI69() != null
						&& this.getI69().equals(castOther.getI69())))
				&& ((this.getI70() == castOther.getI70()) || (this.getI70() != null && castOther.getI70() != null
						&& this.getI70().equals(castOther.getI70())))
				&& ((this.getI71() == castOther.getI71()) || (this.getI71() != null && castOther.getI71() != null
						&& this.getI71().equals(castOther.getI71())))
				&& ((this.getI72() == castOther.getI72()) || (this.getI72() != null && castOther.getI72() != null
						&& this.getI72().equals(castOther.getI72())))
				&& ((this.getI73() == castOther.getI73()) || (this.getI73() != null && castOther.getI73() != null
						&& this.getI73().equals(castOther.getI73())))
				&& ((this.getI74() == castOther.getI74()) || (this.getI74() != null && castOther.getI74() != null
						&& this.getI74().equals(castOther.getI74())))
				&& ((this.getI75() == castOther.getI75()) || (this.getI75() != null && castOther.getI75() != null
						&& this.getI75().equals(castOther.getI75())))
				&& ((this.getI76() == castOther.getI76()) || (this.getI76() != null && castOther.getI76() != null
						&& this.getI76().equals(castOther.getI76())))
				&& ((this.getI77() == castOther.getI77()) || (this.getI77() != null && castOther.getI77() != null
						&& this.getI77().equals(castOther.getI77())))
				&& ((this.getI78() == castOther.getI78()) || (this.getI78() != null && castOther.getI78() != null
						&& this.getI78().equals(castOther.getI78())))
				&& ((this.getI79() == castOther.getI79()) || (this.getI79() != null && castOther.getI79() != null
						&& this.getI79().equals(castOther.getI79())))
				&& ((this.getI80() == castOther.getI80()) || (this.getI80() != null && castOther.getI80() != null
						&& this.getI80().equals(castOther.getI80())))
				&& ((this.getI81() == castOther.getI81()) || (this.getI81() != null && castOther.getI81() != null
						&& this.getI81().equals(castOther.getI81())))
				&& ((this.getI82() == castOther.getI82()) || (this.getI82() != null && castOther.getI82() != null
						&& this.getI82().equals(castOther.getI82())))
				&& ((this.getI83() == castOther.getI83()) || (this.getI83() != null && castOther.getI83() != null
						&& this.getI83().equals(castOther.getI83())))
				&& ((this.getI84() == castOther.getI84()) || (this.getI84() != null && castOther.getI84() != null
						&& this.getI84().equals(castOther.getI84())))
				&& ((this.getI85() == castOther.getI85()) || (this.getI85() != null && castOther.getI85() != null
						&& this.getI85().equals(castOther.getI85())))
				&& ((this.getI86() == castOther.getI86()) || (this.getI86() != null && castOther.getI86() != null
						&& this.getI86().equals(castOther.getI86())))
				&& ((this.getI87() == castOther.getI87()) || (this.getI87() != null && castOther.getI87() != null
						&& this.getI87().equals(castOther.getI87())))
				&& ((this.getI88() == castOther.getI88()) || (this.getI88() != null && castOther.getI88() != null
						&& this.getI88().equals(castOther.getI88())))
				&& ((this.getI89() == castOther.getI89()) || (this.getI89() != null && castOther.getI89() != null
						&& this.getI89().equals(castOther.getI89())))
				&& ((this.getI90() == castOther.getI90()) || (this.getI90() != null && castOther.getI90() != null
						&& this.getI90().equals(castOther.getI90())))
				&& ((this.getI91() == castOther.getI91()) || (this.getI91() != null && castOther.getI91() != null
						&& this.getI91().equals(castOther.getI91())))
				&& ((this.getI92() == castOther.getI92()) || (this.getI92() != null && castOther.getI92() != null
						&& this.getI92().equals(castOther.getI92())))
				&& ((this.getI93() == castOther.getI93()) || (this.getI93() != null && castOther.getI93() != null
						&& this.getI93().equals(castOther.getI93())))
				&& ((this.getI94() == castOther.getI94()) || (this.getI94() != null && castOther.getI94() != null
						&& this.getI94().equals(castOther.getI94())))
				&& ((this.getI95() == castOther.getI95()) || (this.getI95() != null && castOther.getI95() != null
						&& this.getI95().equals(castOther.getI95())))
				&& ((this.getI96() == castOther.getI96()) || (this.getI96() != null && castOther.getI96() != null
						&& this.getI96().equals(castOther.getI96())))
				&& ((this.getI97() == castOther.getI97()) || (this.getI97() != null && castOther.getI97() != null
						&& this.getI97().equals(castOther.getI97())))
				&& ((this.getI98() == castOther.getI98()) || (this.getI98() != null && castOther.getI98() != null
						&& this.getI98().equals(castOther.getI98())))
				&& ((this.getI99() == castOther.getI99()) || (this.getI99() != null && castOther.getI99() != null
						&& this.getI99().equals(castOther.getI99())))
				&& ((this.getI100() == castOther.getI100()) || (this.getI100() != null && castOther.getI100() != null
						&& this.getI100().equals(castOther.getI100())))
				&& ((this.getI101() == castOther.getI101()) || (this.getI101() != null && castOther.getI101() != null
						&& this.getI101().equals(castOther.getI101())))
				&& ((this.getI102() == castOther.getI102()) || (this.getI102() != null && castOther.getI102() != null
						&& this.getI102().equals(castOther.getI102())))
				&& ((this.getI103() == castOther.getI103()) || (this.getI103() != null && castOther.getI103() != null
						&& this.getI103().equals(castOther.getI103())))
				&& ((this.getI104() == castOther.getI104()) || (this.getI104() != null && castOther.getI104() != null
						&& this.getI104().equals(castOther.getI104())))
				&& ((this.getI105() == castOther.getI105()) || (this.getI105() != null && castOther.getI105() != null
						&& this.getI105().equals(castOther.getI105())))
				&& ((this.getI106() == castOther.getI106()) || (this.getI106() != null && castOther.getI106() != null
						&& this.getI106().equals(castOther.getI106())))
				&& ((this.getI107() == castOther.getI107()) || (this.getI107() != null && castOther.getI107() != null
						&& this.getI107().equals(castOther.getI107())))
				&& ((this.getI108() == castOther.getI108()) || (this.getI108() != null && castOther.getI108() != null
						&& this.getI108().equals(castOther.getI108())))
				&& ((this.getI109() == castOther.getI109()) || (this.getI109() != null && castOther.getI109() != null
						&& this.getI109().equals(castOther.getI109())))
				&& ((this.getI110() == castOther.getI110()) || (this.getI110() != null && castOther.getI110() != null
						&& this.getI110().equals(castOther.getI110())))
				&& ((this.getI111() == castOther.getI111()) || (this.getI111() != null && castOther.getI111() != null
						&& this.getI111().equals(castOther.getI111())))
				&& ((this.getI112() == castOther.getI112()) || (this.getI112() != null && castOther.getI112() != null
						&& this.getI112().equals(castOther.getI112())))
				&& ((this.getI113() == castOther.getI113()) || (this.getI113() != null && castOther.getI113() != null
						&& this.getI113().equals(castOther.getI113())))
				&& ((this.getI114() == castOther.getI114()) || (this.getI114() != null && castOther.getI114() != null
						&& this.getI114().equals(castOther.getI114())))
				&& ((this.getI115() == castOther.getI115()) || (this.getI115() != null && castOther.getI115() != null
						&& this.getI115().equals(castOther.getI115())))
				&& ((this.getI116() == castOther.getI116()) || (this.getI116() != null && castOther.getI116() != null
						&& this.getI116().equals(castOther.getI116())))
				&& ((this.getI117() == castOther.getI117()) || (this.getI117() != null && castOther.getI117() != null
						&& this.getI117().equals(castOther.getI117())))
				&& ((this.getI118() == castOther.getI118()) || (this.getI118() != null && castOther.getI118() != null
						&& this.getI118().equals(castOther.getI118())))
				&& ((this.getI119() == castOther.getI119()) || (this.getI119() != null && castOther.getI119() != null
						&& this.getI119().equals(castOther.getI119())))
				&& ((this.getI120() == castOther.getI120()) || (this.getI120() != null && castOther.getI120() != null
						&& this.getI120().equals(castOther.getI120())))
				&& ((this.getI121() == castOther.getI121()) || (this.getI121() != null && castOther.getI121() != null
						&& this.getI121().equals(castOther.getI121())))
				&& ((this.getI122() == castOther.getI122()) || (this.getI122() != null && castOther.getI122() != null
						&& this.getI122().equals(castOther.getI122())))
				&& ((this.getI123() == castOther.getI123()) || (this.getI123() != null && castOther.getI123() != null
						&& this.getI123().equals(castOther.getI123())))
				&& ((this.getI124() == castOther.getI124()) || (this.getI124() != null && castOther.getI124() != null
						&& this.getI124().equals(castOther.getI124())))
				&& ((this.getI125() == castOther.getI125()) || (this.getI125() != null && castOther.getI125() != null
						&& this.getI125().equals(castOther.getI125())))
				&& ((this.getI126() == castOther.getI126()) || (this.getI126() != null && castOther.getI126() != null
						&& this.getI126().equals(castOther.getI126())))
				&& ((this.getI127() == castOther.getI127()) || (this.getI127() != null && castOther.getI127() != null
						&& this.getI127().equals(castOther.getI127())))
				&& ((this.getI128() == castOther.getI128()) || (this.getI128() != null && castOther.getI128() != null
						&& this.getI128().equals(castOther.getI128())))
				&& ((this.getI129() == castOther.getI129()) || (this.getI129() != null && castOther.getI129() != null
						&& this.getI129().equals(castOther.getI129())))
				&& ((this.getI130() == castOther.getI130()) || (this.getI130() != null && castOther.getI130() != null
						&& this.getI130().equals(castOther.getI130())))
				&& ((this.getI131() == castOther.getI131()) || (this.getI131() != null && castOther.getI131() != null
						&& this.getI131().equals(castOther.getI131())))
				&& ((this.getI132() == castOther.getI132()) || (this.getI132() != null && castOther.getI132() != null
						&& this.getI132().equals(castOther.getI132())))
				&& ((this.getI133() == castOther.getI133()) || (this.getI133() != null && castOther.getI133() != null
						&& this.getI133().equals(castOther.getI133())))
				&& ((this.getI134() == castOther.getI134()) || (this.getI134() != null && castOther.getI134() != null
						&& this.getI134().equals(castOther.getI134())))
				&& ((this.getI135() == castOther.getI135()) || (this.getI135() != null && castOther.getI135() != null
						&& this.getI135().equals(castOther.getI135())))
				&& ((this.getI136() == castOther.getI136()) || (this.getI136() != null && castOther.getI136() != null
						&& this.getI136().equals(castOther.getI136())))
				&& ((this.getI137() == castOther.getI137()) || (this.getI137() != null && castOther.getI137() != null
						&& this.getI137().equals(castOther.getI137())))
				&& ((this.getI138() == castOther.getI138()) || (this.getI138() != null && castOther.getI138() != null
						&& this.getI138().equals(castOther.getI138())))
				&& ((this.getI139() == castOther.getI139()) || (this.getI139() != null && castOther.getI139() != null
						&& this.getI139().equals(castOther.getI139())))
				&& ((this.getI140() == castOther.getI140()) || (this.getI140() != null && castOther.getI140() != null
						&& this.getI140().equals(castOther.getI140())))
				&& ((this.getI141() == castOther.getI141()) || (this.getI141() != null && castOther.getI141() != null
						&& this.getI141().equals(castOther.getI141())))
				&& ((this.getI142() == castOther.getI142()) || (this.getI142() != null && castOther.getI142() != null
						&& this.getI142().equals(castOther.getI142())))
				&& ((this.getI143() == castOther.getI143()) || (this.getI143() != null && castOther.getI143() != null
						&& this.getI143().equals(castOther.getI143())))
				&& ((this.getI144() == castOther.getI144()) || (this.getI144() != null && castOther.getI144() != null
						&& this.getI144().equals(castOther.getI144())))
				&& ((this.getI145() == castOther.getI145()) || (this.getI145() != null && castOther.getI145() != null
						&& this.getI145().equals(castOther.getI145())))
				&& ((this.getI146() == castOther.getI146()) || (this.getI146() != null && castOther.getI146() != null
						&& this.getI146().equals(castOther.getI146())))
				&& ((this.getI147() == castOther.getI147()) || (this.getI147() != null && castOther.getI147() != null
						&& this.getI147().equals(castOther.getI147())))
				&& ((this.getI148() == castOther.getI148()) || (this.getI148() != null && castOther.getI148() != null
						&& this.getI148().equals(castOther.getI148())))
				&& ((this.getI149() == castOther.getI149()) || (this.getI149() != null && castOther.getI149() != null
						&& this.getI149().equals(castOther.getI149())))
				&& ((this.getI150() == castOther.getI150()) || (this.getI150() != null && castOther.getI150() != null
						&& this.getI150().equals(castOther.getI150())))
				&& ((this.getI151() == castOther.getI151()) || (this.getI151() != null && castOther.getI151() != null
						&& this.getI151().equals(castOther.getI151())))
				&& ((this.getI152() == castOther.getI152()) || (this.getI152() != null && castOther.getI152() != null
						&& this.getI152().equals(castOther.getI152())))
				&& ((this.getI153() == castOther.getI153()) || (this.getI153() != null && castOther.getI153() != null
						&& this.getI153().equals(castOther.getI153())))
				&& ((this.getI154() == castOther.getI154()) || (this.getI154() != null && castOther.getI154() != null
						&& this.getI154().equals(castOther.getI154())))
				&& ((this.getI155() == castOther.getI155()) || (this.getI155() != null && castOther.getI155() != null
						&& this.getI155().equals(castOther.getI155())))
				&& ((this.getI156() == castOther.getI156()) || (this.getI156() != null && castOther.getI156() != null
						&& this.getI156().equals(castOther.getI156())))
				&& ((this.getI157() == castOther.getI157()) || (this.getI157() != null && castOther.getI157() != null
						&& this.getI157().equals(castOther.getI157())))
				&& ((this.getI158() == castOther.getI158()) || (this.getI158() != null && castOther.getI158() != null
						&& this.getI158().equals(castOther.getI158())))
				&& ((this.getI159() == castOther.getI159()) || (this.getI159() != null && castOther.getI159() != null
						&& this.getI159().equals(castOther.getI159())))
				&& ((this.getI160() == castOther.getI160()) || (this.getI160() != null && castOther.getI160() != null
						&& this.getI160().equals(castOther.getI160())))
				&& ((this.getI161() == castOther.getI161()) || (this.getI161() != null && castOther.getI161() != null
						&& this.getI161().equals(castOther.getI161())))
				&& ((this.getI162() == castOther.getI162()) || (this.getI162() != null && castOther.getI162() != null
						&& this.getI162().equals(castOther.getI162())))
				&& ((this.getI163() == castOther.getI163()) || (this.getI163() != null && castOther.getI163() != null
						&& this.getI163().equals(castOther.getI163())))
				&& ((this.getI164() == castOther.getI164()) || (this.getI164() != null && castOther.getI164() != null
						&& this.getI164().equals(castOther.getI164())))
				&& ((this.getI165() == castOther.getI165()) || (this.getI165() != null && castOther.getI165() != null
						&& this.getI165().equals(castOther.getI165())))
				&& ((this.getI166() == castOther.getI166()) || (this.getI166() != null && castOther.getI166() != null
						&& this.getI166().equals(castOther.getI166())))
				&& ((this.getI167() == castOther.getI167()) || (this.getI167() != null && castOther.getI167() != null
						&& this.getI167().equals(castOther.getI167())))
				&& ((this.getI168() == castOther.getI168()) || (this.getI168() != null && castOther.getI168() != null
						&& this.getI168().equals(castOther.getI168())))
				&& ((this.getI169() == castOther.getI169()) || (this.getI169() != null && castOther.getI169() != null
						&& this.getI169().equals(castOther.getI169())))
				&& ((this.getI170() == castOther.getI170()) || (this.getI170() != null && castOther.getI170() != null
						&& this.getI170().equals(castOther.getI170())))
				&& ((this.getI171() == castOther.getI171()) || (this.getI171() != null && castOther.getI171() != null
						&& this.getI171().equals(castOther.getI171())))
				&& ((this.getI172() == castOther.getI172()) || (this.getI172() != null && castOther.getI172() != null
						&& this.getI172().equals(castOther.getI172())))
				&& ((this.getI173() == castOther.getI173()) || (this.getI173() != null && castOther.getI173() != null
						&& this.getI173().equals(castOther.getI173())))
				&& ((this.getI174() == castOther.getI174()) || (this.getI174() != null && castOther.getI174() != null
						&& this.getI174().equals(castOther.getI174())))
				&& ((this.getI175() == castOther.getI175()) || (this.getI175() != null && castOther.getI175() != null
						&& this.getI175().equals(castOther.getI175())))
				&& ((this.getI176() == castOther.getI176()) || (this.getI176() != null && castOther.getI176() != null
						&& this.getI176().equals(castOther.getI176())))
				&& ((this.getI177() == castOther.getI177()) || (this.getI177() != null && castOther.getI177() != null
						&& this.getI177().equals(castOther.getI177())))
				&& ((this.getI178() == castOther.getI178()) || (this.getI178() != null && castOther.getI178() != null
						&& this.getI178().equals(castOther.getI178())))
				&& ((this.getI179() == castOther.getI179()) || (this.getI179() != null && castOther.getI179() != null
						&& this.getI179().equals(castOther.getI179())))
				&& ((this.getI180() == castOther.getI180()) || (this.getI180() != null && castOther.getI180() != null
						&& this.getI180().equals(castOther.getI180())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getI1() == null ? 0 : this.getI1().hashCode());
		result = 37 * result + (getI2() == null ? 0 : this.getI2().hashCode());
		result = 37 * result + (getI3() == null ? 0 : this.getI3().hashCode());
		result = 37 * result + (getI4() == null ? 0 : this.getI4().hashCode());
		result = 37 * result + (getI5() == null ? 0 : this.getI5().hashCode());
		result = 37 * result + (getI6() == null ? 0 : this.getI6().hashCode());
		result = 37 * result + (getI7() == null ? 0 : this.getI7().hashCode());
		result = 37 * result + (getI8() == null ? 0 : this.getI8().hashCode());
		result = 37 * result + (getI9() == null ? 0 : this.getI9().hashCode());
		result = 37 * result + (getI10() == null ? 0 : this.getI10().hashCode());
		result = 37 * result + (getI11() == null ? 0 : this.getI11().hashCode());
		result = 37 * result + (getI12() == null ? 0 : this.getI12().hashCode());
		result = 37 * result + (getI13() == null ? 0 : this.getI13().hashCode());
		result = 37 * result + (getI14() == null ? 0 : this.getI14().hashCode());
		result = 37 * result + (getI15() == null ? 0 : this.getI15().hashCode());
		result = 37 * result + (getI16() == null ? 0 : this.getI16().hashCode());
		result = 37 * result + (getI17() == null ? 0 : this.getI17().hashCode());
		result = 37 * result + (getI18() == null ? 0 : this.getI18().hashCode());
		result = 37 * result + (getI19() == null ? 0 : this.getI19().hashCode());
		result = 37 * result + (getI20() == null ? 0 : this.getI20().hashCode());
		result = 37 * result + (getI21() == null ? 0 : this.getI21().hashCode());
		result = 37 * result + (getI22() == null ? 0 : this.getI22().hashCode());
		result = 37 * result + (getI23() == null ? 0 : this.getI23().hashCode());
		result = 37 * result + (getI24() == null ? 0 : this.getI24().hashCode());
		result = 37 * result + (getI25() == null ? 0 : this.getI25().hashCode());
		result = 37 * result + (getI26() == null ? 0 : this.getI26().hashCode());
		result = 37 * result + (getI27() == null ? 0 : this.getI27().hashCode());
		result = 37 * result + (getI28() == null ? 0 : this.getI28().hashCode());
		result = 37 * result + (getI29() == null ? 0 : this.getI29().hashCode());
		result = 37 * result + (getI30() == null ? 0 : this.getI30().hashCode());
		result = 37 * result + (getI31() == null ? 0 : this.getI31().hashCode());
		result = 37 * result + (getI32() == null ? 0 : this.getI32().hashCode());
		result = 37 * result + (getI33() == null ? 0 : this.getI33().hashCode());
		result = 37 * result + (getI34() == null ? 0 : this.getI34().hashCode());
		result = 37 * result + (getI35() == null ? 0 : this.getI35().hashCode());
		result = 37 * result + (getI36() == null ? 0 : this.getI36().hashCode());
		result = 37 * result + (getI37() == null ? 0 : this.getI37().hashCode());
		result = 37 * result + (getI38() == null ? 0 : this.getI38().hashCode());
		result = 37 * result + (getI39() == null ? 0 : this.getI39().hashCode());
		result = 37 * result + (getI40() == null ? 0 : this.getI40().hashCode());
		result = 37 * result + (getI41() == null ? 0 : this.getI41().hashCode());
		result = 37 * result + (getI42() == null ? 0 : this.getI42().hashCode());
		result = 37 * result + (getI43() == null ? 0 : this.getI43().hashCode());
		result = 37 * result + (getI44() == null ? 0 : this.getI44().hashCode());
		result = 37 * result + (getI45() == null ? 0 : this.getI45().hashCode());
		result = 37 * result + (getI46() == null ? 0 : this.getI46().hashCode());
		result = 37 * result + (getI47() == null ? 0 : this.getI47().hashCode());
		result = 37 * result + (getI48() == null ? 0 : this.getI48().hashCode());
		result = 37 * result + (getI49() == null ? 0 : this.getI49().hashCode());
		result = 37 * result + (getI50() == null ? 0 : this.getI50().hashCode());
		result = 37 * result + (getI51() == null ? 0 : this.getI51().hashCode());
		result = 37 * result + (getI52() == null ? 0 : this.getI52().hashCode());
		result = 37 * result + (getI53() == null ? 0 : this.getI53().hashCode());
		result = 37 * result + (getI54() == null ? 0 : this.getI54().hashCode());
		result = 37 * result + (getI55() == null ? 0 : this.getI55().hashCode());
		result = 37 * result + (getI56() == null ? 0 : this.getI56().hashCode());
		result = 37 * result + (getI57() == null ? 0 : this.getI57().hashCode());
		result = 37 * result + (getI58() == null ? 0 : this.getI58().hashCode());
		result = 37 * result + (getI59() == null ? 0 : this.getI59().hashCode());
		result = 37 * result + (getI60() == null ? 0 : this.getI60().hashCode());
		result = 37 * result + (getI61() == null ? 0 : this.getI61().hashCode());
		result = 37 * result + (getI62() == null ? 0 : this.getI62().hashCode());
		result = 37 * result + (getI63() == null ? 0 : this.getI63().hashCode());
		result = 37 * result + (getI64() == null ? 0 : this.getI64().hashCode());
		result = 37 * result + (getI65() == null ? 0 : this.getI65().hashCode());
		result = 37 * result + (getI66() == null ? 0 : this.getI66().hashCode());
		result = 37 * result + (getI67() == null ? 0 : this.getI67().hashCode());
		result = 37 * result + (getI68() == null ? 0 : this.getI68().hashCode());
		result = 37 * result + (getI69() == null ? 0 : this.getI69().hashCode());
		result = 37 * result + (getI70() == null ? 0 : this.getI70().hashCode());
		result = 37 * result + (getI71() == null ? 0 : this.getI71().hashCode());
		result = 37 * result + (getI72() == null ? 0 : this.getI72().hashCode());
		result = 37 * result + (getI73() == null ? 0 : this.getI73().hashCode());
		result = 37 * result + (getI74() == null ? 0 : this.getI74().hashCode());
		result = 37 * result + (getI75() == null ? 0 : this.getI75().hashCode());
		result = 37 * result + (getI76() == null ? 0 : this.getI76().hashCode());
		result = 37 * result + (getI77() == null ? 0 : this.getI77().hashCode());
		result = 37 * result + (getI78() == null ? 0 : this.getI78().hashCode());
		result = 37 * result + (getI79() == null ? 0 : this.getI79().hashCode());
		result = 37 * result + (getI80() == null ? 0 : this.getI80().hashCode());
		result = 37 * result + (getI81() == null ? 0 : this.getI81().hashCode());
		result = 37 * result + (getI82() == null ? 0 : this.getI82().hashCode());
		result = 37 * result + (getI83() == null ? 0 : this.getI83().hashCode());
		result = 37 * result + (getI84() == null ? 0 : this.getI84().hashCode());
		result = 37 * result + (getI85() == null ? 0 : this.getI85().hashCode());
		result = 37 * result + (getI86() == null ? 0 : this.getI86().hashCode());
		result = 37 * result + (getI87() == null ? 0 : this.getI87().hashCode());
		result = 37 * result + (getI88() == null ? 0 : this.getI88().hashCode());
		result = 37 * result + (getI89() == null ? 0 : this.getI89().hashCode());
		result = 37 * result + (getI90() == null ? 0 : this.getI90().hashCode());
		result = 37 * result + (getI91() == null ? 0 : this.getI91().hashCode());
		result = 37 * result + (getI92() == null ? 0 : this.getI92().hashCode());
		result = 37 * result + (getI93() == null ? 0 : this.getI93().hashCode());
		result = 37 * result + (getI94() == null ? 0 : this.getI94().hashCode());
		result = 37 * result + (getI95() == null ? 0 : this.getI95().hashCode());
		result = 37 * result + (getI96() == null ? 0 : this.getI96().hashCode());
		result = 37 * result + (getI97() == null ? 0 : this.getI97().hashCode());
		result = 37 * result + (getI98() == null ? 0 : this.getI98().hashCode());
		result = 37 * result + (getI99() == null ? 0 : this.getI99().hashCode());
		result = 37 * result + (getI100() == null ? 0 : this.getI100().hashCode());
		result = 37 * result + (getI101() == null ? 0 : this.getI101().hashCode());
		result = 37 * result + (getI102() == null ? 0 : this.getI102().hashCode());
		result = 37 * result + (getI103() == null ? 0 : this.getI103().hashCode());
		result = 37 * result + (getI104() == null ? 0 : this.getI104().hashCode());
		result = 37 * result + (getI105() == null ? 0 : this.getI105().hashCode());
		result = 37 * result + (getI106() == null ? 0 : this.getI106().hashCode());
		result = 37 * result + (getI107() == null ? 0 : this.getI107().hashCode());
		result = 37 * result + (getI108() == null ? 0 : this.getI108().hashCode());
		result = 37 * result + (getI109() == null ? 0 : this.getI109().hashCode());
		result = 37 * result + (getI110() == null ? 0 : this.getI110().hashCode());
		result = 37 * result + (getI111() == null ? 0 : this.getI111().hashCode());
		result = 37 * result + (getI112() == null ? 0 : this.getI112().hashCode());
		result = 37 * result + (getI113() == null ? 0 : this.getI113().hashCode());
		result = 37 * result + (getI114() == null ? 0 : this.getI114().hashCode());
		result = 37 * result + (getI115() == null ? 0 : this.getI115().hashCode());
		result = 37 * result + (getI116() == null ? 0 : this.getI116().hashCode());
		result = 37 * result + (getI117() == null ? 0 : this.getI117().hashCode());
		result = 37 * result + (getI118() == null ? 0 : this.getI118().hashCode());
		result = 37 * result + (getI119() == null ? 0 : this.getI119().hashCode());
		result = 37 * result + (getI120() == null ? 0 : this.getI120().hashCode());
		result = 37 * result + (getI121() == null ? 0 : this.getI121().hashCode());
		result = 37 * result + (getI122() == null ? 0 : this.getI122().hashCode());
		result = 37 * result + (getI123() == null ? 0 : this.getI123().hashCode());
		result = 37 * result + (getI124() == null ? 0 : this.getI124().hashCode());
		result = 37 * result + (getI125() == null ? 0 : this.getI125().hashCode());
		result = 37 * result + (getI126() == null ? 0 : this.getI126().hashCode());
		result = 37 * result + (getI127() == null ? 0 : this.getI127().hashCode());
		result = 37 * result + (getI128() == null ? 0 : this.getI128().hashCode());
		result = 37 * result + (getI129() == null ? 0 : this.getI129().hashCode());
		result = 37 * result + (getI130() == null ? 0 : this.getI130().hashCode());
		result = 37 * result + (getI131() == null ? 0 : this.getI131().hashCode());
		result = 37 * result + (getI132() == null ? 0 : this.getI132().hashCode());
		result = 37 * result + (getI133() == null ? 0 : this.getI133().hashCode());
		result = 37 * result + (getI134() == null ? 0 : this.getI134().hashCode());
		result = 37 * result + (getI135() == null ? 0 : this.getI135().hashCode());
		result = 37 * result + (getI136() == null ? 0 : this.getI136().hashCode());
		result = 37 * result + (getI137() == null ? 0 : this.getI137().hashCode());
		result = 37 * result + (getI138() == null ? 0 : this.getI138().hashCode());
		result = 37 * result + (getI139() == null ? 0 : this.getI139().hashCode());
		result = 37 * result + (getI140() == null ? 0 : this.getI140().hashCode());
		result = 37 * result + (getI141() == null ? 0 : this.getI141().hashCode());
		result = 37 * result + (getI142() == null ? 0 : this.getI142().hashCode());
		result = 37 * result + (getI143() == null ? 0 : this.getI143().hashCode());
		result = 37 * result + (getI144() == null ? 0 : this.getI144().hashCode());
		result = 37 * result + (getI145() == null ? 0 : this.getI145().hashCode());
		result = 37 * result + (getI146() == null ? 0 : this.getI146().hashCode());
		result = 37 * result + (getI147() == null ? 0 : this.getI147().hashCode());
		result = 37 * result + (getI148() == null ? 0 : this.getI148().hashCode());
		result = 37 * result + (getI149() == null ? 0 : this.getI149().hashCode());
		result = 37 * result + (getI150() == null ? 0 : this.getI150().hashCode());
		result = 37 * result + (getI151() == null ? 0 : this.getI151().hashCode());
		result = 37 * result + (getI152() == null ? 0 : this.getI152().hashCode());
		result = 37 * result + (getI153() == null ? 0 : this.getI153().hashCode());
		result = 37 * result + (getI154() == null ? 0 : this.getI154().hashCode());
		result = 37 * result + (getI155() == null ? 0 : this.getI155().hashCode());
		result = 37 * result + (getI156() == null ? 0 : this.getI156().hashCode());
		result = 37 * result + (getI157() == null ? 0 : this.getI157().hashCode());
		result = 37 * result + (getI158() == null ? 0 : this.getI158().hashCode());
		result = 37 * result + (getI159() == null ? 0 : this.getI159().hashCode());
		result = 37 * result + (getI160() == null ? 0 : this.getI160().hashCode());
		result = 37 * result + (getI161() == null ? 0 : this.getI161().hashCode());
		result = 37 * result + (getI162() == null ? 0 : this.getI162().hashCode());
		result = 37 * result + (getI163() == null ? 0 : this.getI163().hashCode());
		result = 37 * result + (getI164() == null ? 0 : this.getI164().hashCode());
		result = 37 * result + (getI165() == null ? 0 : this.getI165().hashCode());
		result = 37 * result + (getI166() == null ? 0 : this.getI166().hashCode());
		result = 37 * result + (getI167() == null ? 0 : this.getI167().hashCode());
		result = 37 * result + (getI168() == null ? 0 : this.getI168().hashCode());
		result = 37 * result + (getI169() == null ? 0 : this.getI169().hashCode());
		result = 37 * result + (getI170() == null ? 0 : this.getI170().hashCode());
		result = 37 * result + (getI171() == null ? 0 : this.getI171().hashCode());
		result = 37 * result + (getI172() == null ? 0 : this.getI172().hashCode());
		result = 37 * result + (getI173() == null ? 0 : this.getI173().hashCode());
		result = 37 * result + (getI174() == null ? 0 : this.getI174().hashCode());
		result = 37 * result + (getI175() == null ? 0 : this.getI175().hashCode());
		result = 37 * result + (getI176() == null ? 0 : this.getI176().hashCode());
		result = 37 * result + (getI177() == null ? 0 : this.getI177().hashCode());
		result = 37 * result + (getI178() == null ? 0 : this.getI178().hashCode());
		result = 37 * result + (getI179() == null ? 0 : this.getI179().hashCode());
		result = 37 * result + (getI180() == null ? 0 : this.getI180().hashCode());
		return result;
	}

}
