package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Cape generated by hbm2java
 */
public class Cape implements java.io.Serializable {

	private CapeId id;

	public Cape() {
	}

	public Cape(CapeId id) {
		this.id = id;
	}

	public CapeId getId() {
		return this.id;
	}

	public void setId(CapeId id) {
		this.id = id;
	}

}
