package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Chadsmith generated by hbm2java
 */
public class Chadsmith implements java.io.Serializable {

	private Integer counter;
	private String deerNumber;
	private boolean chadPrinted;

	public Chadsmith() {
	}

	public Chadsmith(String deerNumber, boolean chadPrinted) {
		this.deerNumber = deerNumber;
		this.chadPrinted = chadPrinted;
	}

	public Integer getCounter() {
		return this.counter;
	}

	public void setCounter(Integer counter) {
		this.counter = counter;
	}

	public String getDeerNumber() {
		return this.deerNumber;
	}

	public void setDeerNumber(String deerNumber) {
		this.deerNumber = deerNumber;
	}

	public boolean isChadPrinted() {
		return this.chadPrinted;
	}

	public void setChadPrinted(boolean chadPrinted) {
		this.chadPrinted = chadPrinted;
	}

}
