package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Cut generated by hbm2java
 */
public class Cut implements java.io.Serializable {

	private CutId id;

	public Cut() {
	}

	public Cut(CutId id) {
		this.id = id;
	}

	public CutId getId() {
		return this.id;
	}

	public void setId(CutId id) {
		this.id = id;
	}

}
