package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * CutId generated by hbm2java
 */
public class CutId implements java.io.Serializable {

	private int id;
	private String cut;
	private Double species;
	private Double primal;

	public CutId() {
	}

	public CutId(int id) {
		this.id = id;
	}

	public CutId(int id, String cut, Double species, Double primal) {
		this.id = id;
		this.cut = cut;
		this.species = species;
		this.primal = primal;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCut() {
		return this.cut;
	}

	public void setCut(String cut) {
		this.cut = cut;
	}

	public Double getSpecies() {
		return this.species;
	}

	public void setSpecies(Double species) {
		this.species = species;
	}

	public Double getPrimal() {
		return this.primal;
	}

	public void setPrimal(Double primal) {
		this.primal = primal;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CutId))
			return false;
		CutId castOther = (CutId) other;

		return (this.getId() == castOther.getId()) && ((this.getCut() == castOther.getCut())
				|| (this.getCut() != null && castOther.getCut() != null && this.getCut().equals(castOther.getCut())))
				&& ((this.getSpecies() == castOther.getSpecies()) || (this.getSpecies() != null
						&& castOther.getSpecies() != null && this.getSpecies().equals(castOther.getSpecies())))
				&& ((this.getPrimal() == castOther.getPrimal()) || (this.getPrimal() != null
						&& castOther.getPrimal() != null && this.getPrimal().equals(castOther.getPrimal())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getCut() == null ? 0 : this.getCut().hashCode());
		result = 37 * result + (getSpecies() == null ? 0 : this.getSpecies().hashCode());
		result = 37 * result + (getPrimal() == null ? 0 : this.getPrimal().hashCode());
		return result;
	}

}
