package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Dbarrel generated by hbm2java
 */
public class Dbarrel implements java.io.Serializable {

	private DbarrelId id;

	public Dbarrel() {
	}

	public Dbarrel(DbarrelId id) {
		this.id = id;
	}

	public DbarrelId getId() {
		return this.id;
	}

	public void setId(DbarrelId id) {
		this.id = id;
	}

}
