package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * DbarrelId generated by hbm2java
 */
public class DbarrelId implements java.io.Serializable {

	private int location;
	private String i1;
	private String i2;
	private String i3;
	private String i4;
	private String i5;
	private String i6;
	private String i7;
	private String i8;
	private String i9;
	private String a;
	private String b;
	private String c;
	private String d;
	private String e;
	private String f;
	private String g;
	private String h;
	private String i;

	public DbarrelId() {
	}

	public DbarrelId(int location, String i1, String i2, String i3, String i4, String i5, String i6, String i7,
			String i8, String i9, String a, String b, String c, String d, String e, String f, String g, String h,
			String i) {
		this.location = location;
		this.i1 = i1;
		this.i2 = i2;
		this.i3 = i3;
		this.i4 = i4;
		this.i5 = i5;
		this.i6 = i6;
		this.i7 = i7;
		this.i8 = i8;
		this.i9 = i9;
		this.a = a;
		this.b = b;
		this.c = c;
		this.d = d;
		this.e = e;
		this.f = f;
		this.g = g;
		this.h = h;
		this.i = i;
	}

	public int getLocation() {
		return this.location;
	}

	public void setLocation(int location) {
		this.location = location;
	}

	public String getI1() {
		return this.i1;
	}

	public void setI1(String i1) {
		this.i1 = i1;
	}

	public String getI2() {
		return this.i2;
	}

	public void setI2(String i2) {
		this.i2 = i2;
	}

	public String getI3() {
		return this.i3;
	}

	public void setI3(String i3) {
		this.i3 = i3;
	}

	public String getI4() {
		return this.i4;
	}

	public void setI4(String i4) {
		this.i4 = i4;
	}

	public String getI5() {
		return this.i5;
	}

	public void setI5(String i5) {
		this.i5 = i5;
	}

	public String getI6() {
		return this.i6;
	}

	public void setI6(String i6) {
		this.i6 = i6;
	}

	public String getI7() {
		return this.i7;
	}

	public void setI7(String i7) {
		this.i7 = i7;
	}

	public String getI8() {
		return this.i8;
	}

	public void setI8(String i8) {
		this.i8 = i8;
	}

	public String getI9() {
		return this.i9;
	}

	public void setI9(String i9) {
		this.i9 = i9;
	}

	public String getA() {
		return this.a;
	}

	public void setA(String a) {
		this.a = a;
	}

	public String getB() {
		return this.b;
	}

	public void setB(String b) {
		this.b = b;
	}

	public String getC() {
		return this.c;
	}

	public void setC(String c) {
		this.c = c;
	}

	public String getD() {
		return this.d;
	}

	public void setD(String d) {
		this.d = d;
	}

	public String getE() {
		return this.e;
	}

	public void setE(String e) {
		this.e = e;
	}

	public String getF() {
		return this.f;
	}

	public void setF(String f) {
		this.f = f;
	}

	public String getG() {
		return this.g;
	}

	public void setG(String g) {
		this.g = g;
	}

	public String getH() {
		return this.h;
	}

	public void setH(String h) {
		this.h = h;
	}

	public String getI() {
		return this.i;
	}

	public void setI(String i) {
		this.i = i;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DbarrelId))
			return false;
		DbarrelId castOther = (DbarrelId) other;

		return (this.getLocation() == castOther.getLocation()) && ((this.getI1() == castOther.getI1())
				|| (this.getI1() != null && castOther.getI1() != null && this.getI1().equals(castOther.getI1())))
				&& ((this.getI2() == castOther.getI2()) || (this.getI2() != null && castOther.getI2() != null
						&& this.getI2().equals(castOther.getI2())))
				&& ((this.getI3() == castOther.getI3()) || (this.getI3() != null && castOther.getI3() != null
						&& this.getI3().equals(castOther.getI3())))
				&& ((this.getI4() == castOther.getI4()) || (this.getI4() != null && castOther.getI4() != null
						&& this.getI4().equals(castOther.getI4())))
				&& ((this.getI5() == castOther.getI5()) || (this.getI5() != null && castOther.getI5() != null
						&& this.getI5().equals(castOther.getI5())))
				&& ((this.getI6() == castOther.getI6()) || (this.getI6() != null && castOther.getI6() != null
						&& this.getI6().equals(castOther.getI6())))
				&& ((this.getI7() == castOther.getI7()) || (this.getI7() != null && castOther.getI7() != null
						&& this.getI7().equals(castOther.getI7())))
				&& ((this.getI8() == castOther.getI8()) || (this.getI8() != null && castOther.getI8() != null
						&& this.getI8().equals(castOther.getI8())))
				&& ((this.getI9() == castOther.getI9()) || (this.getI9() != null && castOther.getI9() != null
						&& this.getI9().equals(castOther.getI9())))
				&& ((this.getA() == castOther.getA())
						|| (this.getA() != null && castOther.getA() != null && this.getA().equals(castOther.getA())))
				&& ((this.getB() == castOther.getB())
						|| (this.getB() != null && castOther.getB() != null && this.getB().equals(castOther.getB())))
				&& ((this.getC() == castOther.getC())
						|| (this.getC() != null && castOther.getC() != null && this.getC().equals(castOther.getC())))
				&& ((this.getD() == castOther.getD())
						|| (this.getD() != null && castOther.getD() != null && this.getD().equals(castOther.getD())))
				&& ((this.getE() == castOther.getE())
						|| (this.getE() != null && castOther.getE() != null && this.getE().equals(castOther.getE())))
				&& ((this.getF() == castOther.getF())
						|| (this.getF() != null && castOther.getF() != null && this.getF().equals(castOther.getF())))
				&& ((this.getG() == castOther.getG())
						|| (this.getG() != null && castOther.getG() != null && this.getG().equals(castOther.getG())))
				&& ((this.getH() == castOther.getH())
						|| (this.getH() != null && castOther.getH() != null && this.getH().equals(castOther.getH())))
				&& ((this.getI() == castOther.getI())
						|| (this.getI() != null && castOther.getI() != null && this.getI().equals(castOther.getI())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLocation();
		result = 37 * result + (getI1() == null ? 0 : this.getI1().hashCode());
		result = 37 * result + (getI2() == null ? 0 : this.getI2().hashCode());
		result = 37 * result + (getI3() == null ? 0 : this.getI3().hashCode());
		result = 37 * result + (getI4() == null ? 0 : this.getI4().hashCode());
		result = 37 * result + (getI5() == null ? 0 : this.getI5().hashCode());
		result = 37 * result + (getI6() == null ? 0 : this.getI6().hashCode());
		result = 37 * result + (getI7() == null ? 0 : this.getI7().hashCode());
		result = 37 * result + (getI8() == null ? 0 : this.getI8().hashCode());
		result = 37 * result + (getI9() == null ? 0 : this.getI9().hashCode());
		result = 37 * result + (getA() == null ? 0 : this.getA().hashCode());
		result = 37 * result + (getB() == null ? 0 : this.getB().hashCode());
		result = 37 * result + (getC() == null ? 0 : this.getC().hashCode());
		result = 37 * result + (getD() == null ? 0 : this.getD().hashCode());
		result = 37 * result + (getE() == null ? 0 : this.getE().hashCode());
		result = 37 * result + (getF() == null ? 0 : this.getF().hashCode());
		result = 37 * result + (getG() == null ? 0 : this.getG().hashCode());
		result = 37 * result + (getH() == null ? 0 : this.getH().hashCode());
		result = 37 * result + (getI() == null ? 0 : this.getI().hashCode());
		return result;
	}

}
