package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Deershelf generated by hbm2java
 */
public class Deershelf implements java.io.Serializable {

	private DeershelfId id;

	public Deershelf() {
	}

	public Deershelf(DeershelfId id) {
		this.id = id;
	}

	public DeershelfId getId() {
		return this.id;
	}

	public void setId(DeershelfId id) {
		this.id = id;
	}

}
