package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Deershelfii generated by hbm2java
 */
public class Deershelfii implements java.io.Serializable {

	private DeershelfiiId id;

	public Deershelfii() {
	}

	public Deershelfii(DeershelfiiId id) {
		this.id = id;
	}

	public DeershelfiiId getId() {
		return this.id;
	}

	public void setId(DeershelfiiId id) {
		this.id = id;
	}

}
