package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Deercart generated by hbm2java
 */
public class Deercart implements java.io.Serializable {

	private DeercartId id;

	public Deercart() {
	}

	public Deercart(DeercartId id) {
		this.id = id;
	}

	public DeercartId getId() {
		return this.id;
	}

	public void setId(DeercartId id) {
		this.id = id;
	}

}
