package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * DeerId generated by hbm2java
 */
public class DeerId implements java.io.Serializable {

	private String i1;
	private String i2;
	private String i3;
	private String i11;
	private String i12;
	private String i13;
	private String i21;
	private String i22;
	private String i23;
	private String i31;
	private String i32;
	private String i33;
	private String i41;
	private String i42;
	private String i43;
	private String i51;
	private String i52;
	private String i53;
	private String i61;
	private String i62;
	private String i63;
	private String i71;
	private String i72;
	private String i73;
	private String i81;
	private String i82;
	private String i83;
	private String i91;
	private String i92;
	private String i93;
	private String i101;
	private String i102;
	private String i103;
	private String i111;
	private String i112;
	private String i113;
	private String i121;
	private String i122;
	private String i123;
	private String i131;
	private String i132;
	private String i133;
	private String i141;
	private String i142;
	private String i143;
	private String i151;
	private String i152;
	private String i153;
	private String i161;
	private String i162;
	private String i163;
	private String i171;
	private String i172;
	private String i173;
	private String i181;
	private String i182;
	private String i183;
	private String i191;
	private String i192;
	private String i193;
	private String i201;
	private String i202;
	private String i203;
	private String i211;
	private String i212;
	private String i213;
	private String i221;
	private String i222;
	private String i223;

	public DeerId() {
	}

	public DeerId(String i1, String i2, String i3, String i11, String i12, String i13, String i21, String i22,
			String i23, String i31, String i32, String i33, String i41, String i42, String i43, String i51, String i52,
			String i53, String i61, String i62, String i63, String i71, String i72, String i73, String i81, String i82,
			String i83, String i91, String i92, String i93, String i101, String i102, String i103, String i111,
			String i112, String i113, String i121, String i122, String i123, String i131, String i132, String i133,
			String i141, String i142, String i143, String i151, String i152, String i153, String i161, String i162,
			String i163, String i171, String i172, String i173, String i181, String i182, String i183, String i191,
			String i192, String i193, String i201, String i202, String i203, String i211, String i212, String i213,
			String i221, String i222, String i223) {
		this.i1 = i1;
		this.i2 = i2;
		this.i3 = i3;
		this.i11 = i11;
		this.i12 = i12;
		this.i13 = i13;
		this.i21 = i21;
		this.i22 = i22;
		this.i23 = i23;
		this.i31 = i31;
		this.i32 = i32;
		this.i33 = i33;
		this.i41 = i41;
		this.i42 = i42;
		this.i43 = i43;
		this.i51 = i51;
		this.i52 = i52;
		this.i53 = i53;
		this.i61 = i61;
		this.i62 = i62;
		this.i63 = i63;
		this.i71 = i71;
		this.i72 = i72;
		this.i73 = i73;
		this.i81 = i81;
		this.i82 = i82;
		this.i83 = i83;
		this.i91 = i91;
		this.i92 = i92;
		this.i93 = i93;
		this.i101 = i101;
		this.i102 = i102;
		this.i103 = i103;
		this.i111 = i111;
		this.i112 = i112;
		this.i113 = i113;
		this.i121 = i121;
		this.i122 = i122;
		this.i123 = i123;
		this.i131 = i131;
		this.i132 = i132;
		this.i133 = i133;
		this.i141 = i141;
		this.i142 = i142;
		this.i143 = i143;
		this.i151 = i151;
		this.i152 = i152;
		this.i153 = i153;
		this.i161 = i161;
		this.i162 = i162;
		this.i163 = i163;
		this.i171 = i171;
		this.i172 = i172;
		this.i173 = i173;
		this.i181 = i181;
		this.i182 = i182;
		this.i183 = i183;
		this.i191 = i191;
		this.i192 = i192;
		this.i193 = i193;
		this.i201 = i201;
		this.i202 = i202;
		this.i203 = i203;
		this.i211 = i211;
		this.i212 = i212;
		this.i213 = i213;
		this.i221 = i221;
		this.i222 = i222;
		this.i223 = i223;
	}

	public String getI1() {
		return this.i1;
	}

	public void setI1(String i1) {
		this.i1 = i1;
	}

	public String getI2() {
		return this.i2;
	}

	public void setI2(String i2) {
		this.i2 = i2;
	}

	public String getI3() {
		return this.i3;
	}

	public void setI3(String i3) {
		this.i3 = i3;
	}

	public String getI11() {
		return this.i11;
	}

	public void setI11(String i11) {
		this.i11 = i11;
	}

	public String getI12() {
		return this.i12;
	}

	public void setI12(String i12) {
		this.i12 = i12;
	}

	public String getI13() {
		return this.i13;
	}

	public void setI13(String i13) {
		this.i13 = i13;
	}

	public String getI21() {
		return this.i21;
	}

	public void setI21(String i21) {
		this.i21 = i21;
	}

	public String getI22() {
		return this.i22;
	}

	public void setI22(String i22) {
		this.i22 = i22;
	}

	public String getI23() {
		return this.i23;
	}

	public void setI23(String i23) {
		this.i23 = i23;
	}

	public String getI31() {
		return this.i31;
	}

	public void setI31(String i31) {
		this.i31 = i31;
	}

	public String getI32() {
		return this.i32;
	}

	public void setI32(String i32) {
		this.i32 = i32;
	}

	public String getI33() {
		return this.i33;
	}

	public void setI33(String i33) {
		this.i33 = i33;
	}

	public String getI41() {
		return this.i41;
	}

	public void setI41(String i41) {
		this.i41 = i41;
	}

	public String getI42() {
		return this.i42;
	}

	public void setI42(String i42) {
		this.i42 = i42;
	}

	public String getI43() {
		return this.i43;
	}

	public void setI43(String i43) {
		this.i43 = i43;
	}

	public String getI51() {
		return this.i51;
	}

	public void setI51(String i51) {
		this.i51 = i51;
	}

	public String getI52() {
		return this.i52;
	}

	public void setI52(String i52) {
		this.i52 = i52;
	}

	public String getI53() {
		return this.i53;
	}

	public void setI53(String i53) {
		this.i53 = i53;
	}

	public String getI61() {
		return this.i61;
	}

	public void setI61(String i61) {
		this.i61 = i61;
	}

	public String getI62() {
		return this.i62;
	}

	public void setI62(String i62) {
		this.i62 = i62;
	}

	public String getI63() {
		return this.i63;
	}

	public void setI63(String i63) {
		this.i63 = i63;
	}

	public String getI71() {
		return this.i71;
	}

	public void setI71(String i71) {
		this.i71 = i71;
	}

	public String getI72() {
		return this.i72;
	}

	public void setI72(String i72) {
		this.i72 = i72;
	}

	public String getI73() {
		return this.i73;
	}

	public void setI73(String i73) {
		this.i73 = i73;
	}

	public String getI81() {
		return this.i81;
	}

	public void setI81(String i81) {
		this.i81 = i81;
	}

	public String getI82() {
		return this.i82;
	}

	public void setI82(String i82) {
		this.i82 = i82;
	}

	public String getI83() {
		return this.i83;
	}

	public void setI83(String i83) {
		this.i83 = i83;
	}

	public String getI91() {
		return this.i91;
	}

	public void setI91(String i91) {
		this.i91 = i91;
	}

	public String getI92() {
		return this.i92;
	}

	public void setI92(String i92) {
		this.i92 = i92;
	}

	public String getI93() {
		return this.i93;
	}

	public void setI93(String i93) {
		this.i93 = i93;
	}

	public String getI101() {
		return this.i101;
	}

	public void setI101(String i101) {
		this.i101 = i101;
	}

	public String getI102() {
		return this.i102;
	}

	public void setI102(String i102) {
		this.i102 = i102;
	}

	public String getI103() {
		return this.i103;
	}

	public void setI103(String i103) {
		this.i103 = i103;
	}

	public String getI111() {
		return this.i111;
	}

	public void setI111(String i111) {
		this.i111 = i111;
	}

	public String getI112() {
		return this.i112;
	}

	public void setI112(String i112) {
		this.i112 = i112;
	}

	public String getI113() {
		return this.i113;
	}

	public void setI113(String i113) {
		this.i113 = i113;
	}

	public String getI121() {
		return this.i121;
	}

	public void setI121(String i121) {
		this.i121 = i121;
	}

	public String getI122() {
		return this.i122;
	}

	public void setI122(String i122) {
		this.i122 = i122;
	}

	public String getI123() {
		return this.i123;
	}

	public void setI123(String i123) {
		this.i123 = i123;
	}

	public String getI131() {
		return this.i131;
	}

	public void setI131(String i131) {
		this.i131 = i131;
	}

	public String getI132() {
		return this.i132;
	}

	public void setI132(String i132) {
		this.i132 = i132;
	}

	public String getI133() {
		return this.i133;
	}

	public void setI133(String i133) {
		this.i133 = i133;
	}

	public String getI141() {
		return this.i141;
	}

	public void setI141(String i141) {
		this.i141 = i141;
	}

	public String getI142() {
		return this.i142;
	}

	public void setI142(String i142) {
		this.i142 = i142;
	}

	public String getI143() {
		return this.i143;
	}

	public void setI143(String i143) {
		this.i143 = i143;
	}

	public String getI151() {
		return this.i151;
	}

	public void setI151(String i151) {
		this.i151 = i151;
	}

	public String getI152() {
		return this.i152;
	}

	public void setI152(String i152) {
		this.i152 = i152;
	}

	public String getI153() {
		return this.i153;
	}

	public void setI153(String i153) {
		this.i153 = i153;
	}

	public String getI161() {
		return this.i161;
	}

	public void setI161(String i161) {
		this.i161 = i161;
	}

	public String getI162() {
		return this.i162;
	}

	public void setI162(String i162) {
		this.i162 = i162;
	}

	public String getI163() {
		return this.i163;
	}

	public void setI163(String i163) {
		this.i163 = i163;
	}

	public String getI171() {
		return this.i171;
	}

	public void setI171(String i171) {
		this.i171 = i171;
	}

	public String getI172() {
		return this.i172;
	}

	public void setI172(String i172) {
		this.i172 = i172;
	}

	public String getI173() {
		return this.i173;
	}

	public void setI173(String i173) {
		this.i173 = i173;
	}

	public String getI181() {
		return this.i181;
	}

	public void setI181(String i181) {
		this.i181 = i181;
	}

	public String getI182() {
		return this.i182;
	}

	public void setI182(String i182) {
		this.i182 = i182;
	}

	public String getI183() {
		return this.i183;
	}

	public void setI183(String i183) {
		this.i183 = i183;
	}

	public String getI191() {
		return this.i191;
	}

	public void setI191(String i191) {
		this.i191 = i191;
	}

	public String getI192() {
		return this.i192;
	}

	public void setI192(String i192) {
		this.i192 = i192;
	}

	public String getI193() {
		return this.i193;
	}

	public void setI193(String i193) {
		this.i193 = i193;
	}

	public String getI201() {
		return this.i201;
	}

	public void setI201(String i201) {
		this.i201 = i201;
	}

	public String getI202() {
		return this.i202;
	}

	public void setI202(String i202) {
		this.i202 = i202;
	}

	public String getI203() {
		return this.i203;
	}

	public void setI203(String i203) {
		this.i203 = i203;
	}

	public String getI211() {
		return this.i211;
	}

	public void setI211(String i211) {
		this.i211 = i211;
	}

	public String getI212() {
		return this.i212;
	}

	public void setI212(String i212) {
		this.i212 = i212;
	}

	public String getI213() {
		return this.i213;
	}

	public void setI213(String i213) {
		this.i213 = i213;
	}

	public String getI221() {
		return this.i221;
	}

	public void setI221(String i221) {
		this.i221 = i221;
	}

	public String getI222() {
		return this.i222;
	}

	public void setI222(String i222) {
		this.i222 = i222;
	}

	public String getI223() {
		return this.i223;
	}

	public void setI223(String i223) {
		this.i223 = i223;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DeerId))
			return false;
		DeerId castOther = (DeerId) other;

		return ((this.getI1() == castOther.getI1())
				|| (this.getI1() != null && castOther.getI1() != null && this.getI1().equals(castOther.getI1())))
				&& ((this.getI2() == castOther.getI2()) || (this.getI2() != null && castOther.getI2() != null
						&& this.getI2().equals(castOther.getI2())))
				&& ((this.getI3() == castOther.getI3()) || (this.getI3() != null && castOther.getI3() != null
						&& this.getI3().equals(castOther.getI3())))
				&& ((this.getI11() == castOther.getI11()) || (this.getI11() != null && castOther.getI11() != null
						&& this.getI11().equals(castOther.getI11())))
				&& ((this.getI12() == castOther.getI12()) || (this.getI12() != null && castOther.getI12() != null
						&& this.getI12().equals(castOther.getI12())))
				&& ((this.getI13() == castOther.getI13()) || (this.getI13() != null && castOther.getI13() != null
						&& this.getI13().equals(castOther.getI13())))
				&& ((this.getI21() == castOther.getI21()) || (this.getI21() != null && castOther.getI21() != null
						&& this.getI21().equals(castOther.getI21())))
				&& ((this.getI22() == castOther.getI22()) || (this.getI22() != null && castOther.getI22() != null
						&& this.getI22().equals(castOther.getI22())))
				&& ((this.getI23() == castOther.getI23()) || (this.getI23() != null && castOther.getI23() != null
						&& this.getI23().equals(castOther.getI23())))
				&& ((this.getI31() == castOther.getI31()) || (this.getI31() != null && castOther.getI31() != null
						&& this.getI31().equals(castOther.getI31())))
				&& ((this.getI32() == castOther.getI32()) || (this.getI32() != null && castOther.getI32() != null
						&& this.getI32().equals(castOther.getI32())))
				&& ((this.getI33() == castOther.getI33()) || (this.getI33() != null && castOther.getI33() != null
						&& this.getI33().equals(castOther.getI33())))
				&& ((this.getI41() == castOther.getI41()) || (this.getI41() != null && castOther.getI41() != null
						&& this.getI41().equals(castOther.getI41())))
				&& ((this.getI42() == castOther.getI42()) || (this.getI42() != null && castOther.getI42() != null
						&& this.getI42().equals(castOther.getI42())))
				&& ((this.getI43() == castOther.getI43()) || (this.getI43() != null && castOther.getI43() != null
						&& this.getI43().equals(castOther.getI43())))
				&& ((this.getI51() == castOther.getI51()) || (this.getI51() != null && castOther.getI51() != null
						&& this.getI51().equals(castOther.getI51())))
				&& ((this.getI52() == castOther.getI52()) || (this.getI52() != null && castOther.getI52() != null
						&& this.getI52().equals(castOther.getI52())))
				&& ((this.getI53() == castOther.getI53()) || (this.getI53() != null && castOther.getI53() != null
						&& this.getI53().equals(castOther.getI53())))
				&& ((this.getI61() == castOther.getI61()) || (this.getI61() != null && castOther.getI61() != null
						&& this.getI61().equals(castOther.getI61())))
				&& ((this.getI62() == castOther.getI62()) || (this.getI62() != null && castOther.getI62() != null
						&& this.getI62().equals(castOther.getI62())))
				&& ((this.getI63() == castOther.getI63()) || (this.getI63() != null && castOther.getI63() != null
						&& this.getI63().equals(castOther.getI63())))
				&& ((this.getI71() == castOther.getI71()) || (this.getI71() != null && castOther.getI71() != null
						&& this.getI71().equals(castOther.getI71())))
				&& ((this.getI72() == castOther.getI72()) || (this.getI72() != null && castOther.getI72() != null
						&& this.getI72().equals(castOther.getI72())))
				&& ((this.getI73() == castOther.getI73()) || (this.getI73() != null && castOther.getI73() != null
						&& this.getI73().equals(castOther.getI73())))
				&& ((this.getI81() == castOther.getI81()) || (this.getI81() != null && castOther.getI81() != null
						&& this.getI81().equals(castOther.getI81())))
				&& ((this.getI82() == castOther.getI82()) || (this.getI82() != null && castOther.getI82() != null
						&& this.getI82().equals(castOther.getI82())))
				&& ((this.getI83() == castOther.getI83()) || (this.getI83() != null && castOther.getI83() != null
						&& this.getI83().equals(castOther.getI83())))
				&& ((this.getI91() == castOther.getI91()) || (this.getI91() != null && castOther.getI91() != null
						&& this.getI91().equals(castOther.getI91())))
				&& ((this.getI92() == castOther.getI92()) || (this.getI92() != null && castOther.getI92() != null
						&& this.getI92().equals(castOther.getI92())))
				&& ((this.getI93() == castOther.getI93()) || (this.getI93() != null && castOther.getI93() != null
						&& this.getI93().equals(castOther.getI93())))
				&& ((this.getI101() == castOther.getI101()) || (this.getI101() != null && castOther.getI101() != null
						&& this.getI101().equals(castOther.getI101())))
				&& ((this.getI102() == castOther.getI102()) || (this.getI102() != null && castOther.getI102() != null
						&& this.getI102().equals(castOther.getI102())))
				&& ((this.getI103() == castOther.getI103()) || (this.getI103() != null && castOther.getI103() != null
						&& this.getI103().equals(castOther.getI103())))
				&& ((this.getI111() == castOther.getI111()) || (this.getI111() != null && castOther.getI111() != null
						&& this.getI111().equals(castOther.getI111())))
				&& ((this.getI112() == castOther.getI112()) || (this.getI112() != null && castOther.getI112() != null
						&& this.getI112().equals(castOther.getI112())))
				&& ((this.getI113() == castOther.getI113()) || (this.getI113() != null && castOther.getI113() != null
						&& this.getI113().equals(castOther.getI113())))
				&& ((this.getI121() == castOther.getI121()) || (this.getI121() != null && castOther.getI121() != null
						&& this.getI121().equals(castOther.getI121())))
				&& ((this.getI122() == castOther.getI122()) || (this.getI122() != null && castOther.getI122() != null
						&& this.getI122().equals(castOther.getI122())))
				&& ((this.getI123() == castOther.getI123()) || (this.getI123() != null && castOther.getI123() != null
						&& this.getI123().equals(castOther.getI123())))
				&& ((this.getI131() == castOther.getI131()) || (this.getI131() != null && castOther.getI131() != null
						&& this.getI131().equals(castOther.getI131())))
				&& ((this.getI132() == castOther.getI132()) || (this.getI132() != null && castOther.getI132() != null
						&& this.getI132().equals(castOther.getI132())))
				&& ((this.getI133() == castOther.getI133()) || (this.getI133() != null && castOther.getI133() != null
						&& this.getI133().equals(castOther.getI133())))
				&& ((this.getI141() == castOther.getI141()) || (this.getI141() != null && castOther.getI141() != null
						&& this.getI141().equals(castOther.getI141())))
				&& ((this.getI142() == castOther.getI142()) || (this.getI142() != null && castOther.getI142() != null
						&& this.getI142().equals(castOther.getI142())))
				&& ((this.getI143() == castOther.getI143()) || (this.getI143() != null && castOther.getI143() != null
						&& this.getI143().equals(castOther.getI143())))
				&& ((this.getI151() == castOther.getI151()) || (this.getI151() != null && castOther.getI151() != null
						&& this.getI151().equals(castOther.getI151())))
				&& ((this.getI152() == castOther.getI152()) || (this.getI152() != null && castOther.getI152() != null
						&& this.getI152().equals(castOther.getI152())))
				&& ((this.getI153() == castOther.getI153()) || (this.getI153() != null && castOther.getI153() != null
						&& this.getI153().equals(castOther.getI153())))
				&& ((this.getI161() == castOther.getI161()) || (this.getI161() != null && castOther.getI161() != null
						&& this.getI161().equals(castOther.getI161())))
				&& ((this.getI162() == castOther.getI162()) || (this.getI162() != null && castOther.getI162() != null
						&& this.getI162().equals(castOther.getI162())))
				&& ((this.getI163() == castOther.getI163()) || (this.getI163() != null && castOther.getI163() != null
						&& this.getI163().equals(castOther.getI163())))
				&& ((this.getI171() == castOther.getI171()) || (this.getI171() != null && castOther.getI171() != null
						&& this.getI171().equals(castOther.getI171())))
				&& ((this.getI172() == castOther.getI172()) || (this.getI172() != null && castOther.getI172() != null
						&& this.getI172().equals(castOther.getI172())))
				&& ((this.getI173() == castOther.getI173()) || (this.getI173() != null && castOther.getI173() != null
						&& this.getI173().equals(castOther.getI173())))
				&& ((this.getI181() == castOther.getI181()) || (this.getI181() != null && castOther.getI181() != null
						&& this.getI181().equals(castOther.getI181())))
				&& ((this.getI182() == castOther.getI182()) || (this.getI182() != null && castOther.getI182() != null
						&& this.getI182().equals(castOther.getI182())))
				&& ((this.getI183() == castOther.getI183()) || (this.getI183() != null && castOther.getI183() != null
						&& this.getI183().equals(castOther.getI183())))
				&& ((this.getI191() == castOther.getI191()) || (this.getI191() != null && castOther.getI191() != null
						&& this.getI191().equals(castOther.getI191())))
				&& ((this.getI192() == castOther.getI192()) || (this.getI192() != null && castOther.getI192() != null
						&& this.getI192().equals(castOther.getI192())))
				&& ((this.getI193() == castOther.getI193()) || (this.getI193() != null && castOther.getI193() != null
						&& this.getI193().equals(castOther.getI193())))
				&& ((this.getI201() == castOther.getI201()) || (this.getI201() != null && castOther.getI201() != null
						&& this.getI201().equals(castOther.getI201())))
				&& ((this.getI202() == castOther.getI202()) || (this.getI202() != null && castOther.getI202() != null
						&& this.getI202().equals(castOther.getI202())))
				&& ((this.getI203() == castOther.getI203()) || (this.getI203() != null && castOther.getI203() != null
						&& this.getI203().equals(castOther.getI203())))
				&& ((this.getI211() == castOther.getI211()) || (this.getI211() != null && castOther.getI211() != null
						&& this.getI211().equals(castOther.getI211())))
				&& ((this.getI212() == castOther.getI212()) || (this.getI212() != null && castOther.getI212() != null
						&& this.getI212().equals(castOther.getI212())))
				&& ((this.getI213() == castOther.getI213()) || (this.getI213() != null && castOther.getI213() != null
						&& this.getI213().equals(castOther.getI213())))
				&& ((this.getI221() == castOther.getI221()) || (this.getI221() != null && castOther.getI221() != null
						&& this.getI221().equals(castOther.getI221())))
				&& ((this.getI222() == castOther.getI222()) || (this.getI222() != null && castOther.getI222() != null
						&& this.getI222().equals(castOther.getI222())))
				&& ((this.getI223() == castOther.getI223()) || (this.getI223() != null && castOther.getI223() != null
						&& this.getI223().equals(castOther.getI223())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getI1() == null ? 0 : this.getI1().hashCode());
		result = 37 * result + (getI2() == null ? 0 : this.getI2().hashCode());
		result = 37 * result + (getI3() == null ? 0 : this.getI3().hashCode());
		result = 37 * result + (getI11() == null ? 0 : this.getI11().hashCode());
		result = 37 * result + (getI12() == null ? 0 : this.getI12().hashCode());
		result = 37 * result + (getI13() == null ? 0 : this.getI13().hashCode());
		result = 37 * result + (getI21() == null ? 0 : this.getI21().hashCode());
		result = 37 * result + (getI22() == null ? 0 : this.getI22().hashCode());
		result = 37 * result + (getI23() == null ? 0 : this.getI23().hashCode());
		result = 37 * result + (getI31() == null ? 0 : this.getI31().hashCode());
		result = 37 * result + (getI32() == null ? 0 : this.getI32().hashCode());
		result = 37 * result + (getI33() == null ? 0 : this.getI33().hashCode());
		result = 37 * result + (getI41() == null ? 0 : this.getI41().hashCode());
		result = 37 * result + (getI42() == null ? 0 : this.getI42().hashCode());
		result = 37 * result + (getI43() == null ? 0 : this.getI43().hashCode());
		result = 37 * result + (getI51() == null ? 0 : this.getI51().hashCode());
		result = 37 * result + (getI52() == null ? 0 : this.getI52().hashCode());
		result = 37 * result + (getI53() == null ? 0 : this.getI53().hashCode());
		result = 37 * result + (getI61() == null ? 0 : this.getI61().hashCode());
		result = 37 * result + (getI62() == null ? 0 : this.getI62().hashCode());
		result = 37 * result + (getI63() == null ? 0 : this.getI63().hashCode());
		result = 37 * result + (getI71() == null ? 0 : this.getI71().hashCode());
		result = 37 * result + (getI72() == null ? 0 : this.getI72().hashCode());
		result = 37 * result + (getI73() == null ? 0 : this.getI73().hashCode());
		result = 37 * result + (getI81() == null ? 0 : this.getI81().hashCode());
		result = 37 * result + (getI82() == null ? 0 : this.getI82().hashCode());
		result = 37 * result + (getI83() == null ? 0 : this.getI83().hashCode());
		result = 37 * result + (getI91() == null ? 0 : this.getI91().hashCode());
		result = 37 * result + (getI92() == null ? 0 : this.getI92().hashCode());
		result = 37 * result + (getI93() == null ? 0 : this.getI93().hashCode());
		result = 37 * result + (getI101() == null ? 0 : this.getI101().hashCode());
		result = 37 * result + (getI102() == null ? 0 : this.getI102().hashCode());
		result = 37 * result + (getI103() == null ? 0 : this.getI103().hashCode());
		result = 37 * result + (getI111() == null ? 0 : this.getI111().hashCode());
		result = 37 * result + (getI112() == null ? 0 : this.getI112().hashCode());
		result = 37 * result + (getI113() == null ? 0 : this.getI113().hashCode());
		result = 37 * result + (getI121() == null ? 0 : this.getI121().hashCode());
		result = 37 * result + (getI122() == null ? 0 : this.getI122().hashCode());
		result = 37 * result + (getI123() == null ? 0 : this.getI123().hashCode());
		result = 37 * result + (getI131() == null ? 0 : this.getI131().hashCode());
		result = 37 * result + (getI132() == null ? 0 : this.getI132().hashCode());
		result = 37 * result + (getI133() == null ? 0 : this.getI133().hashCode());
		result = 37 * result + (getI141() == null ? 0 : this.getI141().hashCode());
		result = 37 * result + (getI142() == null ? 0 : this.getI142().hashCode());
		result = 37 * result + (getI143() == null ? 0 : this.getI143().hashCode());
		result = 37 * result + (getI151() == null ? 0 : this.getI151().hashCode());
		result = 37 * result + (getI152() == null ? 0 : this.getI152().hashCode());
		result = 37 * result + (getI153() == null ? 0 : this.getI153().hashCode());
		result = 37 * result + (getI161() == null ? 0 : this.getI161().hashCode());
		result = 37 * result + (getI162() == null ? 0 : this.getI162().hashCode());
		result = 37 * result + (getI163() == null ? 0 : this.getI163().hashCode());
		result = 37 * result + (getI171() == null ? 0 : this.getI171().hashCode());
		result = 37 * result + (getI172() == null ? 0 : this.getI172().hashCode());
		result = 37 * result + (getI173() == null ? 0 : this.getI173().hashCode());
		result = 37 * result + (getI181() == null ? 0 : this.getI181().hashCode());
		result = 37 * result + (getI182() == null ? 0 : this.getI182().hashCode());
		result = 37 * result + (getI183() == null ? 0 : this.getI183().hashCode());
		result = 37 * result + (getI191() == null ? 0 : this.getI191().hashCode());
		result = 37 * result + (getI192() == null ? 0 : this.getI192().hashCode());
		result = 37 * result + (getI193() == null ? 0 : this.getI193().hashCode());
		result = 37 * result + (getI201() == null ? 0 : this.getI201().hashCode());
		result = 37 * result + (getI202() == null ? 0 : this.getI202().hashCode());
		result = 37 * result + (getI203() == null ? 0 : this.getI203().hashCode());
		result = 37 * result + (getI211() == null ? 0 : this.getI211().hashCode());
		result = 37 * result + (getI212() == null ? 0 : this.getI212().hashCode());
		result = 37 * result + (getI213() == null ? 0 : this.getI213().hashCode());
		result = 37 * result + (getI221() == null ? 0 : this.getI221().hashCode());
		result = 37 * result + (getI222() == null ? 0 : this.getI222().hashCode());
		result = 37 * result + (getI223() == null ? 0 : this.getI223().hashCode());
		return result;
	}

}
