package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Deol generated by hbm2java
 */
public class Deol implements java.io.Serializable {

	private DeolId id;

	public Deol() {
	}

	public Deol(DeolId id) {
		this.id = id;
	}

	public DeolId getId() {
		return this.id;
	}

	public void setId(DeolId id) {
		this.id = id;
	}

}
