package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Doublewides generated by hbm2java
 */
public class Doublewides implements java.io.Serializable {

	private DoublewidesId id;

	public Doublewides() {
	}

	public Doublewides(DoublewidesId id) {
		this.id = id;
	}

	public DoublewidesId getId() {
		return this.id;
	}

	public void setId(DoublewidesId id) {
		this.id = id;
	}

}
