package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * DoublewidesId generated by hbm2java
 */
public class DoublewidesId implements java.io.Serializable {

	private int location;
	private String i1;
	private String i2;
	private String i3;
	private String i4;
	private String i5;
	private String i6;
	private String i7;
	private String i8;
	private String i9;
	private String i10;
	private String i11;
	private String i12;

	public DoublewidesId() {
	}

	public DoublewidesId(int location, String i1, String i2, String i3, String i4, String i5, String i6, String i7,
			String i8, String i9, String i10, String i11, String i12) {
		this.location = location;
		this.i1 = i1;
		this.i2 = i2;
		this.i3 = i3;
		this.i4 = i4;
		this.i5 = i5;
		this.i6 = i6;
		this.i7 = i7;
		this.i8 = i8;
		this.i9 = i9;
		this.i10 = i10;
		this.i11 = i11;
		this.i12 = i12;
	}

	public int getLocation() {
		return this.location;
	}

	public void setLocation(int location) {
		this.location = location;
	}

	public String getI1() {
		return this.i1;
	}

	public void setI1(String i1) {
		this.i1 = i1;
	}

	public String getI2() {
		return this.i2;
	}

	public void setI2(String i2) {
		this.i2 = i2;
	}

	public String getI3() {
		return this.i3;
	}

	public void setI3(String i3) {
		this.i3 = i3;
	}

	public String getI4() {
		return this.i4;
	}

	public void setI4(String i4) {
		this.i4 = i4;
	}

	public String getI5() {
		return this.i5;
	}

	public void setI5(String i5) {
		this.i5 = i5;
	}

	public String getI6() {
		return this.i6;
	}

	public void setI6(String i6) {
		this.i6 = i6;
	}

	public String getI7() {
		return this.i7;
	}

	public void setI7(String i7) {
		this.i7 = i7;
	}

	public String getI8() {
		return this.i8;
	}

	public void setI8(String i8) {
		this.i8 = i8;
	}

	public String getI9() {
		return this.i9;
	}

	public void setI9(String i9) {
		this.i9 = i9;
	}

	public String getI10() {
		return this.i10;
	}

	public void setI10(String i10) {
		this.i10 = i10;
	}

	public String getI11() {
		return this.i11;
	}

	public void setI11(String i11) {
		this.i11 = i11;
	}

	public String getI12() {
		return this.i12;
	}

	public void setI12(String i12) {
		this.i12 = i12;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DoublewidesId))
			return false;
		DoublewidesId castOther = (DoublewidesId) other;

		return (this.getLocation() == castOther.getLocation()) && ((this.getI1() == castOther.getI1())
				|| (this.getI1() != null && castOther.getI1() != null && this.getI1().equals(castOther.getI1())))
				&& ((this.getI2() == castOther.getI2()) || (this.getI2() != null && castOther.getI2() != null
						&& this.getI2().equals(castOther.getI2())))
				&& ((this.getI3() == castOther.getI3()) || (this.getI3() != null && castOther.getI3() != null
						&& this.getI3().equals(castOther.getI3())))
				&& ((this.getI4() == castOther.getI4()) || (this.getI4() != null && castOther.getI4() != null
						&& this.getI4().equals(castOther.getI4())))
				&& ((this.getI5() == castOther.getI5()) || (this.getI5() != null && castOther.getI5() != null
						&& this.getI5().equals(castOther.getI5())))
				&& ((this.getI6() == castOther.getI6()) || (this.getI6() != null && castOther.getI6() != null
						&& this.getI6().equals(castOther.getI6())))
				&& ((this.getI7() == castOther.getI7()) || (this.getI7() != null && castOther.getI7() != null
						&& this.getI7().equals(castOther.getI7())))
				&& ((this.getI8() == castOther.getI8()) || (this.getI8() != null && castOther.getI8() != null
						&& this.getI8().equals(castOther.getI8())))
				&& ((this.getI9() == castOther.getI9()) || (this.getI9() != null && castOther.getI9() != null
						&& this.getI9().equals(castOther.getI9())))
				&& ((this.getI10() == castOther.getI10()) || (this.getI10() != null && castOther.getI10() != null
						&& this.getI10().equals(castOther.getI10())))
				&& ((this.getI11() == castOther.getI11()) || (this.getI11() != null && castOther.getI11() != null
						&& this.getI11().equals(castOther.getI11())))
				&& ((this.getI12() == castOther.getI12()) || (this.getI12() != null && castOther.getI12() != null
						&& this.getI12().equals(castOther.getI12())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLocation();
		result = 37 * result + (getI1() == null ? 0 : this.getI1().hashCode());
		result = 37 * result + (getI2() == null ? 0 : this.getI2().hashCode());
		result = 37 * result + (getI3() == null ? 0 : this.getI3().hashCode());
		result = 37 * result + (getI4() == null ? 0 : this.getI4().hashCode());
		result = 37 * result + (getI5() == null ? 0 : this.getI5().hashCode());
		result = 37 * result + (getI6() == null ? 0 : this.getI6().hashCode());
		result = 37 * result + (getI7() == null ? 0 : this.getI7().hashCode());
		result = 37 * result + (getI8() == null ? 0 : this.getI8().hashCode());
		result = 37 * result + (getI9() == null ? 0 : this.getI9().hashCode());
		result = 37 * result + (getI10() == null ? 0 : this.getI10().hashCode());
		result = 37 * result + (getI11() == null ? 0 : this.getI11().hashCode());
		result = 37 * result + (getI12() == null ? 0 : this.getI12().hashCode());
		return result;
	}

}
