package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * EmployeesId generated by hbm2java
 */
public class EmployeesId implements java.io.Serializable {

	private int counter;
	private String fullName;
	private Boolean killFloor;

	public EmployeesId() {
	}

	public EmployeesId(int counter, String fullName) {
		this.counter = counter;
		this.fullName = fullName;
	}

	public EmployeesId(int counter, String fullName, Boolean killFloor) {
		this.counter = counter;
		this.fullName = fullName;
		this.killFloor = killFloor;
	}

	public int getCounter() {
		return this.counter;
	}

	public void setCounter(int counter) {
		this.counter = counter;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public Boolean getKillFloor() {
		return this.killFloor;
	}

	public void setKillFloor(Boolean killFloor) {
		this.killFloor = killFloor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmployeesId))
			return false;
		EmployeesId castOther = (EmployeesId) other;

		return (this.getCounter() == castOther.getCounter())
				&& ((this.getFullName() == castOther.getFullName()) || (this.getFullName() != null
						&& castOther.getFullName() != null && this.getFullName().equals(castOther.getFullName())))
				&& ((this.getKillFloor() == castOther.getKillFloor()) || (this.getKillFloor() != null
						&& castOther.getKillFloor() != null && this.getKillFloor().equals(castOther.getKillFloor())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCounter();
		result = 37 * result + (getFullName() == null ? 0 : this.getFullName().hashCode());
		result = 37 * result + (getKillFloor() == null ? 0 : this.getKillFloor().hashCode());
		return result;
	}

}
