package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Employees generated by hbm2java
 */
public class Employees implements java.io.Serializable {

	private EmployeesId id;

	public Employees() {
	}

	public Employees(EmployeesId id) {
		this.id = id;
	}

	public EmployeesId getId() {
		return this.id;
	}

	public void setId(EmployeesId id) {
		this.id = id;
	}

}
