package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * European generated by hbm2java
 */
public class European implements java.io.Serializable {

	private EuropeanId id;

	public European() {
	}

	public European(EuropeanId id) {
		this.id = id;
	}

	public EuropeanId getId() {
		return this.id;
	}

	public void setId(EuropeanId id) {
		this.id = id;
	}

}
