package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Flocations generated by hbm2java
 */
public class Flocations implements java.io.Serializable {

	private FlocationsId id;

	public Flocations() {
	}

	public Flocations(FlocationsId id) {
		this.id = id;
	}

	public FlocationsId getId() {
		return this.id;
	}

	public void setId(FlocationsId id) {
		this.id = id;
	}

}
