package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Pkgcount generated by hbm2java
 */
public class Pkgcount implements java.io.Serializable {

	private Integer counter;
	private int animalId;
	private int count;
	private String primal;

	public Pkgcount() {
	}

	public Pkgcount(int animalId, int count, String primal) {
		this.animalId = animalId;
		this.count = count;
		this.primal = primal;
	}

	public Integer getCounter() {
		return this.counter;
	}

	public void setCounter(Integer counter) {
		this.counter = counter;
	}

	public int getAnimalId() {
		return this.animalId;
	}

	public void setAnimalId(int animalId) {
		this.animalId = animalId;
	}

	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	public String getPrimal() {
		return this.primal;
	}

	public void setPrimal(String primal) {
		this.primal = primal;
	}

}
