package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Plu generated by hbm2java
 */
public class Plu implements java.io.Serializable {

	private PluId id;

	public Plu() {
	}

	public Plu(PluId id) {
		this.id = id;
	}

	public PluId getId() {
		return this.id;
	}

	public void setId(PluId id) {
		this.id = id;
	}

}
