package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * PluId generated by hbm2java
 */
public class PluId implements java.io.Serializable {

	private String catagory;
	private String subCat;
	private Short plu;
	private String description;

	public PluId() {
	}

	public PluId(String catagory, String subCat, Short plu, String description) {
		this.catagory = catagory;
		this.subCat = subCat;
		this.plu = plu;
		this.description = description;
	}

	public String getCatagory() {
		return this.catagory;
	}

	public void setCatagory(String catagory) {
		this.catagory = catagory;
	}

	public String getSubCat() {
		return this.subCat;
	}

	public void setSubCat(String subCat) {
		this.subCat = subCat;
	}

	public Short getPlu() {
		return this.plu;
	}

	public void setPlu(Short plu) {
		this.plu = plu;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PluId))
			return false;
		PluId castOther = (PluId) other;

		return ((this.getCatagory() == castOther.getCatagory()) || (this.getCatagory() != null
				&& castOther.getCatagory() != null && this.getCatagory().equals(castOther.getCatagory())))
				&& ((this.getSubCat() == castOther.getSubCat()) || (this.getSubCat() != null
						&& castOther.getSubCat() != null && this.getSubCat().equals(castOther.getSubCat())))
				&& ((this.getPlu() == castOther.getPlu()) || (this.getPlu() != null && castOther.getPlu() != null
						&& this.getPlu().equals(castOther.getPlu())))
				&& ((this.getDescription() == castOther.getDescription())
						|| (this.getDescription() != null && castOther.getDescription() != null
								&& this.getDescription().equals(castOther.getDescription())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCatagory() == null ? 0 : this.getCatagory().hashCode());
		result = 37 * result + (getSubCat() == null ? 0 : this.getSubCat().hashCode());
		result = 37 * result + (getPlu() == null ? 0 : this.getPlu().hashCode());
		result = 37 * result + (getDescription() == null ? 0 : this.getDescription().hashCode());
		return result;
	}

}
