package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Porkdw generated by hbm2java
 */
public class Porkdw implements java.io.Serializable {

	private PorkdwId id;

	public Porkdw() {
	}

	public Porkdw(PorkdwId id) {
		this.id = id;
	}

	public PorkdwId getId() {
		return this.id;
	}

	public void setId(PorkdwId id) {
		this.id = id;
	}

}
