package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Porks1 generated by hbm2java
 */
public class Porks1 implements java.io.Serializable {

	private Porks1Id id;

	public Porks1() {
	}

	public Porks1(Porks1Id id) {
		this.id = id;
	}

	public Porks1Id getId() {
		return this.id;
	}

	public void setId(Porks1Id id) {
		this.id = id;
	}

}
