package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Porks generated by hbm2java
 */
public class Porks implements java.io.Serializable {

	private PorksId id;

	public Porks() {
	}

	public Porks(PorksId id) {
		this.id = id;
	}

	public PorksId getId() {
		return this.id;
	}

	public void setId(PorksId id) {
		this.id = id;
	}

}
