package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Porkcarts generated by hbm2java
 */
public class Porkcarts implements java.io.Serializable {

	private PorkcartsId id;

	public Porkcarts() {
	}

	public Porkcarts(PorkcartsId id) {
		this.id = id;
	}

	public PorkcartsId getId() {
		return this.id;
	}

	public void setId(PorkcartsId id) {
		this.id = id;
	}

}
