package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Primal generated by hbm2java
 */
public class Primal implements java.io.Serializable {

	private PrimalId id;

	public Primal() {
	}

	public Primal(PrimalId id) {
		this.id = id;
	}

	public PrimalId getId() {
		return this.id;
	}

	public void setId(PrimalId id) {
		this.id = id;
	}

}
