package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Qf generated by hbm2java
 */
public class Qf implements java.io.Serializable {

	private QfId id;

	public Qf() {
	}

	public Qf(QfId id) {
		this.id = id;
	}

	public QfId getId() {
		return this.id;
	}

	public void setId(QfId id) {
		this.id = id;
	}

}
