package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * QfId generated by hbm2java
 */
public class QfId implements java.io.Serializable {

	private String i1;
	private String i2;
	private String i3;
	private String i4;
	private String i5;
	private String i6;
	private String i7;
	private String i8;
	private String i9;
	private String i10;
	private String i11;
	private String i12;
	private String i13;
	private String i14;
	private String i15;
	private String i16;
	private String i17;
	private String i18;
	private String i19;
	private String i20;
	private String i21;
	private String i22;
	private String i23;
	private String i24;
	private String i25;
	private String i26;
	private String i27;

	public QfId() {
	}

	public QfId(String i1, String i2, String i3, String i4, String i5, String i6, String i7, String i8, String i9,
			String i10, String i11, String i12, String i13, String i14, String i15, String i16, String i17, String i18,
			String i19, String i20, String i21, String i22, String i23, String i24, String i25, String i26,
			String i27) {
		this.i1 = i1;
		this.i2 = i2;
		this.i3 = i3;
		this.i4 = i4;
		this.i5 = i5;
		this.i6 = i6;
		this.i7 = i7;
		this.i8 = i8;
		this.i9 = i9;
		this.i10 = i10;
		this.i11 = i11;
		this.i12 = i12;
		this.i13 = i13;
		this.i14 = i14;
		this.i15 = i15;
		this.i16 = i16;
		this.i17 = i17;
		this.i18 = i18;
		this.i19 = i19;
		this.i20 = i20;
		this.i21 = i21;
		this.i22 = i22;
		this.i23 = i23;
		this.i24 = i24;
		this.i25 = i25;
		this.i26 = i26;
		this.i27 = i27;
	}

	public String getI1() {
		return this.i1;
	}

	public void setI1(String i1) {
		this.i1 = i1;
	}

	public String getI2() {
		return this.i2;
	}

	public void setI2(String i2) {
		this.i2 = i2;
	}

	public String getI3() {
		return this.i3;
	}

	public void setI3(String i3) {
		this.i3 = i3;
	}

	public String getI4() {
		return this.i4;
	}

	public void setI4(String i4) {
		this.i4 = i4;
	}

	public String getI5() {
		return this.i5;
	}

	public void setI5(String i5) {
		this.i5 = i5;
	}

	public String getI6() {
		return this.i6;
	}

	public void setI6(String i6) {
		this.i6 = i6;
	}

	public String getI7() {
		return this.i7;
	}

	public void setI7(String i7) {
		this.i7 = i7;
	}

	public String getI8() {
		return this.i8;
	}

	public void setI8(String i8) {
		this.i8 = i8;
	}

	public String getI9() {
		return this.i9;
	}

	public void setI9(String i9) {
		this.i9 = i9;
	}

	public String getI10() {
		return this.i10;
	}

	public void setI10(String i10) {
		this.i10 = i10;
	}

	public String getI11() {
		return this.i11;
	}

	public void setI11(String i11) {
		this.i11 = i11;
	}

	public String getI12() {
		return this.i12;
	}

	public void setI12(String i12) {
		this.i12 = i12;
	}

	public String getI13() {
		return this.i13;
	}

	public void setI13(String i13) {
		this.i13 = i13;
	}

	public String getI14() {
		return this.i14;
	}

	public void setI14(String i14) {
		this.i14 = i14;
	}

	public String getI15() {
		return this.i15;
	}

	public void setI15(String i15) {
		this.i15 = i15;
	}

	public String getI16() {
		return this.i16;
	}

	public void setI16(String i16) {
		this.i16 = i16;
	}

	public String getI17() {
		return this.i17;
	}

	public void setI17(String i17) {
		this.i17 = i17;
	}

	public String getI18() {
		return this.i18;
	}

	public void setI18(String i18) {
		this.i18 = i18;
	}

	public String getI19() {
		return this.i19;
	}

	public void setI19(String i19) {
		this.i19 = i19;
	}

	public String getI20() {
		return this.i20;
	}

	public void setI20(String i20) {
		this.i20 = i20;
	}

	public String getI21() {
		return this.i21;
	}

	public void setI21(String i21) {
		this.i21 = i21;
	}

	public String getI22() {
		return this.i22;
	}

	public void setI22(String i22) {
		this.i22 = i22;
	}

	public String getI23() {
		return this.i23;
	}

	public void setI23(String i23) {
		this.i23 = i23;
	}

	public String getI24() {
		return this.i24;
	}

	public void setI24(String i24) {
		this.i24 = i24;
	}

	public String getI25() {
		return this.i25;
	}

	public void setI25(String i25) {
		this.i25 = i25;
	}

	public String getI26() {
		return this.i26;
	}

	public void setI26(String i26) {
		this.i26 = i26;
	}

	public String getI27() {
		return this.i27;
	}

	public void setI27(String i27) {
		this.i27 = i27;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof QfId))
			return false;
		QfId castOther = (QfId) other;

		return ((this.getI1() == castOther.getI1())
				|| (this.getI1() != null && castOther.getI1() != null && this.getI1().equals(castOther.getI1())))
				&& ((this.getI2() == castOther.getI2()) || (this.getI2() != null && castOther.getI2() != null
						&& this.getI2().equals(castOther.getI2())))
				&& ((this.getI3() == castOther.getI3()) || (this.getI3() != null && castOther.getI3() != null
						&& this.getI3().equals(castOther.getI3())))
				&& ((this.getI4() == castOther.getI4()) || (this.getI4() != null && castOther.getI4() != null
						&& this.getI4().equals(castOther.getI4())))
				&& ((this.getI5() == castOther.getI5()) || (this.getI5() != null && castOther.getI5() != null
						&& this.getI5().equals(castOther.getI5())))
				&& ((this.getI6() == castOther.getI6()) || (this.getI6() != null && castOther.getI6() != null
						&& this.getI6().equals(castOther.getI6())))
				&& ((this.getI7() == castOther.getI7()) || (this.getI7() != null && castOther.getI7() != null
						&& this.getI7().equals(castOther.getI7())))
				&& ((this.getI8() == castOther.getI8()) || (this.getI8() != null && castOther.getI8() != null
						&& this.getI8().equals(castOther.getI8())))
				&& ((this.getI9() == castOther.getI9()) || (this.getI9() != null && castOther.getI9() != null
						&& this.getI9().equals(castOther.getI9())))
				&& ((this.getI10() == castOther.getI10()) || (this.getI10() != null && castOther.getI10() != null
						&& this.getI10().equals(castOther.getI10())))
				&& ((this.getI11() == castOther.getI11()) || (this.getI11() != null && castOther.getI11() != null
						&& this.getI11().equals(castOther.getI11())))
				&& ((this.getI12() == castOther.getI12()) || (this.getI12() != null && castOther.getI12() != null
						&& this.getI12().equals(castOther.getI12())))
				&& ((this.getI13() == castOther.getI13()) || (this.getI13() != null && castOther.getI13() != null
						&& this.getI13().equals(castOther.getI13())))
				&& ((this.getI14() == castOther.getI14()) || (this.getI14() != null && castOther.getI14() != null
						&& this.getI14().equals(castOther.getI14())))
				&& ((this.getI15() == castOther.getI15()) || (this.getI15() != null && castOther.getI15() != null
						&& this.getI15().equals(castOther.getI15())))
				&& ((this.getI16() == castOther.getI16()) || (this.getI16() != null && castOther.getI16() != null
						&& this.getI16().equals(castOther.getI16())))
				&& ((this.getI17() == castOther.getI17()) || (this.getI17() != null && castOther.getI17() != null
						&& this.getI17().equals(castOther.getI17())))
				&& ((this.getI18() == castOther.getI18()) || (this.getI18() != null && castOther.getI18() != null
						&& this.getI18().equals(castOther.getI18())))
				&& ((this.getI19() == castOther.getI19()) || (this.getI19() != null && castOther.getI19() != null
						&& this.getI19().equals(castOther.getI19())))
				&& ((this.getI20() == castOther.getI20()) || (this.getI20() != null && castOther.getI20() != null
						&& this.getI20().equals(castOther.getI20())))
				&& ((this.getI21() == castOther.getI21()) || (this.getI21() != null && castOther.getI21() != null
						&& this.getI21().equals(castOther.getI21())))
				&& ((this.getI22() == castOther.getI22()) || (this.getI22() != null && castOther.getI22() != null
						&& this.getI22().equals(castOther.getI22())))
				&& ((this.getI23() == castOther.getI23()) || (this.getI23() != null && castOther.getI23() != null
						&& this.getI23().equals(castOther.getI23())))
				&& ((this.getI24() == castOther.getI24()) || (this.getI24() != null && castOther.getI24() != null
						&& this.getI24().equals(castOther.getI24())))
				&& ((this.getI25() == castOther.getI25()) || (this.getI25() != null && castOther.getI25() != null
						&& this.getI25().equals(castOther.getI25())))
				&& ((this.getI26() == castOther.getI26()) || (this.getI26() != null && castOther.getI26() != null
						&& this.getI26().equals(castOther.getI26())))
				&& ((this.getI27() == castOther.getI27()) || (this.getI27() != null && castOther.getI27() != null
						&& this.getI27().equals(castOther.getI27())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getI1() == null ? 0 : this.getI1().hashCode());
		result = 37 * result + (getI2() == null ? 0 : this.getI2().hashCode());
		result = 37 * result + (getI3() == null ? 0 : this.getI3().hashCode());
		result = 37 * result + (getI4() == null ? 0 : this.getI4().hashCode());
		result = 37 * result + (getI5() == null ? 0 : this.getI5().hashCode());
		result = 37 * result + (getI6() == null ? 0 : this.getI6().hashCode());
		result = 37 * result + (getI7() == null ? 0 : this.getI7().hashCode());
		result = 37 * result + (getI8() == null ? 0 : this.getI8().hashCode());
		result = 37 * result + (getI9() == null ? 0 : this.getI9().hashCode());
		result = 37 * result + (getI10() == null ? 0 : this.getI10().hashCode());
		result = 37 * result + (getI11() == null ? 0 : this.getI11().hashCode());
		result = 37 * result + (getI12() == null ? 0 : this.getI12().hashCode());
		result = 37 * result + (getI13() == null ? 0 : this.getI13().hashCode());
		result = 37 * result + (getI14() == null ? 0 : this.getI14().hashCode());
		result = 37 * result + (getI15() == null ? 0 : this.getI15().hashCode());
		result = 37 * result + (getI16() == null ? 0 : this.getI16().hashCode());
		result = 37 * result + (getI17() == null ? 0 : this.getI17().hashCode());
		result = 37 * result + (getI18() == null ? 0 : this.getI18().hashCode());
		result = 37 * result + (getI19() == null ? 0 : this.getI19().hashCode());
		result = 37 * result + (getI20() == null ? 0 : this.getI20().hashCode());
		result = 37 * result + (getI21() == null ? 0 : this.getI21().hashCode());
		result = 37 * result + (getI22() == null ? 0 : this.getI22().hashCode());
		result = 37 * result + (getI23() == null ? 0 : this.getI23().hashCode());
		result = 37 * result + (getI24() == null ? 0 : this.getI24().hashCode());
		result = 37 * result + (getI25() == null ? 0 : this.getI25().hashCode());
		result = 37 * result + (getI26() == null ? 0 : this.getI26().hashCode());
		result = 37 * result + (getI27() == null ? 0 : this.getI27().hashCode());
		return result;
	}

}
