package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Quickfreeze generated by hbm2java
 */
public class Quickfreeze implements java.io.Serializable {

	private QuickfreezeId id;

	public Quickfreeze() {
	}

	public Quickfreeze(QuickfreezeId id) {
		this.id = id;
	}

	public QuickfreezeId getId() {
		return this.id;
	}

	public void setId(QuickfreezeId id) {
		this.id = id;
	}

}
