package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Species generated by hbm2java
 */
public class Species implements java.io.Serializable {

	private SpeciesId id;

	public Species() {
	}

	public Species(SpeciesId id) {
		this.id = id;
	}

	public SpeciesId getId() {
		return this.id;
	}

	public void setId(SpeciesId id) {
		this.id = id;
	}

}
