package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Timepunchesold generated by hbm2java
 */
public class Timepunchesold implements java.io.Serializable {

	private TimepunchesoldId id;

	public Timepunchesold() {
	}

	public Timepunchesold(TimepunchesoldId id) {
		this.id = id;
	}

	public TimepunchesoldId getId() {
		return this.id;
	}

	public void setId(TimepunchesoldId id) {
		this.id = id;
	}

}
