package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;

/**
 * Timesheet generated by hbm2java
 */
public class Timesheet implements java.io.Serializable {

	private int counter;
	private String fullName;
	private Date starting;
	private Double regHours;
	private Double othours;
	private String holiday;
	private Double holidayHours;
	private Boolean pulled;

	public Timesheet() {
	}

	public Timesheet(int counter, String fullName, Date starting, String holiday) {
		this.counter = counter;
		this.fullName = fullName;
		this.starting = starting;
		this.holiday = holiday;
	}

	public Timesheet(int counter, String fullName, Date starting, Double regHours, Double othours, String holiday,
			Double holidayHours, Boolean pulled) {
		this.counter = counter;
		this.fullName = fullName;
		this.starting = starting;
		this.regHours = regHours;
		this.othours = othours;
		this.holiday = holiday;
		this.holidayHours = holidayHours;
		this.pulled = pulled;
	}

	public int getCounter() {
		return this.counter;
	}

	public void setCounter(int counter) {
		this.counter = counter;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public Date getStarting() {
		return this.starting;
	}

	public void setStarting(Date starting) {
		this.starting = starting;
	}

	public Double getRegHours() {
		return this.regHours;
	}

	public void setRegHours(Double regHours) {
		this.regHours = regHours;
	}

	public Double getOthours() {
		return this.othours;
	}

	public void setOthours(Double othours) {
		this.othours = othours;
	}

	public String getHoliday() {
		return this.holiday;
	}

	public void setHoliday(String holiday) {
		this.holiday = holiday;
	}

	public Double getHolidayHours() {
		return this.holidayHours;
	}

	public void setHolidayHours(Double holidayHours) {
		this.holidayHours = holidayHours;
	}

	public Boolean getPulled() {
		return this.pulled;
	}

	public void setPulled(Boolean pulled) {
		this.pulled = pulled;
	}

}
