package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Timepunches generated by hbm2java
 */
public class Timepunches implements java.io.Serializable {

	private TimepunchesId id;

	public Timepunches() {
	}

	public Timepunches(TimepunchesId id) {
		this.id = id;
	}

	public TimepunchesId getId() {
		return this.id;
	}

	public void setId(TimepunchesId id) {
		this.id = id;
	}

}
