package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;

/**
 * Timenotes generated by hbm2java
 */
public class Timenotes implements java.io.Serializable {

	private Integer counter;
	private String employee;
	private int remind;
	private String note;
	private Date startDate;
	private Date endDate;

	public Timenotes() {
	}

	public Timenotes(String employee, int remind, String note) {
		this.employee = employee;
		this.remind = remind;
		this.note = note;
	}

	public Timenotes(String employee, int remind, String note, Date startDate, Date endDate) {
		this.employee = employee;
		this.remind = remind;
		this.note = note;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	public Integer getCounter() {
		return this.counter;
	}

	public void setCounter(Integer counter) {
		this.counter = counter;
	}

	public String getEmployee() {
		return this.employee;
	}

	public void setEmployee(String employee) {
		this.employee = employee;
	}

	public int getRemind() {
		return this.remind;
	}

	public void setRemind(int remind) {
		this.remind = remind;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
