package freezer.schema.model;
// Generated Feb 17, 2018 3:45:47 PM by Hibernate Tools 5.2.8.Final

/**
 * Usda generated by hbm2java
 */
public class Usda implements java.io.Serializable {

	private UsdaId id;

	public Usda() {
	}

	public Usda(UsdaId id) {
		this.id = id;
	}

	public UsdaId getId() {
		return this.id;
	}

	public void setId(UsdaId id) {
		this.id = id;
	}

}
