package archieverecords.schema.model;
// Generated Feb 17, 2018 4:24:52 PM by Hibernate Tools 5.2.8.Final

/**
 * Archieve generated by hbm2java
 */
public class Archieve implements java.io.Serializable {

	private ArchieveId id;

	public Archieve() {
	}

	public Archieve(ArchieveId id) {
		this.id = id;
	}

	public ArchieveId getId() {
		return this.id;
	}

	public void setId(ArchieveId id) {
		this.id = id;
	}

}
