package archieverecords.schema.model;
// Generated Feb 17, 2018 4:24:52 PM by Hibernate Tools 5.2.8.Final

/**
 * Billing generated by hbm2java
 */
public class Billing implements java.io.Serializable {

	private BillingId id;

	public Billing() {
	}

	public Billing(BillingId id) {
		this.id = id;
	}

	public BillingId getId() {
		return this.id;
	}

	public void setId(BillingId id) {
		this.id = id;
	}

}
