package archieverecords.schema.model;
// Generated Feb 17, 2018 4:24:52 PM by Hibernate Tools 5.2.8.Final

/**
 * CashReportSheet generated by hbm2java
 */
public class CashReportSheet implements java.io.Serializable {

	private CashReportSheetId id;

	public CashReportSheet() {
	}

	public CashReportSheet(CashReportSheetId id) {
		this.id = id;
	}

	public CashReportSheetId getId() {
		return this.id;
	}

	public void setId(CashReportSheetId id) {
		this.id = id;
	}

}
