package archieverecords.schema.model;
// Generated Feb 17, 2018 4:24:52 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;

/**
 * CuringjournalId generated by hbm2java
 */
public class CuringjournalId implements java.io.Serializable {

	private String animalId;
	private int hams;
	private int bacons;
	private int ark;
	private int shoulders;
	private int loins;
	private int ribs;
	private boolean hocksYn;
	private int hocks;
	private int jowl;
	private Integer begin;
	private Integer end;
	private Double weight;
	private String otherName;
	private int otherCount;
	private Date deliveryDate;

	public CuringjournalId() {
	}

	public CuringjournalId(String animalId, int hams, int bacons, int ark, int shoulders, int loins, int ribs,
			boolean hocksYn, int hocks, int jowl, int otherCount, Date deliveryDate) {
		this.animalId = animalId;
		this.hams = hams;
		this.bacons = bacons;
		this.ark = ark;
		this.shoulders = shoulders;
		this.loins = loins;
		this.ribs = ribs;
		this.hocksYn = hocksYn;
		this.hocks = hocks;
		this.jowl = jowl;
		this.otherCount = otherCount;
		this.deliveryDate = deliveryDate;
	}

	public CuringjournalId(String animalId, int hams, int bacons, int ark, int shoulders, int loins, int ribs,
			boolean hocksYn, int hocks, int jowl, Integer begin, Integer end, Double weight, String otherName,
			int otherCount, Date deliveryDate) {
		this.animalId = animalId;
		this.hams = hams;
		this.bacons = bacons;
		this.ark = ark;
		this.shoulders = shoulders;
		this.loins = loins;
		this.ribs = ribs;
		this.hocksYn = hocksYn;
		this.hocks = hocks;
		this.jowl = jowl;
		this.begin = begin;
		this.end = end;
		this.weight = weight;
		this.otherName = otherName;
		this.otherCount = otherCount;
		this.deliveryDate = deliveryDate;
	}

	public String getAnimalId() {
		return this.animalId;
	}

	public void setAnimalId(String animalId) {
		this.animalId = animalId;
	}

	public int getHams() {
		return this.hams;
	}

	public void setHams(int hams) {
		this.hams = hams;
	}

	public int getBacons() {
		return this.bacons;
	}

	public void setBacons(int bacons) {
		this.bacons = bacons;
	}

	public int getArk() {
		return this.ark;
	}

	public void setArk(int ark) {
		this.ark = ark;
	}

	public int getShoulders() {
		return this.shoulders;
	}

	public void setShoulders(int shoulders) {
		this.shoulders = shoulders;
	}

	public int getLoins() {
		return this.loins;
	}

	public void setLoins(int loins) {
		this.loins = loins;
	}

	public int getRibs() {
		return this.ribs;
	}

	public void setRibs(int ribs) {
		this.ribs = ribs;
	}

	public boolean isHocksYn() {
		return this.hocksYn;
	}

	public void setHocksYn(boolean hocksYn) {
		this.hocksYn = hocksYn;
	}

	public int getHocks() {
		return this.hocks;
	}

	public void setHocks(int hocks) {
		this.hocks = hocks;
	}

	public int getJowl() {
		return this.jowl;
	}

	public void setJowl(int jowl) {
		this.jowl = jowl;
	}

	public Integer getBegin() {
		return this.begin;
	}

	public void setBegin(Integer begin) {
		this.begin = begin;
	}

	public Integer getEnd() {
		return this.end;
	}

	public void setEnd(Integer end) {
		this.end = end;
	}

	public Double getWeight() {
		return this.weight;
	}

	public void setWeight(Double weight) {
		this.weight = weight;
	}

	public String getOtherName() {
		return this.otherName;
	}

	public void setOtherName(String otherName) {
		this.otherName = otherName;
	}

	public int getOtherCount() {
		return this.otherCount;
	}

	public void setOtherCount(int otherCount) {
		this.otherCount = otherCount;
	}

	public Date getDeliveryDate() {
		return this.deliveryDate;
	}

	public void setDeliveryDate(Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CuringjournalId))
			return false;
		CuringjournalId castOther = (CuringjournalId) other;

		return ((this.getAnimalId() == castOther.getAnimalId()) || (this.getAnimalId() != null
				&& castOther.getAnimalId() != null && this.getAnimalId().equals(castOther.getAnimalId())))
				&& (this.getHams() == castOther.getHams()) && (this.getBacons() == castOther.getBacons())
				&& (this.getArk() == castOther.getArk()) && (this.getShoulders() == castOther.getShoulders())
				&& (this.getLoins() == castOther.getLoins()) && (this.getRibs() == castOther.getRibs())
				&& (this.isHocksYn() == castOther.isHocksYn()) && (this.getHocks() == castOther.getHocks())
				&& (this.getJowl() == castOther.getJowl())
				&& ((this.getBegin() == castOther.getBegin()) || (this.getBegin() != null
						&& castOther.getBegin() != null && this.getBegin().equals(castOther.getBegin())))
				&& ((this.getEnd() == castOther.getEnd()) || (this.getEnd() != null && castOther.getEnd() != null
						&& this.getEnd().equals(castOther.getEnd())))
				&& ((this.getWeight() == castOther.getWeight()) || (this.getWeight() != null
						&& castOther.getWeight() != null && this.getWeight().equals(castOther.getWeight())))
				&& ((this.getOtherName() == castOther.getOtherName()) || (this.getOtherName() != null
						&& castOther.getOtherName() != null && this.getOtherName().equals(castOther.getOtherName())))
				&& (this.getOtherCount() == castOther.getOtherCount())
				&& ((this.getDeliveryDate() == castOther.getDeliveryDate())
						|| (this.getDeliveryDate() != null && castOther.getDeliveryDate() != null
								&& this.getDeliveryDate().equals(castOther.getDeliveryDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAnimalId() == null ? 0 : this.getAnimalId().hashCode());
		result = 37 * result + this.getHams();
		result = 37 * result + this.getBacons();
		result = 37 * result + this.getArk();
		result = 37 * result + this.getShoulders();
		result = 37 * result + this.getLoins();
		result = 37 * result + this.getRibs();
		result = 37 * result + (this.isHocksYn() ? 1 : 0);
		result = 37 * result + this.getHocks();
		result = 37 * result + this.getJowl();
		result = 37 * result + (getBegin() == null ? 0 : this.getBegin().hashCode());
		result = 37 * result + (getEnd() == null ? 0 : this.getEnd().hashCode());
		result = 37 * result + (getWeight() == null ? 0 : this.getWeight().hashCode());
		result = 37 * result + (getOtherName() == null ? 0 : this.getOtherName().hashCode());
		result = 37 * result + this.getOtherCount();
		result = 37 * result + (getDeliveryDate() == null ? 0 : this.getDeliveryDate().hashCode());
		return result;
	}

}
