package archieverecords.schema.model;
// Generated Feb 17, 2018 4:24:52 PM by Hibernate Tools 5.2.8.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * HidesId generated by hbm2java
 */
public class HidesId implements java.io.Serializable {

	private Date date;
	private Double poundSign;
	private BigDecimal amount;
	private boolean salt;
	private BigDecimal saltAmount;
	private Float lastId;
	private Boolean zed;

	public HidesId() {
	}

	public HidesId(boolean salt) {
		this.salt = salt;
	}

	public HidesId(Date date, Double poundSign, BigDecimal amount, boolean salt, BigDecimal saltAmount, Float lastId,
			Boolean zed) {
		this.date = date;
		this.poundSign = poundSign;
		this.amount = amount;
		this.salt = salt;
		this.saltAmount = saltAmount;
		this.lastId = lastId;
		this.zed = zed;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Double getPoundSign() {
		return this.poundSign;
	}

	public void setPoundSign(Double poundSign) {
		this.poundSign = poundSign;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public boolean isSalt() {
		return this.salt;
	}

	public void setSalt(boolean salt) {
		this.salt = salt;
	}

	public BigDecimal getSaltAmount() {
		return this.saltAmount;
	}

	public void setSaltAmount(BigDecimal saltAmount) {
		this.saltAmount = saltAmount;
	}

	public Float getLastId() {
		return this.lastId;
	}

	public void setLastId(Float lastId) {
		this.lastId = lastId;
	}

	public Boolean getZed() {
		return this.zed;
	}

	public void setZed(Boolean zed) {
		this.zed = zed;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HidesId))
			return false;
		HidesId castOther = (HidesId) other;

		return ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
				&& this.getDate().equals(castOther.getDate())))
				&& ((this.getPoundSign() == castOther.getPoundSign()) || (this.getPoundSign() != null
						&& castOther.getPoundSign() != null && this.getPoundSign().equals(castOther.getPoundSign())))
				&& ((this.getAmount() == castOther.getAmount()) || (this.getAmount() != null
						&& castOther.getAmount() != null && this.getAmount().equals(castOther.getAmount())))
				&& (this.isSalt() == castOther.isSalt())
				&& ((this.getSaltAmount() == castOther.getSaltAmount()) || (this.getSaltAmount() != null
						&& castOther.getSaltAmount() != null && this.getSaltAmount().equals(castOther.getSaltAmount())))
				&& ((this.getLastId() == castOther.getLastId()) || (this.getLastId() != null
						&& castOther.getLastId() != null && this.getLastId().equals(castOther.getLastId())))
				&& ((this.getZed() == castOther.getZed()) || (this.getZed() != null && castOther.getZed() != null
						&& this.getZed().equals(castOther.getZed())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result + (getPoundSign() == null ? 0 : this.getPoundSign().hashCode());
		result = 37 * result + (getAmount() == null ? 0 : this.getAmount().hashCode());
		result = 37 * result + (this.isSalt() ? 1 : 0);
		result = 37 * result + (getSaltAmount() == null ? 0 : this.getSaltAmount().hashCode());
		result = 37 * result + (getLastId() == null ? 0 : this.getLastId().hashCode());
		result = 37 * result + (getZed() == null ? 0 : this.getZed().hashCode());
		return result;
	}

}
