package archieverecords.schema.model;
// Generated Feb 17, 2018 4:24:52 PM by Hibernate Tools 5.2.8.Final

/**
 * Hides generated by hbm2java
 */
public class Hides implements java.io.Serializable {

	private HidesId id;

	public Hides() {
	}

	public Hides(HidesId id) {
		this.id = id;
	}

	public HidesId getId() {
		return this.id;
	}

	public void setId(HidesId id) {
		this.id = id;
	}

}
