package archieverecords.schema.model;
// Generated Feb 17, 2018 4:24:52 PM by Hibernate Tools 5.2.8.Final

/**
 * Sausage generated by hbm2java
 */
public class Sausage implements java.io.Serializable {

	private SausageId id;

	public Sausage() {
	}

	public Sausage(SausageId id) {
		this.id = id;
	}

	public SausageId getId() {
		return this.id;
	}

	public void setId(SausageId id) {
		this.id = id;
	}

}
