package archieverecords.schema.model;
// Generated Feb 17, 2018 4:24:52 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;

/**
 * XactionsId generated by hbm2java
 */
public class XactionsId implements java.io.Serializable {

	private int counter;
	private Date date;
	private Date time;
	private String species;
	private Float meatSales;
	private Float tax;
	private Float nontax;
	private Float lockerRent;
	private Float curing;
	private Float processing;
	private Float pprocessing;
	private Float dprocessing;
	private Float other;
	private Float total;
	private String method;
	private Float amount;
	private Float change;
	private boolean zzed;
	private String name;
	private Double multi;
	private Double TransationNumber;

	public XactionsId() {
	}

	public XactionsId(int counter, boolean zzed) {
		this.counter = counter;
		this.zzed = zzed;
	}

	public XactionsId(int counter, Date date, Date time, String species, Float meatSales, Float tax, Float nontax,
			Float lockerRent, Float curing, Float processing, Float pprocessing, Float dprocessing, Float other,
			Float total, String method, Float amount, Float change, boolean zzed, String name, Double multi,
			Double TransationNumber) {
		this.counter = counter;
		this.date = date;
		this.time = time;
		this.species = species;
		this.meatSales = meatSales;
		this.tax = tax;
		this.nontax = nontax;
		this.lockerRent = lockerRent;
		this.curing = curing;
		this.processing = processing;
		this.pprocessing = pprocessing;
		this.dprocessing = dprocessing;
		this.other = other;
		this.total = total;
		this.method = method;
		this.amount = amount;
		this.change = change;
		this.zzed = zzed;
		this.name = name;
		this.multi = multi;
		this.TransationNumber = TransationNumber;
	}

	public int getCounter() {
		return this.counter;
	}

	public void setCounter(int counter) {
		this.counter = counter;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getSpecies() {
		return this.species;
	}

	public void setSpecies(String species) {
		this.species = species;
	}

	public Float getMeatSales() {
		return this.meatSales;
	}

	public void setMeatSales(Float meatSales) {
		this.meatSales = meatSales;
	}

	public Float getTax() {
		return this.tax;
	}

	public void setTax(Float tax) {
		this.tax = tax;
	}

	public Float getNontax() {
		return this.nontax;
	}

	public void setNontax(Float nontax) {
		this.nontax = nontax;
	}

	public Float getLockerRent() {
		return this.lockerRent;
	}

	public void setLockerRent(Float lockerRent) {
		this.lockerRent = lockerRent;
	}

	public Float getCuring() {
		return this.curing;
	}

	public void setCuring(Float curing) {
		this.curing = curing;
	}

	public Float getProcessing() {
		return this.processing;
	}

	public void setProcessing(Float processing) {
		this.processing = processing;
	}

	public Float getPprocessing() {
		return this.pprocessing;
	}

	public void setPprocessing(Float pprocessing) {
		this.pprocessing = pprocessing;
	}

	public Float getDprocessing() {
		return this.dprocessing;
	}

	public void setDprocessing(Float dprocessing) {
		this.dprocessing = dprocessing;
	}

	public Float getOther() {
		return this.other;
	}

	public void setOther(Float other) {
		this.other = other;
	}

	public Float getTotal() {
		return this.total;
	}

	public void setTotal(Float total) {
		this.total = total;
	}

	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	public Float getAmount() {
		return this.amount;
	}

	public void setAmount(Float amount) {
		this.amount = amount;
	}

	public Float getChange() {
		return this.change;
	}

	public void setChange(Float change) {
		this.change = change;
	}

	public boolean isZzed() {
		return this.zzed;
	}

	public void setZzed(boolean zzed) {
		this.zzed = zzed;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getMulti() {
		return this.multi;
	}

	public void setMulti(Double multi) {
		this.multi = multi;
	}

	public Double getTransationNumber() {
		return this.TransationNumber;
	}

	public void setTransationNumber(Double TransationNumber) {
		this.TransationNumber = TransationNumber;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof XactionsId))
			return false;
		XactionsId castOther = (XactionsId) other;

		return (this.getCounter() == castOther.getCounter())
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
						&& this.getDate().equals(castOther.getDate())))
				&& ((this.getTime() == castOther.getTime()) || (this.getTime() != null && castOther.getTime() != null
						&& this.getTime().equals(castOther.getTime())))
				&& ((this.getSpecies() == castOther.getSpecies()) || (this.getSpecies() != null
						&& castOther.getSpecies() != null && this.getSpecies().equals(castOther.getSpecies())))
				&& ((this.getMeatSales() == castOther.getMeatSales()) || (this.getMeatSales() != null
						&& castOther.getMeatSales() != null && this.getMeatSales().equals(castOther.getMeatSales())))
				&& ((this.getTax() == castOther.getTax()) || (this.getTax() != null && castOther.getTax() != null
						&& this.getTax().equals(castOther.getTax())))
				&& ((this.getNontax() == castOther.getNontax()) || (this.getNontax() != null
						&& castOther.getNontax() != null && this.getNontax().equals(castOther.getNontax())))
				&& ((this.getLockerRent() == castOther.getLockerRent()) || (this.getLockerRent() != null
						&& castOther.getLockerRent() != null && this.getLockerRent().equals(castOther.getLockerRent())))
				&& ((this.getCuring() == castOther.getCuring()) || (this.getCuring() != null
						&& castOther.getCuring() != null && this.getCuring().equals(castOther.getCuring())))
				&& ((this.getProcessing() == castOther.getProcessing()) || (this.getProcessing() != null
						&& castOther.getProcessing() != null && this.getProcessing().equals(castOther.getProcessing())))
				&& ((this.getPprocessing() == castOther.getPprocessing())
						|| (this.getPprocessing() != null && castOther.getPprocessing() != null
								&& this.getPprocessing().equals(castOther.getPprocessing())))
				&& ((this.getDprocessing() == castOther.getDprocessing())
						|| (this.getDprocessing() != null && castOther.getDprocessing() != null
								&& this.getDprocessing().equals(castOther.getDprocessing())))
				&& ((this.getOther() == castOther.getOther()) || (this.getOther() != null
						&& castOther.getOther() != null && this.getOther().equals(castOther.getOther())))
				&& ((this.getTotal() == castOther.getTotal()) || (this.getTotal() != null
						&& castOther.getTotal() != null && this.getTotal().equals(castOther.getTotal())))
				&& ((this.getMethod() == castOther.getMethod()) || (this.getMethod() != null
						&& castOther.getMethod() != null && this.getMethod().equals(castOther.getMethod())))
				&& ((this.getAmount() == castOther.getAmount()) || (this.getAmount() != null
						&& castOther.getAmount() != null && this.getAmount().equals(castOther.getAmount())))
				&& ((this.getChange() == castOther.getChange()) || (this.getChange() != null
						&& castOther.getChange() != null && this.getChange().equals(castOther.getChange())))
				&& (this.isZzed() == castOther.isZzed())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getMulti() == castOther.getMulti()) || (this.getMulti() != null
						&& castOther.getMulti() != null && this.getMulti().equals(castOther.getMulti())))
				&& ((this.getTransationNumber() == castOther.getTransationNumber())
						|| (this.getTransationNumber() != null && castOther.getTransationNumber() != null
								&& this.getTransationNumber().equals(castOther.getTransationNumber())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCounter();
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result + (getTime() == null ? 0 : this.getTime().hashCode());
		result = 37 * result + (getSpecies() == null ? 0 : this.getSpecies().hashCode());
		result = 37 * result + (getMeatSales() == null ? 0 : this.getMeatSales().hashCode());
		result = 37 * result + (getTax() == null ? 0 : this.getTax().hashCode());
		result = 37 * result + (getNontax() == null ? 0 : this.getNontax().hashCode());
		result = 37 * result + (getLockerRent() == null ? 0 : this.getLockerRent().hashCode());
		result = 37 * result + (getCuring() == null ? 0 : this.getCuring().hashCode());
		result = 37 * result + (getProcessing() == null ? 0 : this.getProcessing().hashCode());
		result = 37 * result + (getPprocessing() == null ? 0 : this.getPprocessing().hashCode());
		result = 37 * result + (getDprocessing() == null ? 0 : this.getDprocessing().hashCode());
		result = 37 * result + (getOther() == null ? 0 : this.getOther().hashCode());
		result = 37 * result + (getTotal() == null ? 0 : this.getTotal().hashCode());
		result = 37 * result + (getMethod() == null ? 0 : this.getMethod().hashCode());
		result = 37 * result + (getAmount() == null ? 0 : this.getAmount().hashCode());
		result = 37 * result + (getChange() == null ? 0 : this.getChange().hashCode());
		result = 37 * result + (this.isZzed() ? 1 : 0);
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getMulti() == null ? 0 : this.getMulti().hashCode());
		result = 37 * result + (getTransationNumber() == null ? 0 : this.getTransationNumber().hashCode());
		return result;
	}

}
