package archieverecords.schema.model;
// Generated Feb 17, 2018 4:24:52 PM by Hibernate Tools 5.2.8.Final

/**
 * Xactions generated by hbm2java
 */
public class Xactions implements java.io.Serializable {

	private XactionsId id;

	public Xactions() {
	}

	public Xactions(XactionsId id) {
		this.id = id;
	}

	public XactionsId getId() {
		return this.id;
	}

	public void setId(XactionsId id) {
		this.id = id;
	}

}
