package archieverecords.schema.model;
// Generated Feb 17, 2018 4:24:52 PM by Hibernate Tools 5.2.8.Final

/**
 * Xdeposits generated by hbm2java
 */
public class Xdeposits implements java.io.Serializable {

	private XdepositsId id;

	public Xdeposits() {
	}

	public Xdeposits(XdepositsId id) {
		this.id = id;
	}

	public XdepositsId getId() {
		return this.id;
	}

	public void setId(XdepositsId id) {
		this.id = id;
	}

}
