package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	private AccountId id;

	public Account() {
	}

	public Account(AccountId id) {
		this.id = id;
	}

	public AccountId getId() {
		return this.id;
	}

	public void setId(AccountId id) {
		this.id = id;
	}

}
