package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * Authorities generated by hbm2java
 */
public class Authorities implements java.io.Serializable {

	private AuthoritiesId id;

	public Authorities() {
	}

	public Authorities(AuthoritiesId id) {
		this.id = id;
	}

	public AuthoritiesId getId() {
		return this.id;
	}

	public void setId(AuthoritiesId id) {
		this.id = id;
	}

}
