package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * BeefweightsId generated by hbm2java
 */
public class BeefweightsId implements java.io.Serializable {

	private int counter;
	private Integer beefId;
	private String weight;

	public BeefweightsId() {
	}

	public BeefweightsId(int counter) {
		this.counter = counter;
	}

	public BeefweightsId(int counter, Integer beefId, String weight) {
		this.counter = counter;
		this.beefId = beefId;
		this.weight = weight;
	}

	public int getCounter() {
		return this.counter;
	}

	public void setCounter(int counter) {
		this.counter = counter;
	}

	public Integer getBeefId() {
		return this.beefId;
	}

	public void setBeefId(Integer beefId) {
		this.beefId = beefId;
	}

	public String getWeight() {
		return this.weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BeefweightsId))
			return false;
		BeefweightsId castOther = (BeefweightsId) other;

		return (this.getCounter() == castOther.getCounter())
				&& ((this.getBeefId() == castOther.getBeefId()) || (this.getBeefId() != null
						&& castOther.getBeefId() != null && this.getBeefId().equals(castOther.getBeefId())))
				&& ((this.getWeight() == castOther.getWeight()) || (this.getWeight() != null
						&& castOther.getWeight() != null && this.getWeight().equals(castOther.getWeight())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCounter();
		result = 37 * result + (getBeefId() == null ? 0 : this.getBeefId().hashCode());
		result = 37 * result + (getWeight() == null ? 0 : this.getWeight().hashCode());
		return result;
	}

}
