package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Beef generated by hbm2java
 */
@Entity
@Table(name = "beef")
public class Beef implements java.io.Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "counter", unique = true, nullable = false)
	private Integer counter;
    @Column(name = "`Full Name`")
	private String fullName;
	private Date deliveryDate;
	private Integer order;
	private Date active;
	private String type;
	@Column(name = "`Hanging Weight`")
	private Double hangingWeight;
	private BigDecimal processing;
	@Column(name = "`Liver Weight`")
	private Double liverWeight;
	@Column(name = "`Dressed Weight`")
	private Double dressedWeight;
	@Column(name = "`Live Weight`")
	private Float liveWeight;
	@Column(name = "`Tag Number`")
	private Float tagNumber;
	private Double storage;
	@Column(name = "`Total Charges`")
	private BigDecimal totalCharges;
	@Column(name = "`Number Of Beef`")
	private Float numberOfBeef;
	private Double dress;
	private Boolean ztill;
	private Boolean cuttingOrder;
	private Boolean age;
	private String owner;
	private String condit;
	private String breed;
	private Boolean email;
	private Boolean call;
	private Date called;

	public Beef() {
	}

	public Beef(String fullName, String type) {
		this.fullName = fullName;
		this.type = type;
	}

	public Beef(String fullName, Date deliveryDate, Integer order, Date active, String type, Double hangingWeight,
			BigDecimal processing, Double liverWeight, Double dressedWeight, Float liveWeight, Float tagNumber,
			Double storage, BigDecimal totalCharges, Float numberOfBeef, Double dress, Boolean ztill,
			Boolean cuttingOrder, Boolean age, String owner, String condit, String breed, Boolean email, Boolean call,
			Date called) {
		this.fullName = fullName;
		this.deliveryDate = deliveryDate;
		this.order = order;
		this.active = active;
		this.type = type;
		this.hangingWeight = hangingWeight;
		this.processing = processing;
		this.liverWeight = liverWeight;
		this.dressedWeight = dressedWeight;
		this.liveWeight = liveWeight;
		this.tagNumber = tagNumber;
		this.storage = storage;
		this.totalCharges = totalCharges;
		this.numberOfBeef = numberOfBeef;
		this.dress = dress;
		this.ztill = ztill;
		this.cuttingOrder = cuttingOrder;
		this.age = age;
		this.owner = owner;
		this.condit = condit;
		this.breed = breed;
		this.email = email;
		this.call = call;
		this.called = called;
	}

	public Integer getCounter() {
		return this.counter;
	}

	public void setCounter(Integer counter) {
		this.counter = counter;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public Date getDeliveryDate() {
		return this.deliveryDate;
	}

	public void setDeliveryDate(Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	public Integer getOrder() {
		return this.order;
	}

	public void setOrder(Integer order) {
		this.order = order;
	}

	public Date getActive() {
		return this.active;
	}

	public void setActive(Date active) {
		this.active = active;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Double getHangingWeight() {
		return this.hangingWeight;
	}

	public void setHangingWeight(Double hangingWeight) {
		this.hangingWeight = hangingWeight;
	}

	public BigDecimal getProcessing() {
		return this.processing;
	}

	public void setProcessing(BigDecimal processing) {
		this.processing = processing;
	}

	public Double getLiverWeight() {
		return this.liverWeight;
	}

	public void setLiverWeight(Double liverWeight) {
		this.liverWeight = liverWeight;
	}

	public Double getDressedWeight() {
		return this.dressedWeight;
	}

	public void setDressedWeight(Double dressedWeight) {
		this.dressedWeight = dressedWeight;
	}

	public Float getLiveWeight() {
		return this.liveWeight;
	}

	public void setLiveWeight(Float liveWeight) {
		this.liveWeight = liveWeight;
	}

	public Float getTagNumber() {
		return this.tagNumber;
	}

	public void setTagNumber(Float tagNumber) {
		this.tagNumber = tagNumber;
	}

	public Double getStorage() {
		return this.storage;
	}

	public void setStorage(Double storage) {
		this.storage = storage;
	}

	public BigDecimal getTotalCharges() {
		return this.totalCharges;
	}

	public void setTotalCharges(BigDecimal totalCharges) {
		this.totalCharges = totalCharges;
	}

	public Float getNumberOfBeef() {
		return this.numberOfBeef;
	}

	public void setNumberOfBeef(Float numberOfBeef) {
		this.numberOfBeef = numberOfBeef;
	}

	public Double getDress() {
		return this.dress;
	}

	public void setDress(Double dress) {
		this.dress = dress;
	}

	public Boolean getZtill() {
		return this.ztill;
	}

	public void setZtill(Boolean ztill) {
		this.ztill = ztill;
	}

	public Boolean getCuttingOrder() {
		return this.cuttingOrder;
	}

	public void setCuttingOrder(Boolean cuttingOrder) {
		this.cuttingOrder = cuttingOrder;
	}

	public Boolean getAge() {
		return this.age;
	}

	public void setAge(Boolean age) {
		this.age = age;
	}

	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public String getCondit() {
		return this.condit;
	}

	public void setCondit(String condit) {
		this.condit = condit;
	}

	public String getBreed() {
		return this.breed;
	}

	public void setBreed(String breed) {
		this.breed = breed;
	}

	public Boolean getEmail() {
		return this.email;
	}

	public void setEmail(Boolean email) {
		this.email = email;
	}

	public Boolean getCall() {
		return this.call;
	}

	public void setCall(Boolean call) {
		this.call = call;
	}

	public Date getCalled() {
		return this.called;
	}

	public void setCalled(Date called) {
		this.called = called;
	}

}
