package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;

/**
 * BeefcuttingId generated by hbm2java
 */
public class BeefcuttingId implements java.io.Serializable {

	private int counter;
	private String fullName;
	private Date date;
	private Integer tagNumber;
	private String order;
	private String special;
	private String steak;
	private String shortRibsTp;
	private String shortRibs;
	private String shortRibsCt;
	private String roast;
	private String boilingBeeftp;
	private String boilingBeef;
	private String boilingBeefct;
	private short soupBonesTp;
	private String soupBones;
	private String soupBonesct;
	private short ribTp;
	private String rib;
	private String ribct;
	private String chuckRoasttp;
	private String chuckRoast;
	private String chuckRoastct;
	private String chuckSteaktp;
	private String chuckSteak;
	private String chuckSteakct;
	private short armTp;
	private String arm;
	private String armct;
	private short sirloinTiptp;
	private String sirloinTip;
	private String sirloinTipct;
	private short tbonetp;
	private String tbone;
	private short tbonect;
	private short porterhousetp;
	private String porterhouse;
	private short porterhousect;
	private short sirlointp;
	private String sirloin;
	private short sirloinct;
	private short roundtp;
	private String round;
	private short roundct;
	private String rump;
	private short rumpct;
	private String pikes;
	private short pikesct;
	private String stew;
	private short stewCt;
	private String ground;
	private String groundpk;
	private String groundct;
	private boolean doubleWrapp;
	private String brisket;
	private String brisketct;
	private int beefId;
	private int liveWeight;
	private String hangingWeight;

	public BeefcuttingId() {
	}

	public BeefcuttingId(int counter, String fullName, Date date, String shortRibsTp, String shortRibsCt, String roast,
			String boilingBeeftp, String boilingBeef, String boilingBeefct, short soupBonesTp, String soupBones,
			String soupBonesct, short ribTp, String rib, String ribct, String chuckRoasttp, String chuckRoast,
			String chuckRoastct, String chuckSteaktp, String chuckSteak, String chuckSteakct, short armTp, String arm,
			String armct, short sirloinTiptp, String sirloinTip, String sirloinTipct, short tbonetp, String tbone,
			short tbonect, short porterhousetp, String porterhouse, short porterhousect, short sirlointp,
			String sirloin, short sirloinct, short roundtp, String round, short roundct, String rump, short rumpct,
			String pikes, short pikesct, String stew, short stewCt, String ground, String groundpk, String groundct,
			boolean doubleWrapp, String brisket, String brisketct, int beefId, int liveWeight, String hangingWeight) {
		this.counter = counter;
		this.fullName = fullName;
		this.date = date;
		this.shortRibsTp = shortRibsTp;
		this.shortRibsCt = shortRibsCt;
		this.roast = roast;
		this.boilingBeeftp = boilingBeeftp;
		this.boilingBeef = boilingBeef;
		this.boilingBeefct = boilingBeefct;
		this.soupBonesTp = soupBonesTp;
		this.soupBones = soupBones;
		this.soupBonesct = soupBonesct;
		this.ribTp = ribTp;
		this.rib = rib;
		this.ribct = ribct;
		this.chuckRoasttp = chuckRoasttp;
		this.chuckRoast = chuckRoast;
		this.chuckRoastct = chuckRoastct;
		this.chuckSteaktp = chuckSteaktp;
		this.chuckSteak = chuckSteak;
		this.chuckSteakct = chuckSteakct;
		this.armTp = armTp;
		this.arm = arm;
		this.armct = armct;
		this.sirloinTiptp = sirloinTiptp;
		this.sirloinTip = sirloinTip;
		this.sirloinTipct = sirloinTipct;
		this.tbonetp = tbonetp;
		this.tbone = tbone;
		this.tbonect = tbonect;
		this.porterhousetp = porterhousetp;
		this.porterhouse = porterhouse;
		this.porterhousect = porterhousect;
		this.sirlointp = sirlointp;
		this.sirloin = sirloin;
		this.sirloinct = sirloinct;
		this.roundtp = roundtp;
		this.round = round;
		this.roundct = roundct;
		this.rump = rump;
		this.rumpct = rumpct;
		this.pikes = pikes;
		this.pikesct = pikesct;
		this.stew = stew;
		this.stewCt = stewCt;
		this.ground = ground;
		this.groundpk = groundpk;
		this.groundct = groundct;
		this.doubleWrapp = doubleWrapp;
		this.brisket = brisket;
		this.brisketct = brisketct;
		this.beefId = beefId;
		this.liveWeight = liveWeight;
		this.hangingWeight = hangingWeight;
	}

	public BeefcuttingId(int counter, String fullName, Date date, Integer tagNumber, String order, String special,
			String steak, String shortRibsTp, String shortRibs, String shortRibsCt, String roast, String boilingBeeftp,
			String boilingBeef, String boilingBeefct, short soupBonesTp, String soupBones, String soupBonesct,
			short ribTp, String rib, String ribct, String chuckRoasttp, String chuckRoast, String chuckRoastct,
			String chuckSteaktp, String chuckSteak, String chuckSteakct, short armTp, String arm, String armct,
			short sirloinTiptp, String sirloinTip, String sirloinTipct, short tbonetp, String tbone, short tbonect,
			short porterhousetp, String porterhouse, short porterhousect, short sirlointp, String sirloin,
			short sirloinct, short roundtp, String round, short roundct, String rump, short rumpct, String pikes,
			short pikesct, String stew, short stewCt, String ground, String groundpk, String groundct,
			boolean doubleWrapp, String brisket, String brisketct, int beefId, int liveWeight, String hangingWeight) {
		this.counter = counter;
		this.fullName = fullName;
		this.date = date;
		this.tagNumber = tagNumber;
		this.order = order;
		this.special = special;
		this.steak = steak;
		this.shortRibsTp = shortRibsTp;
		this.shortRibs = shortRibs;
		this.shortRibsCt = shortRibsCt;
		this.roast = roast;
		this.boilingBeeftp = boilingBeeftp;
		this.boilingBeef = boilingBeef;
		this.boilingBeefct = boilingBeefct;
		this.soupBonesTp = soupBonesTp;
		this.soupBones = soupBones;
		this.soupBonesct = soupBonesct;
		this.ribTp = ribTp;
		this.rib = rib;
		this.ribct = ribct;
		this.chuckRoasttp = chuckRoasttp;
		this.chuckRoast = chuckRoast;
		this.chuckRoastct = chuckRoastct;
		this.chuckSteaktp = chuckSteaktp;
		this.chuckSteak = chuckSteak;
		this.chuckSteakct = chuckSteakct;
		this.armTp = armTp;
		this.arm = arm;
		this.armct = armct;
		this.sirloinTiptp = sirloinTiptp;
		this.sirloinTip = sirloinTip;
		this.sirloinTipct = sirloinTipct;
		this.tbonetp = tbonetp;
		this.tbone = tbone;
		this.tbonect = tbonect;
		this.porterhousetp = porterhousetp;
		this.porterhouse = porterhouse;
		this.porterhousect = porterhousect;
		this.sirlointp = sirlointp;
		this.sirloin = sirloin;
		this.sirloinct = sirloinct;
		this.roundtp = roundtp;
		this.round = round;
		this.roundct = roundct;
		this.rump = rump;
		this.rumpct = rumpct;
		this.pikes = pikes;
		this.pikesct = pikesct;
		this.stew = stew;
		this.stewCt = stewCt;
		this.ground = ground;
		this.groundpk = groundpk;
		this.groundct = groundct;
		this.doubleWrapp = doubleWrapp;
		this.brisket = brisket;
		this.brisketct = brisketct;
		this.beefId = beefId;
		this.liveWeight = liveWeight;
		this.hangingWeight = hangingWeight;
	}

	public int getCounter() {
		return this.counter;
	}

	public void setCounter(int counter) {
		this.counter = counter;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Integer getTagNumber() {
		return this.tagNumber;
	}

	public void setTagNumber(Integer tagNumber) {
		this.tagNumber = tagNumber;
	}

	public String getOrder() {
		return this.order;
	}

	public void setOrder(String order) {
		this.order = order;
	}

	public String getSpecial() {
		return this.special;
	}

	public void setSpecial(String special) {
		this.special = special;
	}

	public String getSteak() {
		return this.steak;
	}

	public void setSteak(String steak) {
		this.steak = steak;
	}

	public String getShortRibsTp() {
		return this.shortRibsTp;
	}

	public void setShortRibsTp(String shortRibsTp) {
		this.shortRibsTp = shortRibsTp;
	}

	public String getShortRibs() {
		return this.shortRibs;
	}

	public void setShortRibs(String shortRibs) {
		this.shortRibs = shortRibs;
	}

	public String getShortRibsCt() {
		return this.shortRibsCt;
	}

	public void setShortRibsCt(String shortRibsCt) {
		this.shortRibsCt = shortRibsCt;
	}

	public String getRoast() {
		return this.roast;
	}

	public void setRoast(String roast) {
		this.roast = roast;
	}

	public String getBoilingBeeftp() {
		return this.boilingBeeftp;
	}

	public void setBoilingBeeftp(String boilingBeeftp) {
		this.boilingBeeftp = boilingBeeftp;
	}

	public String getBoilingBeef() {
		return this.boilingBeef;
	}

	public void setBoilingBeef(String boilingBeef) {
		this.boilingBeef = boilingBeef;
	}

	public String getBoilingBeefct() {
		return this.boilingBeefct;
	}

	public void setBoilingBeefct(String boilingBeefct) {
		this.boilingBeefct = boilingBeefct;
	}

	public short getSoupBonesTp() {
		return this.soupBonesTp;
	}

	public void setSoupBonesTp(short soupBonesTp) {
		this.soupBonesTp = soupBonesTp;
	}

	public String getSoupBones() {
		return this.soupBones;
	}

	public void setSoupBones(String soupBones) {
		this.soupBones = soupBones;
	}

	public String getSoupBonesct() {
		return this.soupBonesct;
	}

	public void setSoupBonesct(String soupBonesct) {
		this.soupBonesct = soupBonesct;
	}

	public short getRibTp() {
		return this.ribTp;
	}

	public void setRibTp(short ribTp) {
		this.ribTp = ribTp;
	}

	public String getRib() {
		return this.rib;
	}

	public void setRib(String rib) {
		this.rib = rib;
	}

	public String getRibct() {
		return this.ribct;
	}

	public void setRibct(String ribct) {
		this.ribct = ribct;
	}

	public String getChuckRoasttp() {
		return this.chuckRoasttp;
	}

	public void setChuckRoasttp(String chuckRoasttp) {
		this.chuckRoasttp = chuckRoasttp;
	}

	public String getChuckRoast() {
		return this.chuckRoast;
	}

	public void setChuckRoast(String chuckRoast) {
		this.chuckRoast = chuckRoast;
	}

	public String getChuckRoastct() {
		return this.chuckRoastct;
	}

	public void setChuckRoastct(String chuckRoastct) {
		this.chuckRoastct = chuckRoastct;
	}

	public String getChuckSteaktp() {
		return this.chuckSteaktp;
	}

	public void setChuckSteaktp(String chuckSteaktp) {
		this.chuckSteaktp = chuckSteaktp;
	}

	public String getChuckSteak() {
		return this.chuckSteak;
	}

	public void setChuckSteak(String chuckSteak) {
		this.chuckSteak = chuckSteak;
	}

	public String getChuckSteakct() {
		return this.chuckSteakct;
	}

	public void setChuckSteakct(String chuckSteakct) {
		this.chuckSteakct = chuckSteakct;
	}

	public short getArmTp() {
		return this.armTp;
	}

	public void setArmTp(short armTp) {
		this.armTp = armTp;
	}

	public String getArm() {
		return this.arm;
	}

	public void setArm(String arm) {
		this.arm = arm;
	}

	public String getArmct() {
		return this.armct;
	}

	public void setArmct(String armct) {
		this.armct = armct;
	}

	public short getSirloinTiptp() {
		return this.sirloinTiptp;
	}

	public void setSirloinTiptp(short sirloinTiptp) {
		this.sirloinTiptp = sirloinTiptp;
	}

	public String getSirloinTip() {
		return this.sirloinTip;
	}

	public void setSirloinTip(String sirloinTip) {
		this.sirloinTip = sirloinTip;
	}

	public String getSirloinTipct() {
		return this.sirloinTipct;
	}

	public void setSirloinTipct(String sirloinTipct) {
		this.sirloinTipct = sirloinTipct;
	}

	public short getTbonetp() {
		return this.tbonetp;
	}

	public void setTbonetp(short tbonetp) {
		this.tbonetp = tbonetp;
	}

	public String getTbone() {
		return this.tbone;
	}

	public void setTbone(String tbone) {
		this.tbone = tbone;
	}

	public short getTbonect() {
		return this.tbonect;
	}

	public void setTbonect(short tbonect) {
		this.tbonect = tbonect;
	}

	public short getPorterhousetp() {
		return this.porterhousetp;
	}

	public void setPorterhousetp(short porterhousetp) {
		this.porterhousetp = porterhousetp;
	}

	public String getPorterhouse() {
		return this.porterhouse;
	}

	public void setPorterhouse(String porterhouse) {
		this.porterhouse = porterhouse;
	}

	public short getPorterhousect() {
		return this.porterhousect;
	}

	public void setPorterhousect(short porterhousect) {
		this.porterhousect = porterhousect;
	}

	public short getSirlointp() {
		return this.sirlointp;
	}

	public void setSirlointp(short sirlointp) {
		this.sirlointp = sirlointp;
	}

	public String getSirloin() {
		return this.sirloin;
	}

	public void setSirloin(String sirloin) {
		this.sirloin = sirloin;
	}

	public short getSirloinct() {
		return this.sirloinct;
	}

	public void setSirloinct(short sirloinct) {
		this.sirloinct = sirloinct;
	}

	public short getRoundtp() {
		return this.roundtp;
	}

	public void setRoundtp(short roundtp) {
		this.roundtp = roundtp;
	}

	public String getRound() {
		return this.round;
	}

	public void setRound(String round) {
		this.round = round;
	}

	public short getRoundct() {
		return this.roundct;
	}

	public void setRoundct(short roundct) {
		this.roundct = roundct;
	}

	public String getRump() {
		return this.rump;
	}

	public void setRump(String rump) {
		this.rump = rump;
	}

	public short getRumpct() {
		return this.rumpct;
	}

	public void setRumpct(short rumpct) {
		this.rumpct = rumpct;
	}

	public String getPikes() {
		return this.pikes;
	}

	public void setPikes(String pikes) {
		this.pikes = pikes;
	}

	public short getPikesct() {
		return this.pikesct;
	}

	public void setPikesct(short pikesct) {
		this.pikesct = pikesct;
	}

	public String getStew() {
		return this.stew;
	}

	public void setStew(String stew) {
		this.stew = stew;
	}

	public short getStewCt() {
		return this.stewCt;
	}

	public void setStewCt(short stewCt) {
		this.stewCt = stewCt;
	}

	public String getGround() {
		return this.ground;
	}

	public void setGround(String ground) {
		this.ground = ground;
	}

	public String getGroundpk() {
		return this.groundpk;
	}

	public void setGroundpk(String groundpk) {
		this.groundpk = groundpk;
	}

	public String getGroundct() {
		return this.groundct;
	}

	public void setGroundct(String groundct) {
		this.groundct = groundct;
	}

	public boolean isDoubleWrapp() {
		return this.doubleWrapp;
	}

	public void setDoubleWrapp(boolean doubleWrapp) {
		this.doubleWrapp = doubleWrapp;
	}

	public String getBrisket() {
		return this.brisket;
	}

	public void setBrisket(String brisket) {
		this.brisket = brisket;
	}

	public String getBrisketct() {
		return this.brisketct;
	}

	public void setBrisketct(String brisketct) {
		this.brisketct = brisketct;
	}

	public int getBeefId() {
		return this.beefId;
	}

	public void setBeefId(int beefId) {
		this.beefId = beefId;
	}

	public int getLiveWeight() {
		return this.liveWeight;
	}

	public void setLiveWeight(int liveWeight) {
		this.liveWeight = liveWeight;
	}

	public String getHangingWeight() {
		return this.hangingWeight;
	}

	public void setHangingWeight(String hangingWeight) {
		this.hangingWeight = hangingWeight;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BeefcuttingId))
			return false;
		BeefcuttingId castOther = (BeefcuttingId) other;

		return (this.getCounter() == castOther.getCounter())
				&& ((this.getFullName() == castOther.getFullName()) || (this.getFullName() != null
						&& castOther.getFullName() != null && this.getFullName().equals(castOther.getFullName())))
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
						&& this.getDate().equals(castOther.getDate())))
				&& ((this.getTagNumber() == castOther.getTagNumber()) || (this.getTagNumber() != null
						&& castOther.getTagNumber() != null && this.getTagNumber().equals(castOther.getTagNumber())))
				&& ((this.getOrder() == castOther.getOrder()) || (this.getOrder() != null
						&& castOther.getOrder() != null && this.getOrder().equals(castOther.getOrder())))
				&& ((this.getSpecial() == castOther.getSpecial()) || (this.getSpecial() != null
						&& castOther.getSpecial() != null && this.getSpecial().equals(castOther.getSpecial())))
				&& ((this.getSteak() == castOther.getSteak()) || (this.getSteak() != null
						&& castOther.getSteak() != null && this.getSteak().equals(castOther.getSteak())))
				&& ((this.getShortRibsTp() == castOther.getShortRibsTp())
						|| (this.getShortRibsTp() != null && castOther.getShortRibsTp() != null
								&& this.getShortRibsTp().equals(castOther.getShortRibsTp())))
				&& ((this.getShortRibs() == castOther.getShortRibs()) || (this.getShortRibs() != null
						&& castOther.getShortRibs() != null && this.getShortRibs().equals(castOther.getShortRibs())))
				&& ((this.getShortRibsCt() == castOther.getShortRibsCt())
						|| (this.getShortRibsCt() != null && castOther.getShortRibsCt() != null
								&& this.getShortRibsCt().equals(castOther.getShortRibsCt())))
				&& ((this.getRoast() == castOther.getRoast()) || (this.getRoast() != null
						&& castOther.getRoast() != null && this.getRoast().equals(castOther.getRoast())))
				&& ((this.getBoilingBeeftp() == castOther.getBoilingBeeftp())
						|| (this.getBoilingBeeftp() != null && castOther.getBoilingBeeftp() != null
								&& this.getBoilingBeeftp().equals(castOther.getBoilingBeeftp())))
				&& ((this.getBoilingBeef() == castOther.getBoilingBeef())
						|| (this.getBoilingBeef() != null && castOther.getBoilingBeef() != null
								&& this.getBoilingBeef().equals(castOther.getBoilingBeef())))
				&& ((this.getBoilingBeefct() == castOther.getBoilingBeefct())
						|| (this.getBoilingBeefct() != null && castOther.getBoilingBeefct() != null
								&& this.getBoilingBeefct().equals(castOther.getBoilingBeefct())))
				&& (this.getSoupBonesTp() == castOther.getSoupBonesTp())
				&& ((this.getSoupBones() == castOther.getSoupBones()) || (this.getSoupBones() != null
						&& castOther.getSoupBones() != null && this.getSoupBones().equals(castOther.getSoupBones())))
				&& ((this.getSoupBonesct() == castOther.getSoupBonesct())
						|| (this.getSoupBonesct() != null && castOther.getSoupBonesct() != null
								&& this.getSoupBonesct().equals(castOther.getSoupBonesct())))
				&& (this.getRibTp() == castOther.getRibTp())
				&& ((this.getRib() == castOther.getRib()) || (this.getRib() != null && castOther.getRib() != null
						&& this.getRib().equals(castOther.getRib())))
				&& ((this.getRibct() == castOther.getRibct()) || (this.getRibct() != null
						&& castOther.getRibct() != null && this.getRibct().equals(castOther.getRibct())))
				&& ((this.getChuckRoasttp() == castOther.getChuckRoasttp())
						|| (this.getChuckRoasttp() != null && castOther.getChuckRoasttp() != null
								&& this.getChuckRoasttp().equals(castOther.getChuckRoasttp())))
				&& ((this.getChuckRoast() == castOther.getChuckRoast()) || (this.getChuckRoast() != null
						&& castOther.getChuckRoast() != null && this.getChuckRoast().equals(castOther.getChuckRoast())))
				&& ((this.getChuckRoastct() == castOther.getChuckRoastct())
						|| (this.getChuckRoastct() != null && castOther.getChuckRoastct() != null
								&& this.getChuckRoastct().equals(castOther.getChuckRoastct())))
				&& ((this.getChuckSteaktp() == castOther.getChuckSteaktp())
						|| (this.getChuckSteaktp() != null && castOther.getChuckSteaktp() != null
								&& this.getChuckSteaktp().equals(castOther.getChuckSteaktp())))
				&& ((this.getChuckSteak() == castOther.getChuckSteak()) || (this.getChuckSteak() != null
						&& castOther.getChuckSteak() != null && this.getChuckSteak().equals(castOther.getChuckSteak())))
				&& ((this.getChuckSteakct() == castOther.getChuckSteakct())
						|| (this.getChuckSteakct() != null && castOther.getChuckSteakct() != null
								&& this.getChuckSteakct().equals(castOther.getChuckSteakct())))
				&& (this.getArmTp() == castOther.getArmTp())
				&& ((this.getArm() == castOther.getArm()) || (this.getArm() != null && castOther.getArm() != null
						&& this.getArm().equals(castOther.getArm())))
				&& ((this.getArmct() == castOther.getArmct()) || (this.getArmct() != null
						&& castOther.getArmct() != null && this.getArmct().equals(castOther.getArmct())))
				&& (this.getSirloinTiptp() == castOther.getSirloinTiptp())
				&& ((this.getSirloinTip() == castOther.getSirloinTip()) || (this.getSirloinTip() != null
						&& castOther.getSirloinTip() != null && this.getSirloinTip().equals(castOther.getSirloinTip())))
				&& ((this.getSirloinTipct() == castOther.getSirloinTipct())
						|| (this.getSirloinTipct() != null && castOther.getSirloinTipct() != null
								&& this.getSirloinTipct().equals(castOther.getSirloinTipct())))
				&& (this.getTbonetp() == castOther.getTbonetp())
				&& ((this.getTbone() == castOther.getTbone()) || (this.getTbone() != null
						&& castOther.getTbone() != null && this.getTbone().equals(castOther.getTbone())))
				&& (this.getTbonect() == castOther.getTbonect())
				&& (this.getPorterhousetp() == castOther.getPorterhousetp())
				&& ((this.getPorterhouse() == castOther.getPorterhouse())
						|| (this.getPorterhouse() != null && castOther.getPorterhouse() != null
								&& this.getPorterhouse().equals(castOther.getPorterhouse())))
				&& (this.getPorterhousect() == castOther.getPorterhousect())
				&& (this.getSirlointp() == castOther.getSirlointp())
				&& ((this.getSirloin() == castOther.getSirloin()) || (this.getSirloin() != null
						&& castOther.getSirloin() != null && this.getSirloin().equals(castOther.getSirloin())))
				&& (this.getSirloinct() == castOther.getSirloinct()) && (this.getRoundtp() == castOther.getRoundtp())
				&& ((this.getRound() == castOther.getRound()) || (this.getRound() != null
						&& castOther.getRound() != null && this.getRound().equals(castOther.getRound())))
				&& (this.getRoundct() == castOther.getRoundct())
				&& ((this.getRump() == castOther.getRump()) || (this.getRump() != null
						&& castOther.getRump() != null && this.getRump().equals(castOther.getRump())))
				&& (this.getRumpct() == castOther.getRumpct())
				&& ((this.getPikes() == castOther.getPikes()) || (this.getPikes() != null
						&& castOther.getPikes() != null && this.getPikes().equals(castOther.getPikes())))
				&& (this.getPikesct() == castOther.getPikesct())
				&& ((this.getStew() == castOther.getStew()) || (this.getStew() != null
						&& castOther.getStew() != null && this.getStew().equals(castOther.getStew())))
				&& (this.getStewCt() == castOther.getStewCt())
				&& ((this.getGround() == castOther.getGround()) || (this.getGround() != null
						&& castOther.getGround() != null && this.getGround().equals(castOther.getGround())))
				&& ((this.getGroundpk() == castOther.getGroundpk()) || (this.getGroundpk() != null
						&& castOther.getGroundpk() != null && this.getGroundpk().equals(castOther.getGroundpk())))
				&& ((this.getGroundct() == castOther.getGroundct()) || (this.getGroundct() != null
						&& castOther.getGroundct() != null && this.getGroundct().equals(castOther.getGroundct())))
				&& (this.isDoubleWrapp() == castOther.isDoubleWrapp())
				&& ((this.getBrisket() == castOther.getBrisket()) || (this.getBrisket() != null
						&& castOther.getBrisket() != null && this.getBrisket().equals(castOther.getBrisket())))
				&& ((this.getBrisketct() == castOther.getBrisketct()) || (this.getBrisketct() != null
						&& castOther.getBrisketct() != null && this.getBrisketct().equals(castOther.getBrisketct())))
				&& (this.getBeefId() == castOther.getBeefId()) && (this.getLiveWeight() == castOther.getLiveWeight())
				&& ((this.getHangingWeight() == castOther.getHangingWeight())
						|| (this.getHangingWeight() != null && castOther.getHangingWeight() != null
								&& this.getHangingWeight().equals(castOther.getHangingWeight())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCounter();
		result = 37 * result + (getFullName() == null ? 0 : this.getFullName().hashCode());
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result + (getTagNumber() == null ? 0 : this.getTagNumber().hashCode());
		result = 37 * result + (getOrder() == null ? 0 : this.getOrder().hashCode());
		result = 37 * result + (getSpecial() == null ? 0 : this.getSpecial().hashCode());
		result = 37 * result + (getSteak() == null ? 0 : this.getSteak().hashCode());
		result = 37 * result + (getShortRibsTp() == null ? 0 : this.getShortRibsTp().hashCode());
		result = 37 * result + (getShortRibs() == null ? 0 : this.getShortRibs().hashCode());
		result = 37 * result + (getShortRibsCt() == null ? 0 : this.getShortRibsCt().hashCode());
		result = 37 * result + (getRoast() == null ? 0 : this.getRoast().hashCode());
		result = 37 * result + (getBoilingBeeftp() == null ? 0 : this.getBoilingBeeftp().hashCode());
		result = 37 * result + (getBoilingBeef() == null ? 0 : this.getBoilingBeef().hashCode());
		result = 37 * result + (getBoilingBeefct() == null ? 0 : this.getBoilingBeefct().hashCode());
		result = 37 * result + this.getSoupBonesTp();
		result = 37 * result + (getSoupBones() == null ? 0 : this.getSoupBones().hashCode());
		result = 37 * result + (getSoupBonesct() == null ? 0 : this.getSoupBonesct().hashCode());
		result = 37 * result + this.getRibTp();
		result = 37 * result + (getRib() == null ? 0 : this.getRib().hashCode());
		result = 37 * result + (getRibct() == null ? 0 : this.getRibct().hashCode());
		result = 37 * result + (getChuckRoasttp() == null ? 0 : this.getChuckRoasttp().hashCode());
		result = 37 * result + (getChuckRoast() == null ? 0 : this.getChuckRoast().hashCode());
		result = 37 * result + (getChuckRoastct() == null ? 0 : this.getChuckRoastct().hashCode());
		result = 37 * result + (getChuckSteaktp() == null ? 0 : this.getChuckSteaktp().hashCode());
		result = 37 * result + (getChuckSteak() == null ? 0 : this.getChuckSteak().hashCode());
		result = 37 * result + (getChuckSteakct() == null ? 0 : this.getChuckSteakct().hashCode());
		result = 37 * result + this.getArmTp();
		result = 37 * result + (getArm() == null ? 0 : this.getArm().hashCode());
		result = 37 * result + (getArmct() == null ? 0 : this.getArmct().hashCode());
		result = 37 * result + this.getSirloinTiptp();
		result = 37 * result + (getSirloinTip() == null ? 0 : this.getSirloinTip().hashCode());
		result = 37 * result + (getSirloinTipct() == null ? 0 : this.getSirloinTipct().hashCode());
		result = 37 * result + this.getTbonetp();
		result = 37 * result + (getTbone() == null ? 0 : this.getTbone().hashCode());
		result = 37 * result + this.getTbonect();
		result = 37 * result + this.getPorterhousetp();
		result = 37 * result + (getPorterhouse() == null ? 0 : this.getPorterhouse().hashCode());
		result = 37 * result + this.getPorterhousect();
		result = 37 * result + this.getSirlointp();
		result = 37 * result + (getSirloin() == null ? 0 : this.getSirloin().hashCode());
		result = 37 * result + this.getSirloinct();
		result = 37 * result + this.getRoundtp();
		result = 37 * result + (getRound() == null ? 0 : this.getRound().hashCode());
		result = 37 * result + this.getRoundct();
		result = 37 * result + (getRump() == null ? 0 : this.getRump().hashCode());
		result = 37 * result + this.getRumpct();
		result = 37 * result + (getPikes() == null ? 0 : this.getPikes().hashCode());
		result = 37 * result + this.getPikesct();
		result = 37 * result + (getStew() == null ? 0 : this.getStew().hashCode());
		result = 37 * result + this.getStewCt();
		result = 37 * result + (getGround() == null ? 0 : this.getGround().hashCode());
		result = 37 * result + (getGroundpk() == null ? 0 : this.getGroundpk().hashCode());
		result = 37 * result + (getGroundct() == null ? 0 : this.getGroundct().hashCode());
		result = 37 * result + (this.isDoubleWrapp() ? 1 : 0);
		result = 37 * result + (getBrisket() == null ? 0 : this.getBrisket().hashCode());
		result = 37 * result + (getBrisketct() == null ? 0 : this.getBrisketct().hashCode());
		result = 37 * result + this.getBeefId();
		result = 37 * result + this.getLiveWeight();
		result = 37 * result + (getHangingWeight() == null ? 0 : this.getHangingWeight().hashCode());
		return result;
	}

}
