package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * Beefweights generated by hbm2java
 */
public class Beefweights implements java.io.Serializable {

	private BeefweightsId id;

	public Beefweights() {
	}

	public Beefweights(BeefweightsId id) {
		this.id = id;
	}

	public BeefweightsId getId() {
		return this.id;
	}

	public void setId(BeefweightsId id) {
		this.id = id;
	}

}
