package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * Beefcutting generated by hbm2java
 */
public class Beefcutting implements java.io.Serializable {

	private BeefcuttingId id;

	public Beefcutting() {
	}

	public Beefcutting(BeefcuttingId id) {
		this.id = id;
	}

	public BeefcuttingId getId() {
		return this.id;
	}

	public void setId(BeefcuttingId id) {
		this.id = id;
	}

}
