package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * Billingold generated by hbm2java
 */
public class Billingold implements java.io.Serializable {

	private BillingoldId id;

	public Billingold() {
	}

	public Billingold(BillingoldId id) {
		this.id = id;
	}

	public BillingoldId getId() {
		return this.id;
	}

	public void setId(BillingoldId id) {
		this.id = id;
	}

}
