package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * Bit generated by hbm2java
 */
public class Bit implements java.io.Serializable {

	private BitId id;

	public Bit() {
	}

	public Bit(BitId id) {
		this.id = id;
	}

	public BitId getId() {
		return this.id;
	}

	public void setId(BitId id) {
		this.id = id;
	}

}
