package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * Breed generated by hbm2java
 */
public class Breed implements java.io.Serializable {

	private Integer id;
	private String breed;

	public Breed() {
	}

	public Breed(String breed) {
		this.breed = breed;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getBreed() {
		return this.breed;
	}

	public void setBreed(String breed) {
		this.breed = breed;
	}

}
