package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

import java.math.BigDecimal;

/**
 * CarryinId generated by hbm2java
 */
public class CarryinId implements java.io.Serializable {

	private long counter;
	private String charge;
	private String weight;
	private BigDecimal amt;
	private String license;
	private String checkStation;

	public CarryinId() {
	}

	public CarryinId(long counter) {
		this.counter = counter;
	}

	public CarryinId(long counter, String charge, String weight, BigDecimal amt, String license, String checkStation) {
		this.counter = counter;
		this.charge = charge;
		this.weight = weight;
		this.amt = amt;
		this.license = license;
		this.checkStation = checkStation;
	}

	public long getCounter() {
		return this.counter;
	}

	public void setCounter(long counter) {
		this.counter = counter;
	}

	public String getCharge() {
		return this.charge;
	}

	public void setCharge(String charge) {
		this.charge = charge;
	}

	public String getWeight() {
		return this.weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

	public BigDecimal getAmt() {
		return this.amt;
	}

	public void setAmt(BigDecimal amt) {
		this.amt = amt;
	}

	public String getLicense() {
		return this.license;
	}

	public void setLicense(String license) {
		this.license = license;
	}

	public String getCheckStation() {
		return this.checkStation;
	}

	public void setCheckStation(String checkStation) {
		this.checkStation = checkStation;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CarryinId))
			return false;
		CarryinId castOther = (CarryinId) other;

		return (this.getCounter() == castOther.getCounter())
				&& ((this.getCharge() == castOther.getCharge()) || (this.getCharge() != null
						&& castOther.getCharge() != null && this.getCharge().equals(castOther.getCharge())))
				&& ((this.getWeight() == castOther.getWeight()) || (this.getWeight() != null
						&& castOther.getWeight() != null && this.getWeight().equals(castOther.getWeight())))
				&& ((this.getAmt() == castOther.getAmt()) || (this.getAmt() != null && castOther.getAmt() != null
						&& this.getAmt().equals(castOther.getAmt())))
				&& ((this.getLicense() == castOther.getLicense()) || (this.getLicense() != null
						&& castOther.getLicense() != null && this.getLicense().equals(castOther.getLicense())))
				&& ((this.getCheckStation() == castOther.getCheckStation())
						|| (this.getCheckStation() != null && castOther.getCheckStation() != null
								&& this.getCheckStation().equals(castOther.getCheckStation())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCounter();
		result = 37 * result + (getCharge() == null ? 0 : this.getCharge().hashCode());
		result = 37 * result + (getWeight() == null ? 0 : this.getWeight().hashCode());
		result = 37 * result + (getAmt() == null ? 0 : this.getAmt().hashCode());
		result = 37 * result + (getLicense() == null ? 0 : this.getLicense().hashCode());
		result = 37 * result + (getCheckStation() == null ? 0 : this.getCheckStation().hashCode());
		return result;
	}

}
