package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * Carryin generated by hbm2java
 */
public class Carryin implements java.io.Serializable {

	private CarryinId id;

	public Carryin() {
	}

	public Carryin(CarryinId id) {
		this.id = id;
	}

	public CarryinId getId() {
		return this.id;
	}

	public void setId(CarryinId id) {
		this.id = id;
	}

}
