package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * Cellinfo generated by hbm2java
 */
public class Cellinfo implements java.io.Serializable {

	private CellinfoId id;

	public Cellinfo() {
	}

	public Cellinfo(CellinfoId id) {
		this.id = id;
	}

	public CellinfoId getId() {
		return this.id;
	}

	public void setId(CellinfoId id) {
		this.id = id;
	}

}
