package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * CellinfoId generated by hbm2java
 */
public class CellinfoId implements java.io.Serializable {

	private int customerId;
	private String cellPhone;
	private String carrier;
	private boolean sendText;
	private boolean sendEmail;

	public CellinfoId() {
	}

	public CellinfoId(int customerId, String cellPhone, String carrier, boolean sendText, boolean sendEmail) {
		this.customerId = customerId;
		this.cellPhone = cellPhone;
		this.carrier = carrier;
		this.sendText = sendText;
		this.sendEmail = sendEmail;
	}

	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	public String getCellPhone() {
		return this.cellPhone;
	}

	public void setCellPhone(String cellPhone) {
		this.cellPhone = cellPhone;
	}

	public String getCarrier() {
		return this.carrier;
	}

	public void setCarrier(String carrier) {
		this.carrier = carrier;
	}

	public boolean isSendText() {
		return this.sendText;
	}

	public void setSendText(boolean sendText) {
		this.sendText = sendText;
	}

	public boolean isSendEmail() {
		return this.sendEmail;
	}

	public void setSendEmail(boolean sendEmail) {
		this.sendEmail = sendEmail;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CellinfoId))
			return false;
		CellinfoId castOther = (CellinfoId) other;

		return (this.getCustomerId() == castOther.getCustomerId())
				&& ((this.getCellPhone() == castOther.getCellPhone()) || (this.getCellPhone() != null
						&& castOther.getCellPhone() != null && this.getCellPhone().equals(castOther.getCellPhone())))
				&& ((this.getCarrier() == castOther.getCarrier()) || (this.getCarrier() != null
						&& castOther.getCarrier() != null && this.getCarrier().equals(castOther.getCarrier())))
				&& (this.isSendText() == castOther.isSendText()) && (this.isSendEmail() == castOther.isSendEmail());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCustomerId();
		result = 37 * result + (getCellPhone() == null ? 0 : this.getCellPhone().hashCode());
		result = 37 * result + (getCarrier() == null ? 0 : this.getCarrier().hashCode());
		result = 37 * result + (this.isSendText() ? 1 : 0);
		result = 37 * result + (this.isSendEmail() ? 1 : 0);
		return result;
	}

}
