package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

import java.math.BigDecimal;

/**
 * Charges1Id generated by hbm2java
 */
public class Charges1Id implements java.io.Serializable {

	private String myItem;
	private BigDecimal cost;
	private String category;

	public Charges1Id() {
	}

	public Charges1Id(String myItem, BigDecimal cost, String category) {
		this.myItem = myItem;
		this.cost = cost;
		this.category = category;
	}

	public String getMyItem() {
		return this.myItem;
	}

	public void setMyItem(String myItem) {
		this.myItem = myItem;
	}

	public BigDecimal getCost() {
		return this.cost;
	}

	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Charges1Id))
			return false;
		Charges1Id castOther = (Charges1Id) other;

		return ((this.getMyItem() == castOther.getMyItem()) || (this.getMyItem() != null
				&& castOther.getMyItem() != null && this.getMyItem().equals(castOther.getMyItem())))
				&& ((this.getCost() == castOther.getCost()) || (this.getCost() != null && castOther.getCost() != null
						&& this.getCost().equals(castOther.getCost())))
				&& ((this.getCategory() == castOther.getCategory()) || (this.getCategory() != null
						&& castOther.getCategory() != null && this.getCategory().equals(castOther.getCategory())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMyItem() == null ? 0 : this.getMyItem().hashCode());
		result = 37 * result + (getCost() == null ? 0 : this.getCost().hashCode());
		result = 37 * result + (getCategory() == null ? 0 : this.getCategory().hashCode());
		return result;
	}

}
