package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * Charges1 generated by hbm2java
 */
public class Charges1 implements java.io.Serializable {

	private Charges1Id id;

	public Charges1() {
	}

	public Charges1(Charges1Id id) {
		this.id = id;
	}

	public Charges1Id getId() {
		return this.id;
	}

	public void setId(Charges1Id id) {
		this.id = id;
	}

}
