package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * Charges2 generated by hbm2java
 */
public class Charges2 implements java.io.Serializable {

	private Charges2Id id;

	public Charges2() {
	}

	public Charges2(Charges2Id id) {
		this.id = id;
	}

	public Charges2Id getId() {
		return this.id;
	}

	public void setId(Charges2Id id) {
		this.id = id;
	}

}
