package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * Condit generated by hbm2java
 */
public class Condit implements java.io.Serializable {

	private Integer id;
	private String condit;

	public Condit() {
	}

	public Condit(String condit) {
		this.condit = condit;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCondit() {
		return this.condit;
	}

	public void setCondit(String condit) {
		this.condit = condit;
	}

}
