package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Cool generated by hbm2java
 */
public class Cool implements java.io.Serializable {

	private Integer boxNumber;
	private String establishmentNumber;
	private String lotNumber;
	private Date productionDate;
	private String productionTime;
	private String primal;
	private Date dateRecieved;
	private String weight;
	private BigDecimal ppp;

	public Cool() {
	}

	public Cool(String establishmentNumber, String lotNumber, String primal, Date dateRecieved) {
		this.establishmentNumber = establishmentNumber;
		this.lotNumber = lotNumber;
		this.primal = primal;
		this.dateRecieved = dateRecieved;
	}

	public Cool(String establishmentNumber, String lotNumber, Date productionDate, String productionTime, String primal,
			Date dateRecieved, String weight, BigDecimal ppp) {
		this.establishmentNumber = establishmentNumber;
		this.lotNumber = lotNumber;
		this.productionDate = productionDate;
		this.productionTime = productionTime;
		this.primal = primal;
		this.dateRecieved = dateRecieved;
		this.weight = weight;
		this.ppp = ppp;
	}

	public Integer getBoxNumber() {
		return this.boxNumber;
	}

	public void setBoxNumber(Integer boxNumber) {
		this.boxNumber = boxNumber;
	}

	public String getEstablishmentNumber() {
		return this.establishmentNumber;
	}

	public void setEstablishmentNumber(String establishmentNumber) {
		this.establishmentNumber = establishmentNumber;
	}

	public String getLotNumber() {
		return this.lotNumber;
	}

	public void setLotNumber(String lotNumber) {
		this.lotNumber = lotNumber;
	}

	public Date getProductionDate() {
		return this.productionDate;
	}

	public void setProductionDate(Date productionDate) {
		this.productionDate = productionDate;
	}

	public String getProductionTime() {
		return this.productionTime;
	}

	public void setProductionTime(String productionTime) {
		this.productionTime = productionTime;
	}

	public String getPrimal() {
		return this.primal;
	}

	public void setPrimal(String primal) {
		this.primal = primal;
	}

	public Date getDateRecieved() {
		return this.dateRecieved;
	}

	public void setDateRecieved(Date dateRecieved) {
		this.dateRecieved = dateRecieved;
	}

	public String getWeight() {
		return this.weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

	public BigDecimal getPpp() {
		return this.ppp;
	}

	public void setPpp(BigDecimal ppp) {
		this.ppp = ppp;
	}

}
