package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Cuttingtest generated by hbm2java
 */
public class Cuttingtest implements java.io.Serializable {

	private Integer id;
	private String boxNumber;
	private BigDecimal totalCost;
	private BigDecimal weightToTest;
	private BigDecimal cost;
	private BigDecimal finalWeight;
	private BigDecimal loss;
	private BigDecimal costToSell;
	private String markUp;
	private BigDecimal pricePerLb;
	private Date date;
	private String primal;

	public Cuttingtest() {
	}

	public Cuttingtest(String boxNumber, BigDecimal totalCost, BigDecimal weightToTest, BigDecimal cost,
			BigDecimal finalWeight, BigDecimal loss, BigDecimal costToSell, String markUp, BigDecimal pricePerLb,
			Date date, String primal) {
		this.boxNumber = boxNumber;
		this.totalCost = totalCost;
		this.weightToTest = weightToTest;
		this.cost = cost;
		this.finalWeight = finalWeight;
		this.loss = loss;
		this.costToSell = costToSell;
		this.markUp = markUp;
		this.pricePerLb = pricePerLb;
		this.date = date;
		this.primal = primal;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getBoxNumber() {
		return this.boxNumber;
	}

	public void setBoxNumber(String boxNumber) {
		this.boxNumber = boxNumber;
	}

	public BigDecimal getTotalCost() {
		return this.totalCost;
	}

	public void setTotalCost(BigDecimal totalCost) {
		this.totalCost = totalCost;
	}

	public BigDecimal getWeightToTest() {
		return this.weightToTest;
	}

	public void setWeightToTest(BigDecimal weightToTest) {
		this.weightToTest = weightToTest;
	}

	public BigDecimal getCost() {
		return this.cost;
	}

	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

	public BigDecimal getFinalWeight() {
		return this.finalWeight;
	}

	public void setFinalWeight(BigDecimal finalWeight) {
		this.finalWeight = finalWeight;
	}

	public BigDecimal getLoss() {
		return this.loss;
	}

	public void setLoss(BigDecimal loss) {
		this.loss = loss;
	}

	public BigDecimal getCostToSell() {
		return this.costToSell;
	}

	public void setCostToSell(BigDecimal costToSell) {
		this.costToSell = costToSell;
	}

	public String getMarkUp() {
		return this.markUp;
	}

	public void setMarkUp(String markUp) {
		this.markUp = markUp;
	}

	public BigDecimal getPricePerLb() {
		return this.pricePerLb;
	}

	public void setPricePerLb(BigDecimal pricePerLb) {
		this.pricePerLb = pricePerLb;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getPrimal() {
		return this.primal;
	}

	public void setPrimal(String primal) {
		this.primal = primal;
	}

}
