package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * DeerId generated by hbm2java
 */
public class DeerId implements java.io.Serializable {

	private Double id;
	private String fullName;
	private String license;
	private String checkStation;

	public DeerId() {
	}

	public DeerId(String fullName) {
		this.fullName = fullName;
	}

	public DeerId(Double id, String fullName, String license, String checkStation) {
		this.id = id;
		this.fullName = fullName;
		this.license = license;
		this.checkStation = checkStation;
	}

	public Double getId() {
		return this.id;
	}

	public void setId(Double id) {
		this.id = id;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getLicense() {
		return this.license;
	}

	public void setLicense(String license) {
		this.license = license;
	}

	public String getCheckStation() {
		return this.checkStation;
	}

	public void setCheckStation(String checkStation) {
		this.checkStation = checkStation;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DeerId))
			return false;
		DeerId castOther = (DeerId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getFullName() == castOther.getFullName()) || (this.getFullName() != null
						&& castOther.getFullName() != null && this.getFullName().equals(castOther.getFullName())))
				&& ((this.getLicense() == castOther.getLicense()) || (this.getLicense() != null
						&& castOther.getLicense() != null && this.getLicense().equals(castOther.getLicense())))
				&& ((this.getCheckStation() == castOther.getCheckStation())
						|| (this.getCheckStation() != null && castOther.getCheckStation() != null
								&& this.getCheckStation().equals(castOther.getCheckStation())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getFullName() == null ? 0 : this.getFullName().hashCode());
		result = 37 * result + (getLicense() == null ? 0 : this.getLicense().hashCode());
		result = 37 * result + (getCheckStation() == null ? 0 : this.getCheckStation().hashCode());
		return result;
	}

}
