package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * Deercuttingorder generated by hbm2java
 */
public class Deercuttingorder implements java.io.Serializable {

	private DeercuttingorderId id;

	public Deercuttingorder() {
	}

	public Deercuttingorder(DeercuttingorderId id) {
		this.id = id;
	}

	public DeercuttingorderId getId() {
		return this.id;
	}

	public void setId(DeercuttingorderId id) {
		this.id = id;
	}

}
