package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * Deer generated by hbm2java
 */
public class Deer implements java.io.Serializable {

	private DeerId id;

	public Deer() {
	}

	public Deer(DeerId id) {
		this.id = id;
	}

	public DeerId getId() {
		return this.id;
	}

	public void setId(DeerId id) {
		this.id = id;
	}

}
