package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * DeercuttingorderId generated by hbm2java
 */
public class DeercuttingorderId implements java.io.Serializable {

	private String counter;
	private String fullName;
	private String chops;
	private String steaks;
	private String roasts;
	private String ground;
	private String groundPkg;
	private String written;
	private Boolean bsausages;
	private String sausagePercents1;
	private String sp1;
	private String sausagePercents2;
	private String sp2;
	private String sausagePercents3;
	private String sp3;

	public DeercuttingorderId() {
	}

	public DeercuttingorderId(String counter) {
		this.counter = counter;
	}

	public DeercuttingorderId(String counter, String fullName, String chops, String steaks, String roasts,
			String ground, String groundPkg, String written, Boolean bsausages, String sausagePercents1, String sp1,
			String sausagePercents2, String sp2, String sausagePercents3, String sp3) {
		this.counter = counter;
		this.fullName = fullName;
		this.chops = chops;
		this.steaks = steaks;
		this.roasts = roasts;
		this.ground = ground;
		this.groundPkg = groundPkg;
		this.written = written;
		this.bsausages = bsausages;
		this.sausagePercents1 = sausagePercents1;
		this.sp1 = sp1;
		this.sausagePercents2 = sausagePercents2;
		this.sp2 = sp2;
		this.sausagePercents3 = sausagePercents3;
		this.sp3 = sp3;
	}

	public String getCounter() {
		return this.counter;
	}

	public void setCounter(String counter) {
		this.counter = counter;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getChops() {
		return this.chops;
	}

	public void setChops(String chops) {
		this.chops = chops;
	}

	public String getSteaks() {
		return this.steaks;
	}

	public void setSteaks(String steaks) {
		this.steaks = steaks;
	}

	public String getRoasts() {
		return this.roasts;
	}

	public void setRoasts(String roasts) {
		this.roasts = roasts;
	}

	public String getGround() {
		return this.ground;
	}

	public void setGround(String ground) {
		this.ground = ground;
	}

	public String getGroundPkg() {
		return this.groundPkg;
	}

	public void setGroundPkg(String groundPkg) {
		this.groundPkg = groundPkg;
	}

	public String getWritten() {
		return this.written;
	}

	public void setWritten(String written) {
		this.written = written;
	}

	public Boolean getBsausages() {
		return this.bsausages;
	}

	public void setBsausages(Boolean bsausages) {
		this.bsausages = bsausages;
	}

	public String getSausagePercents1() {
		return this.sausagePercents1;
	}

	public void setSausagePercents1(String sausagePercents1) {
		this.sausagePercents1 = sausagePercents1;
	}

	public String getSp1() {
		return this.sp1;
	}

	public void setSp1(String sp1) {
		this.sp1 = sp1;
	}

	public String getSausagePercents2() {
		return this.sausagePercents2;
	}

	public void setSausagePercents2(String sausagePercents2) {
		this.sausagePercents2 = sausagePercents2;
	}

	public String getSp2() {
		return this.sp2;
	}

	public void setSp2(String sp2) {
		this.sp2 = sp2;
	}

	public String getSausagePercents3() {
		return this.sausagePercents3;
	}

	public void setSausagePercents3(String sausagePercents3) {
		this.sausagePercents3 = sausagePercents3;
	}

	public String getSp3() {
		return this.sp3;
	}

	public void setSp3(String sp3) {
		this.sp3 = sp3;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DeercuttingorderId))
			return false;
		DeercuttingorderId castOther = (DeercuttingorderId) other;

		return ((this.getCounter() == castOther.getCounter()) || (this.getCounter() != null
				&& castOther.getCounter() != null && this.getCounter().equals(castOther.getCounter())))
				&& ((this.getFullName() == castOther.getFullName()) || (this.getFullName() != null
						&& castOther.getFullName() != null && this.getFullName().equals(castOther.getFullName())))
				&& ((this.getChops() == castOther.getChops()) || (this.getChops() != null
						&& castOther.getChops() != null && this.getChops().equals(castOther.getChops())))
				&& ((this.getSteaks() == castOther.getSteaks()) || (this.getSteaks() != null
						&& castOther.getSteaks() != null && this.getSteaks().equals(castOther.getSteaks())))
				&& ((this.getRoasts() == castOther.getRoasts()) || (this.getRoasts() != null
						&& castOther.getRoasts() != null && this.getRoasts().equals(castOther.getRoasts())))
				&& ((this.getGround() == castOther.getGround()) || (this.getGround() != null
						&& castOther.getGround() != null && this.getGround().equals(castOther.getGround())))
				&& ((this.getGroundPkg() == castOther.getGroundPkg()) || (this.getGroundPkg() != null
						&& castOther.getGroundPkg() != null && this.getGroundPkg().equals(castOther.getGroundPkg())))
				&& ((this.getWritten() == castOther.getWritten()) || (this.getWritten() != null
						&& castOther.getWritten() != null && this.getWritten().equals(castOther.getWritten())))
				&& ((this.getBsausages() == castOther.getBsausages()) || (this.getBsausages() != null
						&& castOther.getBsausages() != null && this.getBsausages().equals(castOther.getBsausages())))
				&& ((this.getSausagePercents1() == castOther.getSausagePercents1())
						|| (this.getSausagePercents1() != null && castOther.getSausagePercents1() != null
								&& this.getSausagePercents1().equals(castOther.getSausagePercents1())))
				&& ((this.getSp1() == castOther.getSp1()) || (this.getSp1() != null && castOther.getSp1() != null
						&& this.getSp1().equals(castOther.getSp1())))
				&& ((this.getSausagePercents2() == castOther.getSausagePercents2())
						|| (this.getSausagePercents2() != null && castOther.getSausagePercents2() != null
								&& this.getSausagePercents2().equals(castOther.getSausagePercents2())))
				&& ((this.getSp2() == castOther.getSp2()) || (this.getSp2() != null && castOther.getSp2() != null
						&& this.getSp2().equals(castOther.getSp2())))
				&& ((this.getSausagePercents3() == castOther.getSausagePercents3())
						|| (this.getSausagePercents3() != null && castOther.getSausagePercents3() != null
								&& this.getSausagePercents3().equals(castOther.getSausagePercents3())))
				&& ((this.getSp3() == castOther.getSp3()) || (this.getSp3() != null && castOther.getSp3() != null
						&& this.getSp3().equals(castOther.getSp3())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCounter() == null ? 0 : this.getCounter().hashCode());
		result = 37 * result + (getFullName() == null ? 0 : this.getFullName().hashCode());
		result = 37 * result + (getChops() == null ? 0 : this.getChops().hashCode());
		result = 37 * result + (getSteaks() == null ? 0 : this.getSteaks().hashCode());
		result = 37 * result + (getRoasts() == null ? 0 : this.getRoasts().hashCode());
		result = 37 * result + (getGround() == null ? 0 : this.getGround().hashCode());
		result = 37 * result + (getGroundPkg() == null ? 0 : this.getGroundPkg().hashCode());
		result = 37 * result + (getWritten() == null ? 0 : this.getWritten().hashCode());
		result = 37 * result + (getBsausages() == null ? 0 : this.getBsausages().hashCode());
		result = 37 * result + (getSausagePercents1() == null ? 0 : this.getSausagePercents1().hashCode());
		result = 37 * result + (getSp1() == null ? 0 : this.getSp1().hashCode());
		result = 37 * result + (getSausagePercents2() == null ? 0 : this.getSausagePercents2().hashCode());
		result = 37 * result + (getSp2() == null ? 0 : this.getSp2().hashCode());
		result = 37 * result + (getSausagePercents3() == null ? 0 : this.getSausagePercents3().hashCode());
		result = 37 * result + (getSp3() == null ? 0 : this.getSp3().hashCode());
		return result;
	}

}
