package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * History generated by hbm2java
 */
public class History implements java.io.Serializable {

	private Integer counter;
	private String lockerNumber;
	private String fullName;
	private Date dateDue;
	private BigDecimal amountPaid;
	private Double rate;
	private Double numberOfLockers;
	private Date todaysDate;
	private String checkNumber;
	private boolean ztill;

	public History() {
	}

	public History(String lockerNumber, boolean ztill) {
		this.lockerNumber = lockerNumber;
		this.ztill = ztill;
	}

	public History(String lockerNumber, String fullName, Date dateDue, BigDecimal amountPaid, Double rate,
			Double numberOfLockers, Date todaysDate, String checkNumber, boolean ztill) {
		this.lockerNumber = lockerNumber;
		this.fullName = fullName;
		this.dateDue = dateDue;
		this.amountPaid = amountPaid;
		this.rate = rate;
		this.numberOfLockers = numberOfLockers;
		this.todaysDate = todaysDate;
		this.checkNumber = checkNumber;
		this.ztill = ztill;
	}

	public Integer getCounter() {
		return this.counter;
	}

	public void setCounter(Integer counter) {
		this.counter = counter;
	}

	public String getLockerNumber() {
		return this.lockerNumber;
	}

	public void setLockerNumber(String lockerNumber) {
		this.lockerNumber = lockerNumber;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public Date getDateDue() {
		return this.dateDue;
	}

	public void setDateDue(Date dateDue) {
		this.dateDue = dateDue;
	}

	public BigDecimal getAmountPaid() {
		return this.amountPaid;
	}

	public void setAmountPaid(BigDecimal amountPaid) {
		this.amountPaid = amountPaid;
	}

	public Double getRate() {
		return this.rate;
	}

	public void setRate(Double rate) {
		this.rate = rate;
	}

	public Double getNumberOfLockers() {
		return this.numberOfLockers;
	}

	public void setNumberOfLockers(Double numberOfLockers) {
		this.numberOfLockers = numberOfLockers;
	}

	public Date getTodaysDate() {
		return this.todaysDate;
	}

	public void setTodaysDate(Date todaysDate) {
		this.todaysDate = todaysDate;
	}

	public String getCheckNumber() {
		return this.checkNumber;
	}

	public void setCheckNumber(String checkNumber) {
		this.checkNumber = checkNumber;
	}

	public boolean isZtill() {
		return this.ztill;
	}

	public void setZtill(boolean ztill) {
		this.ztill = ztill;
	}

}
