package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * IngredientsId generated by hbm2java
 */
public class IngredientsId implements java.io.Serializable {

	private int id;
	private String name;
	private String amount;
	private String supplier;
	private Double inventory;

	public IngredientsId() {
	}

	public IngredientsId(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public IngredientsId(int id, String name, String amount, String supplier, Double inventory) {
		this.id = id;
		this.name = name;
		this.amount = amount;
		this.supplier = supplier;
		this.inventory = inventory;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAmount() {
		return this.amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	public String getSupplier() {
		return this.supplier;
	}

	public void setSupplier(String supplier) {
		this.supplier = supplier;
	}

	public Double getInventory() {
		return this.inventory;
	}

	public void setInventory(Double inventory) {
		this.inventory = inventory;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IngredientsId))
			return false;
		IngredientsId castOther = (IngredientsId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getAmount() == castOther.getAmount()) || (this.getAmount() != null
						&& castOther.getAmount() != null && this.getAmount().equals(castOther.getAmount())))
				&& ((this.getSupplier() == castOther.getSupplier()) || (this.getSupplier() != null
						&& castOther.getSupplier() != null && this.getSupplier().equals(castOther.getSupplier())))
				&& ((this.getInventory() == castOther.getInventory()) || (this.getInventory() != null
						&& castOther.getInventory() != null && this.getInventory().equals(castOther.getInventory())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getAmount() == null ? 0 : this.getAmount().hashCode());
		result = 37 * result + (getSupplier() == null ? 0 : this.getSupplier().hashCode());
		result = 37 * result + (getInventory() == null ? 0 : this.getInventory().hashCode());
		return result;
	}

}
