package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * Ingredients generated by hbm2java
 */
public class Ingredients implements java.io.Serializable {

	private IngredientsId id;

	public Ingredients() {
	}

	public Ingredients(IngredientsId id) {
		this.id = id;
	}

	public IngredientsId getId() {
		return this.id;
	}

	public void setId(IngredientsId id) {
		this.id = id;
	}

}
