package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Locker generated by hbm2java
 */
public class Locker implements java.io.Serializable {

	private double preference;
	private String lockerNumber;
	private String firstName;
	private String lastName;
	private String fullName;
	private Double timeDue;
	private Date dateDue;
	private Double amountPaid;
	private Double rate;
	private Double numberOfLockers;
	private Date todaysDate;
	private Double amountDue;
	private Date lastTransaction;
	private String amountOfLast;
	private Date lastDateDue;
	private Date secondLast;
	private BigDecimal secondLastAmmount;
	private Date secondLastDateDue;
	private String locker1;
	private String locker2;
	private String locker3;
	private String locker4;
	private String locker5;
	private String locker6;
	private String locker7;
	private boolean aflag;
	private boolean each;
	private boolean print;

	public Locker() {
	}

	public Locker(double preference, String lockerNumber, boolean aflag, boolean each, boolean print) {
		this.preference = preference;
		this.lockerNumber = lockerNumber;
		this.aflag = aflag;
		this.each = each;
		this.print = print;
	}

	public Locker(double preference, String lockerNumber, String firstName, String lastName, String fullName,
			Double timeDue, Date dateDue, Double amountPaid, Double rate, Double numberOfLockers, Date todaysDate,
			Double amountDue, Date lastTransaction, String amountOfLast, Date lastDateDue, Date secondLast,
			BigDecimal secondLastAmmount, Date secondLastDateDue, String locker1, String locker2, String locker3,
			String locker4, String locker5, String locker6, String locker7, boolean aflag, boolean each,
			boolean print) {
		this.preference = preference;
		this.lockerNumber = lockerNumber;
		this.firstName = firstName;
		this.lastName = lastName;
		this.fullName = fullName;
		this.timeDue = timeDue;
		this.dateDue = dateDue;
		this.amountPaid = amountPaid;
		this.rate = rate;
		this.numberOfLockers = numberOfLockers;
		this.todaysDate = todaysDate;
		this.amountDue = amountDue;
		this.lastTransaction = lastTransaction;
		this.amountOfLast = amountOfLast;
		this.lastDateDue = lastDateDue;
		this.secondLast = secondLast;
		this.secondLastAmmount = secondLastAmmount;
		this.secondLastDateDue = secondLastDateDue;
		this.locker1 = locker1;
		this.locker2 = locker2;
		this.locker3 = locker3;
		this.locker4 = locker4;
		this.locker5 = locker5;
		this.locker6 = locker6;
		this.locker7 = locker7;
		this.aflag = aflag;
		this.each = each;
		this.print = print;
	}

	public double getPreference() {
		return this.preference;
	}

	public void setPreference(double preference) {
		this.preference = preference;
	}

	public String getLockerNumber() {
		return this.lockerNumber;
	}

	public void setLockerNumber(String lockerNumber) {
		this.lockerNumber = lockerNumber;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public Double getTimeDue() {
		return this.timeDue;
	}

	public void setTimeDue(Double timeDue) {
		this.timeDue = timeDue;
	}

	public Date getDateDue() {
		return this.dateDue;
	}

	public void setDateDue(Date dateDue) {
		this.dateDue = dateDue;
	}

	public Double getAmountPaid() {
		return this.amountPaid;
	}

	public void setAmountPaid(Double amountPaid) {
		this.amountPaid = amountPaid;
	}

	public Double getRate() {
		return this.rate;
	}

	public void setRate(Double rate) {
		this.rate = rate;
	}

	public Double getNumberOfLockers() {
		return this.numberOfLockers;
	}

	public void setNumberOfLockers(Double numberOfLockers) {
		this.numberOfLockers = numberOfLockers;
	}

	public Date getTodaysDate() {
		return this.todaysDate;
	}

	public void setTodaysDate(Date todaysDate) {
		this.todaysDate = todaysDate;
	}

	public Double getAmountDue() {
		return this.amountDue;
	}

	public void setAmountDue(Double amountDue) {
		this.amountDue = amountDue;
	}

	public Date getLastTransaction() {
		return this.lastTransaction;
	}

	public void setLastTransaction(Date lastTransaction) {
		this.lastTransaction = lastTransaction;
	}

	public String getAmountOfLast() {
		return this.amountOfLast;
	}

	public void setAmountOfLast(String amountOfLast) {
		this.amountOfLast = amountOfLast;
	}

	public Date getLastDateDue() {
		return this.lastDateDue;
	}

	public void setLastDateDue(Date lastDateDue) {
		this.lastDateDue = lastDateDue;
	}

	public Date getSecondLast() {
		return this.secondLast;
	}

	public void setSecondLast(Date secondLast) {
		this.secondLast = secondLast;
	}

	public BigDecimal getSecondLastAmmount() {
		return this.secondLastAmmount;
	}

	public void setSecondLastAmmount(BigDecimal secondLastAmmount) {
		this.secondLastAmmount = secondLastAmmount;
	}

	public Date getSecondLastDateDue() {
		return this.secondLastDateDue;
	}

	public void setSecondLastDateDue(Date secondLastDateDue) {
		this.secondLastDateDue = secondLastDateDue;
	}

	public String getLocker1() {
		return this.locker1;
	}

	public void setLocker1(String locker1) {
		this.locker1 = locker1;
	}

	public String getLocker2() {
		return this.locker2;
	}

	public void setLocker2(String locker2) {
		this.locker2 = locker2;
	}

	public String getLocker3() {
		return this.locker3;
	}

	public void setLocker3(String locker3) {
		this.locker3 = locker3;
	}

	public String getLocker4() {
		return this.locker4;
	}

	public void setLocker4(String locker4) {
		this.locker4 = locker4;
	}

	public String getLocker5() {
		return this.locker5;
	}

	public void setLocker5(String locker5) {
		this.locker5 = locker5;
	}

	public String getLocker6() {
		return this.locker6;
	}

	public void setLocker6(String locker6) {
		this.locker6 = locker6;
	}

	public String getLocker7() {
		return this.locker7;
	}

	public void setLocker7(String locker7) {
		this.locker7 = locker7;
	}

	public boolean isAflag() {
		return this.aflag;
	}

	public void setAflag(boolean aflag) {
		this.aflag = aflag;
	}

	public boolean isEach() {
		return this.each;
	}

	public void setEach(boolean each) {
		this.each = each;
	}

	public boolean isPrint() {
		return this.print;
	}

	public void setPrint(boolean print) {
		this.print = print;
	}

}
