package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;

/**
 * Lockerrentagreement generated by hbm2java
 */
public class Lockerrentagreement implements java.io.Serializable {

	private int customerId;
	private boolean agreementOnFile;
	private String verifiedBy;
	private Date vdate;

	public Lockerrentagreement() {
	}

	public Lockerrentagreement(int customerId, boolean agreementOnFile) {
		this.customerId = customerId;
		this.agreementOnFile = agreementOnFile;
	}

	public Lockerrentagreement(int customerId, boolean agreementOnFile, String verifiedBy, Date vdate) {
		this.customerId = customerId;
		this.agreementOnFile = agreementOnFile;
		this.verifiedBy = verifiedBy;
		this.vdate = vdate;
	}

	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	public boolean isAgreementOnFile() {
		return this.agreementOnFile;
	}

	public void setAgreementOnFile(boolean agreementOnFile) {
		this.agreementOnFile = agreementOnFile;
	}

	public String getVerifiedBy() {
		return this.verifiedBy;
	}

	public void setVerifiedBy(String verifiedBy) {
		this.verifiedBy = verifiedBy;
	}

	public Date getVdate() {
		return this.vdate;
	}

	public void setVdate(Date vdate) {
		this.vdate = vdate;
	}

}
