package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * Lockerold generated by hbm2java
 */
public class Lockerold implements java.io.Serializable {

	private LockeroldId id;

	public Lockerold() {
	}

	public Lockerold(LockeroldId id) {
		this.id = id;
	}

	public LockeroldId getId() {
		return this.id;
	}

	public void setId(LockeroldId id) {
		this.id = id;
	}

}
