package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * Msg generated by hbm2java
 */
public class Msg implements java.io.Serializable {

	private MsgId id;

	public Msg() {
	}

	public Msg(MsgId id) {
		this.id = id;
	}

	public MsgId getId() {
		return this.id;
	}

	public void setId(MsgId id) {
		this.id = id;
	}

}
