package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * MsgId generated by hbm2java
 */
public class MsgId implements java.io.Serializable {

	private Boolean msg;
	private int counter;

	public MsgId() {
	}

	public MsgId(int counter) {
		this.counter = counter;
	}

	public MsgId(Boolean msg, int counter) {
		this.msg = msg;
		this.counter = counter;
	}

	public Boolean getMsg() {
		return this.msg;
	}

	public void setMsg(Boolean msg) {
		this.msg = msg;
	}

	public int getCounter() {
		return this.counter;
	}

	public void setCounter(int counter) {
		this.counter = counter;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MsgId))
			return false;
		MsgId castOther = (MsgId) other;

		return ((this.getMsg() == castOther.getMsg())
				|| (this.getMsg() != null && castOther.getMsg() != null && this.getMsg().equals(castOther.getMsg())))
				&& (this.getCounter() == castOther.getCounter());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMsg() == null ? 0 : this.getMsg().hashCode());
		result = 37 * result + this.getCounter();
		return result;
	}

}
