package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

import java.math.BigDecimal;

/**
 * Notes generated by hbm2java
 */
public class Notes implements java.io.Serializable {

	private Integer counter;
	private String customerId;
	private String note;
	private BigDecimal amount;

	public Notes() {
	}

	public Notes(String customerId) {
		this.customerId = customerId;
	}

	public Notes(String customerId, String note, BigDecimal amount) {
		this.customerId = customerId;
		this.note = note;
		this.amount = amount;
	}

	public Integer getCounter() {
		return this.counter;
	}

	public void setCounter(Integer counter) {
		this.counter = counter;
	}

	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

}
