package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * Paidout generated by hbm2java
 */
public class Paidout implements java.io.Serializable {

	private PaidoutId id;

	public Paidout() {
	}

	public Paidout(PaidoutId id) {
		this.id = id;
	}

	public PaidoutId getId() {
		return this.id;
	}

	public void setId(PaidoutId id) {
		this.id = id;
	}

}
