package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * Pastsqls generated by hbm2java
 */
public class Pastsqls implements java.io.Serializable {

	private PastsqlsId id;

	public Pastsqls() {
	}

	public Pastsqls(PastsqlsId id) {
		this.id = id;
	}

	public PastsqlsId getId() {
		return this.id;
	}

	public void setId(PastsqlsId id) {
		this.id = id;
	}

}
