package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * PastsqlsId generated by hbm2java
 */
public class PastsqlsId implements java.io.Serializable {

	private int counter;
	private String sql;

	public PastsqlsId() {
	}

	public PastsqlsId(int counter) {
		this.counter = counter;
	}

	public PastsqlsId(int counter, String sql) {
		this.counter = counter;
		this.sql = sql;
	}

	public int getCounter() {
		return this.counter;
	}

	public void setCounter(int counter) {
		this.counter = counter;
	}

	public String getSql() {
		return this.sql;
	}

	public void setSql(String sql) {
		this.sql = sql;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PastsqlsId))
			return false;
		PastsqlsId castOther = (PastsqlsId) other;

		return (this.getCounter() == castOther.getCounter()) && ((this.getSql() == castOther.getSql())
				|| (this.getSql() != null && castOther.getSql() != null && this.getSql().equals(castOther.getSql())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCounter();
		result = 37 * result + (getSql() == null ? 0 : this.getSql().hashCode());
		return result;
	}

}
