package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * Porkcutting generated by hbm2java
 */
public class Porkcutting implements java.io.Serializable {

	private PorkcuttingId id;

	public Porkcutting() {
	}

	public Porkcutting(PorkcuttingId id) {
		this.id = id;
	}

	public PorkcuttingId getId() {
		return this.id;
	}

	public void setId(PorkcuttingId id) {
		this.id = id;
	}

}
