package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;

/**
 * PorkcuttingId generated by hbm2java
 */
public class PorkcuttingId implements java.io.Serializable {

	private int counter;
	private int beefId;
	private String name;
	private Date deliveryDate;
	private String chops;
	private String picnic;
	private String bostonButt;
	private String freshSide;
	private String freshHam;
	private String spareRibs;
	private String sausage;
	private String lard;
	private String head;
	private String jowl;
	private String hocks;
	private String curedHam;
	private String curedBacon;
	private int ctChops;
	private int ctPicnic;
	private int ctBoston;
	private int ctFreshSide;
	private int ctFreshHam;
	private int ctSpareRibs;
	private int ctSausage;
	private int ctJowl;
	private int ctHocks;
	private int ctCuredHam;
	private int ctCuredBacon;
	private int chopstp;
	private int curedHigh;
	private int curedLow;
	private String special;
	private String cloin;
	private String cark;
	private String cshoulder;
	private String cjowl;
	private String chock;
	private String clc;
	private String cac;
	private String csc;
	private String cjc;
	private String chc;
	private String ccuredHam;
	private String ccuredBacon;
	private Integer tagNumber;
	private Integer liveWeight;
	private Integer hangingWeight;
	private Integer order;

	public PorkcuttingId() {
	}

	public PorkcuttingId(int counter, int beefId, int ctChops, int ctPicnic, int ctBoston, int ctFreshSide,
			int ctFreshHam, int ctSpareRibs, int ctSausage, int ctJowl, int ctHocks, int ctCuredHam, int ctCuredBacon,
			int chopstp, int curedHigh, int curedLow) {
		this.counter = counter;
		this.beefId = beefId;
		this.ctChops = ctChops;
		this.ctPicnic = ctPicnic;
		this.ctBoston = ctBoston;
		this.ctFreshSide = ctFreshSide;
		this.ctFreshHam = ctFreshHam;
		this.ctSpareRibs = ctSpareRibs;
		this.ctSausage = ctSausage;
		this.ctJowl = ctJowl;
		this.ctHocks = ctHocks;
		this.ctCuredHam = ctCuredHam;
		this.ctCuredBacon = ctCuredBacon;
		this.chopstp = chopstp;
		this.curedHigh = curedHigh;
		this.curedLow = curedLow;
	}

	public PorkcuttingId(int counter, int beefId, String name, Date deliveryDate, String chops, String picnic,
			String bostonButt, String freshSide, String freshHam, String spareRibs, String sausage, String lard,
			String head, String jowl, String hocks, String curedHam, String curedBacon, int ctChops, int ctPicnic,
			int ctBoston, int ctFreshSide, int ctFreshHam, int ctSpareRibs, int ctSausage, int ctJowl, int ctHocks,
			int ctCuredHam, int ctCuredBacon, int chopstp, int curedHigh, int curedLow, String special, String cloin,
			String cark, String cshoulder, String cjowl, String chock, String clc, String cac, String csc, String cjc,
			String chc, String ccuredHam, String ccuredBacon, Integer tagNumber, Integer liveWeight,
			Integer hangingWeight, Integer order) {
		this.counter = counter;
		this.beefId = beefId;
		this.name = name;
		this.deliveryDate = deliveryDate;
		this.chops = chops;
		this.picnic = picnic;
		this.bostonButt = bostonButt;
		this.freshSide = freshSide;
		this.freshHam = freshHam;
		this.spareRibs = spareRibs;
		this.sausage = sausage;
		this.lard = lard;
		this.head = head;
		this.jowl = jowl;
		this.hocks = hocks;
		this.curedHam = curedHam;
		this.curedBacon = curedBacon;
		this.ctChops = ctChops;
		this.ctPicnic = ctPicnic;
		this.ctBoston = ctBoston;
		this.ctFreshSide = ctFreshSide;
		this.ctFreshHam = ctFreshHam;
		this.ctSpareRibs = ctSpareRibs;
		this.ctSausage = ctSausage;
		this.ctJowl = ctJowl;
		this.ctHocks = ctHocks;
		this.ctCuredHam = ctCuredHam;
		this.ctCuredBacon = ctCuredBacon;
		this.chopstp = chopstp;
		this.curedHigh = curedHigh;
		this.curedLow = curedLow;
		this.special = special;
		this.cloin = cloin;
		this.cark = cark;
		this.cshoulder = cshoulder;
		this.cjowl = cjowl;
		this.chock = chock;
		this.clc = clc;
		this.cac = cac;
		this.csc = csc;
		this.cjc = cjc;
		this.chc = chc;
		this.ccuredHam = ccuredHam;
		this.ccuredBacon = ccuredBacon;
		this.tagNumber = tagNumber;
		this.liveWeight = liveWeight;
		this.hangingWeight = hangingWeight;
		this.order = order;
	}

	public int getCounter() {
		return this.counter;
	}

	public void setCounter(int counter) {
		this.counter = counter;
	}

	public int getBeefId() {
		return this.beefId;
	}

	public void setBeefId(int beefId) {
		this.beefId = beefId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getDeliveryDate() {
		return this.deliveryDate;
	}

	public void setDeliveryDate(Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	public String getChops() {
		return this.chops;
	}

	public void setChops(String chops) {
		this.chops = chops;
	}

	public String getPicnic() {
		return this.picnic;
	}

	public void setPicnic(String picnic) {
		this.picnic = picnic;
	}

	public String getBostonButt() {
		return this.bostonButt;
	}

	public void setBostonButt(String bostonButt) {
		this.bostonButt = bostonButt;
	}

	public String getFreshSide() {
		return this.freshSide;
	}

	public void setFreshSide(String freshSide) {
		this.freshSide = freshSide;
	}

	public String getFreshHam() {
		return this.freshHam;
	}

	public void setFreshHam(String freshHam) {
		this.freshHam = freshHam;
	}

	public String getSpareRibs() {
		return this.spareRibs;
	}

	public void setSpareRibs(String spareRibs) {
		this.spareRibs = spareRibs;
	}

	public String getSausage() {
		return this.sausage;
	}

	public void setSausage(String sausage) {
		this.sausage = sausage;
	}

	public String getLard() {
		return this.lard;
	}

	public void setLard(String lard) {
		this.lard = lard;
	}

	public String getHead() {
		return this.head;
	}

	public void setHead(String head) {
		this.head = head;
	}

	public String getJowl() {
		return this.jowl;
	}

	public void setJowl(String jowl) {
		this.jowl = jowl;
	}

	public String getHocks() {
		return this.hocks;
	}

	public void setHocks(String hocks) {
		this.hocks = hocks;
	}

	public String getCuredHam() {
		return this.curedHam;
	}

	public void setCuredHam(String curedHam) {
		this.curedHam = curedHam;
	}

	public String getCuredBacon() {
		return this.curedBacon;
	}

	public void setCuredBacon(String curedBacon) {
		this.curedBacon = curedBacon;
	}

	public int getCtChops() {
		return this.ctChops;
	}

	public void setCtChops(int ctChops) {
		this.ctChops = ctChops;
	}

	public int getCtPicnic() {
		return this.ctPicnic;
	}

	public void setCtPicnic(int ctPicnic) {
		this.ctPicnic = ctPicnic;
	}

	public int getCtBoston() {
		return this.ctBoston;
	}

	public void setCtBoston(int ctBoston) {
		this.ctBoston = ctBoston;
	}

	public int getCtFreshSide() {
		return this.ctFreshSide;
	}

	public void setCtFreshSide(int ctFreshSide) {
		this.ctFreshSide = ctFreshSide;
	}

	public int getCtFreshHam() {
		return this.ctFreshHam;
	}

	public void setCtFreshHam(int ctFreshHam) {
		this.ctFreshHam = ctFreshHam;
	}

	public int getCtSpareRibs() {
		return this.ctSpareRibs;
	}

	public void setCtSpareRibs(int ctSpareRibs) {
		this.ctSpareRibs = ctSpareRibs;
	}

	public int getCtSausage() {
		return this.ctSausage;
	}

	public void setCtSausage(int ctSausage) {
		this.ctSausage = ctSausage;
	}

	public int getCtJowl() {
		return this.ctJowl;
	}

	public void setCtJowl(int ctJowl) {
		this.ctJowl = ctJowl;
	}

	public int getCtHocks() {
		return this.ctHocks;
	}

	public void setCtHocks(int ctHocks) {
		this.ctHocks = ctHocks;
	}

	public int getCtCuredHam() {
		return this.ctCuredHam;
	}

	public void setCtCuredHam(int ctCuredHam) {
		this.ctCuredHam = ctCuredHam;
	}

	public int getCtCuredBacon() {
		return this.ctCuredBacon;
	}

	public void setCtCuredBacon(int ctCuredBacon) {
		this.ctCuredBacon = ctCuredBacon;
	}

	public int getChopstp() {
		return this.chopstp;
	}

	public void setChopstp(int chopstp) {
		this.chopstp = chopstp;
	}

	public int getCuredHigh() {
		return this.curedHigh;
	}

	public void setCuredHigh(int curedHigh) {
		this.curedHigh = curedHigh;
	}

	public int getCuredLow() {
		return this.curedLow;
	}

	public void setCuredLow(int curedLow) {
		this.curedLow = curedLow;
	}

	public String getSpecial() {
		return this.special;
	}

	public void setSpecial(String special) {
		this.special = special;
	}

	public String getCloin() {
		return this.cloin;
	}

	public void setCloin(String cloin) {
		this.cloin = cloin;
	}

	public String getCark() {
		return this.cark;
	}

	public void setCark(String cark) {
		this.cark = cark;
	}

	public String getCshoulder() {
		return this.cshoulder;
	}

	public void setCshoulder(String cshoulder) {
		this.cshoulder = cshoulder;
	}

	public String getCjowl() {
		return this.cjowl;
	}

	public void setCjowl(String cjowl) {
		this.cjowl = cjowl;
	}

	public String getChock() {
		return this.chock;
	}

	public void setChock(String chock) {
		this.chock = chock;
	}

	public String getClc() {
		return this.clc;
	}

	public void setClc(String clc) {
		this.clc = clc;
	}

	public String getCac() {
		return this.cac;
	}

	public void setCac(String cac) {
		this.cac = cac;
	}

	public String getCsc() {
		return this.csc;
	}

	public void setCsc(String csc) {
		this.csc = csc;
	}

	public String getCjc() {
		return this.cjc;
	}

	public void setCjc(String cjc) {
		this.cjc = cjc;
	}

	public String getChc() {
		return this.chc;
	}

	public void setChc(String chc) {
		this.chc = chc;
	}

	public String getCcuredHam() {
		return this.ccuredHam;
	}

	public void setCcuredHam(String ccuredHam) {
		this.ccuredHam = ccuredHam;
	}

	public String getCcuredBacon() {
		return this.ccuredBacon;
	}

	public void setCcuredBacon(String ccuredBacon) {
		this.ccuredBacon = ccuredBacon;
	}

	public Integer getTagNumber() {
		return this.tagNumber;
	}

	public void setTagNumber(Integer tagNumber) {
		this.tagNumber = tagNumber;
	}

	public Integer getLiveWeight() {
		return this.liveWeight;
	}

	public void setLiveWeight(Integer liveWeight) {
		this.liveWeight = liveWeight;
	}

	public Integer getHangingWeight() {
		return this.hangingWeight;
	}

	public void setHangingWeight(Integer hangingWeight) {
		this.hangingWeight = hangingWeight;
	}

	public Integer getOrder() {
		return this.order;
	}

	public void setOrder(Integer order) {
		this.order = order;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PorkcuttingId))
			return false;
		PorkcuttingId castOther = (PorkcuttingId) other;

		return (this.getCounter() == castOther.getCounter()) && (this.getBeefId() == castOther.getBeefId())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getDeliveryDate() == castOther.getDeliveryDate())
						|| (this.getDeliveryDate() != null && castOther.getDeliveryDate() != null
								&& this.getDeliveryDate().equals(castOther.getDeliveryDate())))
				&& ((this.getChops() == castOther.getChops()) || (this.getChops() != null
						&& castOther.getChops() != null && this.getChops().equals(castOther.getChops())))
				&& ((this.getPicnic() == castOther.getPicnic()) || (this.getPicnic() != null
						&& castOther.getPicnic() != null && this.getPicnic().equals(castOther.getPicnic())))
				&& ((this.getBostonButt() == castOther.getBostonButt()) || (this.getBostonButt() != null
						&& castOther.getBostonButt() != null && this.getBostonButt().equals(castOther.getBostonButt())))
				&& ((this.getFreshSide() == castOther.getFreshSide()) || (this.getFreshSide() != null
						&& castOther.getFreshSide() != null && this.getFreshSide().equals(castOther.getFreshSide())))
				&& ((this.getFreshHam() == castOther.getFreshHam()) || (this.getFreshHam() != null
						&& castOther.getFreshHam() != null && this.getFreshHam().equals(castOther.getFreshHam())))
				&& ((this.getSpareRibs() == castOther.getSpareRibs()) || (this.getSpareRibs() != null
						&& castOther.getSpareRibs() != null && this.getSpareRibs().equals(castOther.getSpareRibs())))
				&& ((this.getSausage() == castOther.getSausage()) || (this.getSausage() != null
						&& castOther.getSausage() != null && this.getSausage().equals(castOther.getSausage())))
				&& ((this.getLard() == castOther.getLard()) || (this.getLard() != null && castOther.getLard() != null
						&& this.getLard().equals(castOther.getLard())))
				&& ((this.getHead() == castOther.getHead()) || (this.getHead() != null && castOther.getHead() != null
						&& this.getHead().equals(castOther.getHead())))
				&& ((this.getJowl() == castOther.getJowl()) || (this.getJowl() != null && castOther.getJowl() != null
						&& this.getJowl().equals(castOther.getJowl())))
				&& ((this.getHocks() == castOther.getHocks()) || (this.getHocks() != null
						&& castOther.getHocks() != null && this.getHocks().equals(castOther.getHocks())))
				&& ((this.getCuredHam() == castOther.getCuredHam()) || (this.getCuredHam() != null
						&& castOther.getCuredHam() != null && this.getCuredHam().equals(castOther.getCuredHam())))
				&& ((this.getCuredBacon() == castOther.getCuredBacon()) || (this.getCuredBacon() != null
						&& castOther.getCuredBacon() != null && this.getCuredBacon().equals(castOther.getCuredBacon())))
				&& (this.getCtChops() == castOther.getCtChops()) && (this.getCtPicnic() == castOther.getCtPicnic())
				&& (this.getCtBoston() == castOther.getCtBoston())
				&& (this.getCtFreshSide() == castOther.getCtFreshSide())
				&& (this.getCtFreshHam() == castOther.getCtFreshHam())
				&& (this.getCtSpareRibs() == castOther.getCtSpareRibs())
				&& (this.getCtSausage() == castOther.getCtSausage()) && (this.getCtJowl() == castOther.getCtJowl())
				&& (this.getCtHocks() == castOther.getCtHocks()) && (this.getCtCuredHam() == castOther.getCtCuredHam())
				&& (this.getCtCuredBacon() == castOther.getCtCuredBacon())
				&& (this.getChopstp() == castOther.getChopstp()) && (this.getCuredHigh() == castOther.getCuredHigh())
				&& (this.getCuredLow() == castOther.getCuredLow())
				&& ((this.getSpecial() == castOther.getSpecial()) || (this.getSpecial() != null
						&& castOther.getSpecial() != null && this.getSpecial().equals(castOther.getSpecial())))
				&& ((this.getCloin() == castOther.getCloin()) || (this.getCloin() != null
						&& castOther.getCloin() != null && this.getCloin().equals(castOther.getCloin())))
				&& ((this.getCark() == castOther.getCark()) || (this.getCark() != null && castOther.getCark() != null
						&& this.getCark().equals(castOther.getCark())))
				&& ((this.getCshoulder() == castOther.getCshoulder()) || (this.getCshoulder() != null
						&& castOther.getCshoulder() != null && this.getCshoulder().equals(castOther.getCshoulder())))
				&& ((this.getCjowl() == castOther.getCjowl()) || (this.getCjowl() != null
						&& castOther.getCjowl() != null && this.getCjowl().equals(castOther.getCjowl())))
				&& ((this.getChock() == castOther.getChock()) || (this.getChock() != null
						&& castOther.getChock() != null && this.getChock().equals(castOther.getChock())))
				&& ((this.getClc() == castOther.getClc()) || (this.getClc() != null && castOther.getClc() != null
						&& this.getClc().equals(castOther.getClc())))
				&& ((this.getCac() == castOther.getCac()) || (this.getCac() != null && castOther.getCac() != null
						&& this.getCac().equals(castOther.getCac())))
				&& ((this.getCsc() == castOther.getCsc()) || (this.getCsc() != null && castOther.getCsc() != null
						&& this.getCsc().equals(castOther.getCsc())))
				&& ((this.getCjc() == castOther.getCjc()) || (this.getCjc() != null && castOther.getCjc() != null
						&& this.getCjc().equals(castOther.getCjc())))
				&& ((this.getChc() == castOther.getChc()) || (this.getChc() != null && castOther.getChc() != null
						&& this.getChc().equals(castOther.getChc())))
				&& ((this.getCcuredHam() == castOther.getCcuredHam()) || (this.getCcuredHam() != null
						&& castOther.getCcuredHam() != null && this.getCcuredHam().equals(castOther.getCcuredHam())))
				&& ((this.getCcuredBacon() == castOther.getCcuredBacon())
						|| (this.getCcuredBacon() != null && castOther.getCcuredBacon() != null
								&& this.getCcuredBacon().equals(castOther.getCcuredBacon())))
				&& ((this.getTagNumber() == castOther.getTagNumber()) || (this.getTagNumber() != null
						&& castOther.getTagNumber() != null && this.getTagNumber().equals(castOther.getTagNumber())))
				&& ((this.getLiveWeight() == castOther.getLiveWeight()) || (this.getLiveWeight() != null
						&& castOther.getLiveWeight() != null && this.getLiveWeight().equals(castOther.getLiveWeight())))
				&& ((this.getHangingWeight() == castOther.getHangingWeight())
						|| (this.getHangingWeight() != null && castOther.getHangingWeight() != null
								&& this.getHangingWeight().equals(castOther.getHangingWeight())))
				&& ((this.getOrder() == castOther.getOrder()) || (this.getOrder() != null
						&& castOther.getOrder() != null && this.getOrder().equals(castOther.getOrder())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCounter();
		result = 37 * result + this.getBeefId();
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getDeliveryDate() == null ? 0 : this.getDeliveryDate().hashCode());
		result = 37 * result + (getChops() == null ? 0 : this.getChops().hashCode());
		result = 37 * result + (getPicnic() == null ? 0 : this.getPicnic().hashCode());
		result = 37 * result + (getBostonButt() == null ? 0 : this.getBostonButt().hashCode());
		result = 37 * result + (getFreshSide() == null ? 0 : this.getFreshSide().hashCode());
		result = 37 * result + (getFreshHam() == null ? 0 : this.getFreshHam().hashCode());
		result = 37 * result + (getSpareRibs() == null ? 0 : this.getSpareRibs().hashCode());
		result = 37 * result + (getSausage() == null ? 0 : this.getSausage().hashCode());
		result = 37 * result + (getLard() == null ? 0 : this.getLard().hashCode());
		result = 37 * result + (getHead() == null ? 0 : this.getHead().hashCode());
		result = 37 * result + (getJowl() == null ? 0 : this.getJowl().hashCode());
		result = 37 * result + (getHocks() == null ? 0 : this.getHocks().hashCode());
		result = 37 * result + (getCuredHam() == null ? 0 : this.getCuredHam().hashCode());
		result = 37 * result + (getCuredBacon() == null ? 0 : this.getCuredBacon().hashCode());
		result = 37 * result + this.getCtChops();
		result = 37 * result + this.getCtPicnic();
		result = 37 * result + this.getCtBoston();
		result = 37 * result + this.getCtFreshSide();
		result = 37 * result + this.getCtFreshHam();
		result = 37 * result + this.getCtSpareRibs();
		result = 37 * result + this.getCtSausage();
		result = 37 * result + this.getCtJowl();
		result = 37 * result + this.getCtHocks();
		result = 37 * result + this.getCtCuredHam();
		result = 37 * result + this.getCtCuredBacon();
		result = 37 * result + this.getChopstp();
		result = 37 * result + this.getCuredHigh();
		result = 37 * result + this.getCuredLow();
		result = 37 * result + (getSpecial() == null ? 0 : this.getSpecial().hashCode());
		result = 37 * result + (getCloin() == null ? 0 : this.getCloin().hashCode());
		result = 37 * result + (getCark() == null ? 0 : this.getCark().hashCode());
		result = 37 * result + (getCshoulder() == null ? 0 : this.getCshoulder().hashCode());
		result = 37 * result + (getCjowl() == null ? 0 : this.getCjowl().hashCode());
		result = 37 * result + (getChock() == null ? 0 : this.getChock().hashCode());
		result = 37 * result + (getClc() == null ? 0 : this.getClc().hashCode());
		result = 37 * result + (getCac() == null ? 0 : this.getCac().hashCode());
		result = 37 * result + (getCsc() == null ? 0 : this.getCsc().hashCode());
		result = 37 * result + (getCjc() == null ? 0 : this.getCjc().hashCode());
		result = 37 * result + (getChc() == null ? 0 : this.getChc().hashCode());
		result = 37 * result + (getCcuredHam() == null ? 0 : this.getCcuredHam().hashCode());
		result = 37 * result + (getCcuredBacon() == null ? 0 : this.getCcuredBacon().hashCode());
		result = 37 * result + (getTagNumber() == null ? 0 : this.getTagNumber().hashCode());
		result = 37 * result + (getLiveWeight() == null ? 0 : this.getLiveWeight().hashCode());
		result = 37 * result + (getHangingWeight() == null ? 0 : this.getHangingWeight().hashCode());
		result = 37 * result + (getOrder() == null ? 0 : this.getOrder().hashCode());
		return result;
	}

}
