package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * Prices generated by hbm2java
 */
public class Prices implements java.io.Serializable {

	private PricesId id;

	public Prices() {
	}

	public Prices(PricesId id) {
		this.id = id;
	}

	public PricesId getId() {
		return this.id;
	}

	public void setId(PricesId id) {
		this.id = id;
	}

}
