package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * PrintersId generated by hbm2java
 */
public class PrintersId implements java.io.Serializable {

	private int id;
	private String printer;
	private String printerName;
	private String computer;

	public PrintersId() {
	}

	public PrintersId(int id) {
		this.id = id;
	}

	public PrintersId(int id, String printer, String printerName, String computer) {
		this.id = id;
		this.printer = printer;
		this.printerName = printerName;
		this.computer = computer;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getPrinter() {
		return this.printer;
	}

	public void setPrinter(String printer) {
		this.printer = printer;
	}

	public String getPrinterName() {
		return this.printerName;
	}

	public void setPrinterName(String printerName) {
		this.printerName = printerName;
	}

	public String getComputer() {
		return this.computer;
	}

	public void setComputer(String computer) {
		this.computer = computer;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrintersId))
			return false;
		PrintersId castOther = (PrintersId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getPrinter() == castOther.getPrinter()) || (this.getPrinter() != null
						&& castOther.getPrinter() != null && this.getPrinter().equals(castOther.getPrinter())))
				&& ((this.getPrinterName() == castOther.getPrinterName())
						|| (this.getPrinterName() != null && castOther.getPrinterName() != null
								&& this.getPrinterName().equals(castOther.getPrinterName())))
				&& ((this.getComputer() == castOther.getComputer()) || (this.getComputer() != null
						&& castOther.getComputer() != null && this.getComputer().equals(castOther.getComputer())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getPrinter() == null ? 0 : this.getPrinter().hashCode());
		result = 37 * result + (getPrinterName() == null ? 0 : this.getPrinterName().hashCode());
		result = 37 * result + (getComputer() == null ? 0 : this.getComputer().hashCode());
		return result;
	}

}
