package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

import java.math.BigDecimal;

/**
 * Retaillist generated by hbm2java
 */
public class Retaillist implements java.io.Serializable {

	private Integer id;
	private int ctid;
	private String retailName;
	private BigDecimal retailPrice;
	private BigDecimal weight;
	private BigDecimal extendedPrice;

	public Retaillist() {
	}

	public Retaillist(int ctid, String retailName, BigDecimal retailPrice) {
		this.ctid = ctid;
		this.retailName = retailName;
		this.retailPrice = retailPrice;
	}

	public Retaillist(int ctid, String retailName, BigDecimal retailPrice, BigDecimal weight,
			BigDecimal extendedPrice) {
		this.ctid = ctid;
		this.retailName = retailName;
		this.retailPrice = retailPrice;
		this.weight = weight;
		this.extendedPrice = extendedPrice;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getCtid() {
		return this.ctid;
	}

	public void setCtid(int ctid) {
		this.ctid = ctid;
	}

	public String getRetailName() {
		return this.retailName;
	}

	public void setRetailName(String retailName) {
		this.retailName = retailName;
	}

	public BigDecimal getRetailPrice() {
		return this.retailPrice;
	}

	public void setRetailPrice(BigDecimal retailPrice) {
		this.retailPrice = retailPrice;
	}

	public BigDecimal getWeight() {
		return this.weight;
	}

	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	public BigDecimal getExtendedPrice() {
		return this.extendedPrice;
	}

	public void setExtendedPrice(BigDecimal extendedPrice) {
		this.extendedPrice = extendedPrice;
	}

}
