package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * Sausages generated by hbm2java
 */
public class Sausages implements java.io.Serializable {

	private SausagesId id;

	public Sausages() {
	}

	public Sausages(SausagesId id) {
		this.id = id;
	}

	public SausagesId getId() {
		return this.id;
	}

	public void setId(SausagesId id) {
		this.id = id;
	}

}
