package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * SausagesId generated by hbm2java
 */
public class SausagesId implements java.io.Serializable {

	private String type;
	private Double meat;
	private Double pork;
	private Double other;
	private String seasoning;

	public SausagesId() {
	}

	public SausagesId(String type, Double meat, Double pork, Double other, String seasoning) {
		this.type = type;
		this.meat = meat;
		this.pork = pork;
		this.other = other;
		this.seasoning = seasoning;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Double getMeat() {
		return this.meat;
	}

	public void setMeat(Double meat) {
		this.meat = meat;
	}

	public Double getPork() {
		return this.pork;
	}

	public void setPork(Double pork) {
		this.pork = pork;
	}

	public Double getOther() {
		return this.other;
	}

	public void setOther(Double other) {
		this.other = other;
	}

	public String getSeasoning() {
		return this.seasoning;
	}

	public void setSeasoning(String seasoning) {
		this.seasoning = seasoning;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SausagesId))
			return false;
		SausagesId castOther = (SausagesId) other;

		return ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null
				&& this.getType().equals(castOther.getType())))
				&& ((this.getMeat() == castOther.getMeat()) || (this.getMeat() != null && castOther.getMeat() != null
						&& this.getMeat().equals(castOther.getMeat())))
				&& ((this.getPork() == castOther.getPork()) || (this.getPork() != null && castOther.getPork() != null
						&& this.getPork().equals(castOther.getPork())))
				&& ((this.getOther() == castOther.getOther()) || (this.getOther() != null
						&& castOther.getOther() != null && this.getOther().equals(castOther.getOther())))
				&& ((this.getSeasoning() == castOther.getSeasoning()) || (this.getSeasoning() != null
						&& castOther.getSeasoning() != null && this.getSeasoning().equals(castOther.getSeasoning())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result + (getMeat() == null ? 0 : this.getMeat().hashCode());
		result = 37 * result + (getPork() == null ? 0 : this.getPork().hashCode());
		result = 37 * result + (getOther() == null ? 0 : this.getOther().hashCode());
		result = 37 * result + (getSeasoning() == null ? 0 : this.getSeasoning().hashCode());
		return result;
	}

}
