package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * Seasoning generated by hbm2java
 */
public class Seasoning implements java.io.Serializable {

	private SeasoningId id;

	public Seasoning() {
	}

	public Seasoning(SeasoningId id) {
		this.id = id;
	}

	public SeasoningId getId() {
		return this.id;
	}

	public void setId(SeasoningId id) {
		this.id = id;
	}

}
