package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * Test generated by hbm2java
 */
public class Test implements java.io.Serializable {

	private Long counter;

	public Test() {
	}

	public Test(Long counter) {
		this.counter = counter;
	}

	public Long getCounter() {
		return this.counter;
	}

	public void setCounter(Long counter) {
		this.counter = counter;
	}

}
