package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * Town generated by hbm2java
 */
public class Town implements java.io.Serializable {

	private Integer id;
	private String city;
	private String state;
	private String zip;

	public Town() {
	}

	public Town(String city, String state, String zip) {
		this.city = city;
		this.state = state;
		this.zip = zip;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

}
