package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;

/**
 * Traceback generated by hbm2java
 */
public class Traceback implements java.io.Serializable {

	private Integer counter;
	private int customerId;
	private String product;
	private int boxNumber;
	private int beefCounter;
	private Date dateGround;
	private Date saniDate;
	private Integer pkgCount;

	public Traceback() {
	}

	public Traceback(int customerId, String product, int boxNumber, int beefCounter, Date dateGround, Date saniDate) {
		this.customerId = customerId;
		this.product = product;
		this.boxNumber = boxNumber;
		this.beefCounter = beefCounter;
		this.dateGround = dateGround;
		this.saniDate = saniDate;
	}

	public Traceback(int customerId, String product, int boxNumber, int beefCounter, Date dateGround, Date saniDate,
			Integer pkgCount) {
		this.customerId = customerId;
		this.product = product;
		this.boxNumber = boxNumber;
		this.beefCounter = beefCounter;
		this.dateGround = dateGround;
		this.saniDate = saniDate;
		this.pkgCount = pkgCount;
	}

	public Integer getCounter() {
		return this.counter;
	}

	public void setCounter(Integer counter) {
		this.counter = counter;
	}

	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	public String getProduct() {
		return this.product;
	}

	public void setProduct(String product) {
		this.product = product;
	}

	public int getBoxNumber() {
		return this.boxNumber;
	}

	public void setBoxNumber(int boxNumber) {
		this.boxNumber = boxNumber;
	}

	public int getBeefCounter() {
		return this.beefCounter;
	}

	public void setBeefCounter(int beefCounter) {
		this.beefCounter = beefCounter;
	}

	public Date getDateGround() {
		return this.dateGround;
	}

	public void setDateGround(Date dateGround) {
		this.dateGround = dateGround;
	}

	public Date getSaniDate() {
		return this.saniDate;
	}

	public void setSaniDate(Date saniDate) {
		this.saniDate = saniDate;
	}

	public Integer getPkgCount() {
		return this.pkgCount;
	}

	public void setPkgCount(Integer pkgCount) {
		this.pkgCount = pkgCount;
	}

}
