package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;

/**
 * Xactions generated by hbm2java
 */
public class Xactions implements java.io.Serializable {

	private Integer id;
	private int counter;
	private Date date;
	private Date time;
	private String species;
	private Float meatSales;
	private Float tax;
	private Float nontax;
	private Float lockerRent;
	private Float curing;
	private Float processing;
	private Float pprocessing;
	private Float dprocessing;
	private Float other;
	private Float total;
	private String method;
	private Float amount;
	private Float change;
	private boolean zzed;
	private String name;
	private Double multi;
	private double transactionNumber;

	public Xactions() {
	}

	public Xactions(int counter, boolean zzed, double transactionNumber) {
		this.counter = counter;
		this.zzed = zzed;
		this.transactionNumber = transactionNumber;
	}

	public Xactions(int counter, Date date, Date time, String species, Float meatSales, Float tax, Float nontax,
			Float lockerRent, Float curing, Float processing, Float pprocessing, Float dprocessing, Float other,
			Float total, String method, Float amount, Float change, boolean zzed, String name, Double multi,
			double transactionNumber) {
		this.counter = counter;
		this.date = date;
		this.time = time;
		this.species = species;
		this.meatSales = meatSales;
		this.tax = tax;
		this.nontax = nontax;
		this.lockerRent = lockerRent;
		this.curing = curing;
		this.processing = processing;
		this.pprocessing = pprocessing;
		this.dprocessing = dprocessing;
		this.other = other;
		this.total = total;
		this.method = method;
		this.amount = amount;
		this.change = change;
		this.zzed = zzed;
		this.name = name;
		this.multi = multi;
		this.transactionNumber = transactionNumber;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getCounter() {
		return this.counter;
	}

	public void setCounter(int counter) {
		this.counter = counter;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getSpecies() {
		return this.species;
	}

	public void setSpecies(String species) {
		this.species = species;
	}

	public Float getMeatSales() {
		return this.meatSales;
	}

	public void setMeatSales(Float meatSales) {
		this.meatSales = meatSales;
	}

	public Float getTax() {
		return this.tax;
	}

	public void setTax(Float tax) {
		this.tax = tax;
	}

	public Float getNontax() {
		return this.nontax;
	}

	public void setNontax(Float nontax) {
		this.nontax = nontax;
	}

	public Float getLockerRent() {
		return this.lockerRent;
	}

	public void setLockerRent(Float lockerRent) {
		this.lockerRent = lockerRent;
	}

	public Float getCuring() {
		return this.curing;
	}

	public void setCuring(Float curing) {
		this.curing = curing;
	}

	public Float getProcessing() {
		return this.processing;
	}

	public void setProcessing(Float processing) {
		this.processing = processing;
	}

	public Float getPprocessing() {
		return this.pprocessing;
	}

	public void setPprocessing(Float pprocessing) {
		this.pprocessing = pprocessing;
	}

	public Float getDprocessing() {
		return this.dprocessing;
	}

	public void setDprocessing(Float dprocessing) {
		this.dprocessing = dprocessing;
	}

	public Float getOther() {
		return this.other;
	}

	public void setOther(Float other) {
		this.other = other;
	}

	public Float getTotal() {
		return this.total;
	}

	public void setTotal(Float total) {
		this.total = total;
	}

	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	public Float getAmount() {
		return this.amount;
	}

	public void setAmount(Float amount) {
		this.amount = amount;
	}

	public Float getChange() {
		return this.change;
	}

	public void setChange(Float change) {
		this.change = change;
	}

	public boolean isZzed() {
		return this.zzed;
	}

	public void setZzed(boolean zzed) {
		this.zzed = zzed;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getMulti() {
		return this.multi;
	}

	public void setMulti(Double multi) {
		this.multi = multi;
	}

	public double getTransactionNumber() {
		return this.transactionNumber;
	}

	public void setTransactionNumber(double transactionNumber) {
		this.transactionNumber = transactionNumber;
	}

}
