package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

/**
 * Ztill generated by hbm2java
 */
public class Ztill implements java.io.Serializable {

	private ZtillId id;

	public Ztill() {
	}

	public Ztill(ZtillId id) {
		this.id = id;
	}

	public ZtillId getId() {
		return this.id;
	}

	public void setId(ZtillId id) {
		this.id = id;
	}

}
