package lockerdata.schema.model;
// Generated Feb 17, 2018 5:14:42 PM by Hibernate Tools 5.2.8.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * ZtillId generated by hbm2java
 */
public class ZtillId implements java.io.Serializable {

	private Date date;
	private Double meatSales;
	private Double lockerRent;
	private Double tax;
	private Double processing;
	private Double porkProcessing;
	private Double deerProcessing;
	private Double curingSeasoning;
	private BigDecimal hides;
	private BigDecimal dogFood;

	public ZtillId() {
	}

	public ZtillId(Date date, Double meatSales, Double lockerRent, Double tax, Double processing, Double porkProcessing,
			Double deerProcessing, Double curingSeasoning, BigDecimal hides, BigDecimal dogFood) {
		this.date = date;
		this.meatSales = meatSales;
		this.lockerRent = lockerRent;
		this.tax = tax;
		this.processing = processing;
		this.porkProcessing = porkProcessing;
		this.deerProcessing = deerProcessing;
		this.curingSeasoning = curingSeasoning;
		this.hides = hides;
		this.dogFood = dogFood;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Double getMeatSales() {
		return this.meatSales;
	}

	public void setMeatSales(Double meatSales) {
		this.meatSales = meatSales;
	}

	public Double getLockerRent() {
		return this.lockerRent;
	}

	public void setLockerRent(Double lockerRent) {
		this.lockerRent = lockerRent;
	}

	public Double getTax() {
		return this.tax;
	}

	public void setTax(Double tax) {
		this.tax = tax;
	}

	public Double getProcessing() {
		return this.processing;
	}

	public void setProcessing(Double processing) {
		this.processing = processing;
	}

	public Double getPorkProcessing() {
		return this.porkProcessing;
	}

	public void setPorkProcessing(Double porkProcessing) {
		this.porkProcessing = porkProcessing;
	}

	public Double getDeerProcessing() {
		return this.deerProcessing;
	}

	public void setDeerProcessing(Double deerProcessing) {
		this.deerProcessing = deerProcessing;
	}

	public Double getCuringSeasoning() {
		return this.curingSeasoning;
	}

	public void setCuringSeasoning(Double curingSeasoning) {
		this.curingSeasoning = curingSeasoning;
	}

	public BigDecimal getHides() {
		return this.hides;
	}

	public void setHides(BigDecimal hides) {
		this.hides = hides;
	}

	public BigDecimal getDogFood() {
		return this.dogFood;
	}

	public void setDogFood(BigDecimal dogFood) {
		this.dogFood = dogFood;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ZtillId))
			return false;
		ZtillId castOther = (ZtillId) other;

		return ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
				&& this.getDate().equals(castOther.getDate())))
				&& ((this.getMeatSales() == castOther.getMeatSales()) || (this.getMeatSales() != null
						&& castOther.getMeatSales() != null && this.getMeatSales().equals(castOther.getMeatSales())))
				&& ((this.getLockerRent() == castOther.getLockerRent()) || (this.getLockerRent() != null
						&& castOther.getLockerRent() != null && this.getLockerRent().equals(castOther.getLockerRent())))
				&& ((this.getTax() == castOther.getTax()) || (this.getTax() != null && castOther.getTax() != null
						&& this.getTax().equals(castOther.getTax())))
				&& ((this.getProcessing() == castOther.getProcessing()) || (this.getProcessing() != null
						&& castOther.getProcessing() != null && this.getProcessing().equals(castOther.getProcessing())))
				&& ((this.getPorkProcessing() == castOther.getPorkProcessing())
						|| (this.getPorkProcessing() != null && castOther.getPorkProcessing() != null
								&& this.getPorkProcessing().equals(castOther.getPorkProcessing())))
				&& ((this.getDeerProcessing() == castOther.getDeerProcessing())
						|| (this.getDeerProcessing() != null && castOther.getDeerProcessing() != null
								&& this.getDeerProcessing().equals(castOther.getDeerProcessing())))
				&& ((this.getCuringSeasoning() == castOther.getCuringSeasoning())
						|| (this.getCuringSeasoning() != null && castOther.getCuringSeasoning() != null
								&& this.getCuringSeasoning().equals(castOther.getCuringSeasoning())))
				&& ((this.getHides() == castOther.getHides()) || (this.getHides() != null
						&& castOther.getHides() != null && this.getHides().equals(castOther.getHides())))
				&& ((this.getDogFood() == castOther.getDogFood()) || (this.getDogFood() != null
						&& castOther.getDogFood() != null && this.getDogFood().equals(castOther.getDogFood())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result + (getMeatSales() == null ? 0 : this.getMeatSales().hashCode());
		result = 37 * result + (getLockerRent() == null ? 0 : this.getLockerRent().hashCode());
		result = 37 * result + (getTax() == null ? 0 : this.getTax().hashCode());
		result = 37 * result + (getProcessing() == null ? 0 : this.getProcessing().hashCode());
		result = 37 * result + (getPorkProcessing() == null ? 0 : this.getPorkProcessing().hashCode());
		result = 37 * result + (getDeerProcessing() == null ? 0 : this.getDeerProcessing().hashCode());
		result = 37 * result + (getCuringSeasoning() == null ? 0 : this.getCuringSeasoning().hashCode());
		result = 37 * result + (getHides() == null ? 0 : this.getHides().hashCode());
		result = 37 * result + (getDogFood() == null ? 0 : this.getDogFood().hashCode());
		return result;
	}

}
